src/Camera.cc, src/Camera.h, src/GLView.cc, src/QGLView.cc
* Use correct eye position in orthogonal projection mode (fixes #1058).
* Use viewport height as "distance" for the status text in orthogonal mode. (While this is not strictly correct as the actual distance has no effect in orthogonal mode, it's giving the user an indication of the zoom factor.)
=> Orthogonal zoom fix

openscad.pro, src/PlatformUtils-win.cc, src/findversion.h
As GetVersionEx() is deprecated and will not report Windows 8.1 without
additional resource file manipulation this is now using the code from
http://hg.m1xa.com/findversion (by M1xA / MIT license) which is using the
VerifyVersionInfo API.
=> Extend Windows version detection (fixes #1076).

locale/ru.po
Looks like lines 908-909 need to be reversed for my Mac OS X build to work on my latest git pull.
Error message is:
--snip--
msgfmt -c -v -o ./locale/ru/LC_MESSAGES/openscad.mo ./locale/ru.po
./locale/ru.po:908: missing 'msgstr' section
./locale/ru.po:910:7: syntax error
msgfmt: found 2 fatal errors
error running msgfmt
make: *** [OpenSCAD.app/Contents/MacOS/OpenSCAD] Error 1
--end-snip--
Andrew.
=> Mac build failing on line 908-909

scripts/check-dependencies.sh
Fix problem with check-dependencies.sh during detection of qt under some circumstances.
- If qtchooser is installed but qmake could not be found (either qt4 or qt5), the check would hang due to grep expecting input from stdin.
- If qtchooser is installed but qmake for qt5 is not installed, the code would not actually check for the existence of qt4 qmake, since the test for ! -e $qtpath doesn't do what you want when $qtpath is empty.
=> Fix problem with check-dependencies.sh during detection of qt

src/launchingscreen.cc, src/openscad.cc
The "New" button will cause the launching screen to return with an empty
selection of files. In this case, the dummy file name "" needs to remain
in the file list to allow the main window to open.
=> Fix "New" button in launching screen.

scripts/check-dependencies.sh
Grep doesn't return matching lines when it believes that the file is a binary.
The header for opencsg seems to trigger this behaviour. Added the -a switch to
the grep invocation to force interpretation as text file.
Maybe -a should be added to all grep invocations in the whole file/directory/repository.
=> scripts/check-dependencies.sh can't determine version of opencsg

contrib/scad-mode.el
* Convert to being derived from cc-mode, as per a 2013 post from Lukasz Stelmach. This yields better indentation (particularly for continuations) as well as being simpler.
* Update keywords for the 2015.03 release (plus a couple missed from earlier)
* Use separate highlighting style for deprecated keywords.
=> Updates to Emacs scad-mode

qscintilla2.prf
Fedora installs qscintilla2.prf in the wrong location and has a different
naming scheme than the one used in Ubuntu so the existing workaround fails.
This adds yet another workaround to detect the different naming for the
Qt5 version of the QScintilla2 library.
=> Workaround for Fedora 21 builds (fixes #1254).

color-schemes/render/beforedawn.json, color-schemes/render/deepocean.json, color-schemes/render/metallic.json, color-schemes/render/monotone.json, color-schemes/render/nature.json, color-schemes/render/solarized.json, color-schemes/render/starnight.json, color-schemes/render/sunset.json, color-schemes/render/tomorrow-night.json, color-schemes/render/tomorrow.json, src/GLView.cc, src/colormap.cc, src/colormap.h
This implements the feature request in #1328.
I've added an `AXES_COLOR` key to **`ColorMap`**, and hooked it up to `axes-color` in the colorscheme JSON.
I've also updated all the colorschemes with very contrasty axis colors :smiley:
=> Add a axes-color option for color schemes

src/export.cc, src/mainwin.cc
Simple fix for the STL export failure @ocastelao mentioned in #113.
The export was just called with the UTF-8 / Local-Encoded values swapped.
=> Fix export call for non-ASCII file names.

src/MainWindow.h, src/mainwin.cc
Always check the status of the QTextStream to catch problems like disk full.
In addition QSaveFile can ensure the old file is not destroyed as it's using a temporary file which is committed at the end by just renaming it to the output file name. Unfortunately this is only available with Qt 5.1.
I guess this needs some cross-platform testing. On Linux it did not simply catch the device full problem as advertised. Instead it happily committed a zero byte length file. This is now caught by checking the QTextStream status.
=> Use QSaveFile (if available) to write designs to disk. (fixes #1350)

.gitignore, contrib/appdata.its, openscad.appdata.xml.in, scripts/translation-update.sh
- updated appdata file to a newer syntax
- created an english appdata template
- the strings are extracted during updatepot function in translation-update.sh
- the multilingual file is created at the end of updatemo in the same script
- itstool needed when running make (added this information to README)
Note: I did not update the scripts for dependencies obtaining, don't know what's the proper way of dealing with them.
Please sanity check this and let me know what you think.
=> Create multilingual appdata file using itstool

doc/translation.txt
After #1366 was merged, itstool is required to update the .po files.
=> Add a line about itstool to translation doc

doc/openscad.1, icons/openscad.desktop, locale/cs.po, locale/de.po, locale/es.po, locale/fr.po, locale/openscad.pot, locale/ru.po, src/Preferences.ui, tests/test_cmdline_tool.py
This is a bunch of probably non-controversial changes fixing the hashbang in an executable file (which is only used with explicit invocation anyway most of the time), desktop file extensions, man page line breaking errors and grammar.
The "Allow to open" issue might be better resolved by rephrasing it to not use "allow" at all (see [english localization notes](http://www.xibalba.demon.co.uk/jbr/linux/esl.html#b1)), but given it currently deviates from the other "enable" options in a seemingly purpuseful way, I didn't change it that way.
=> Minor fixes from Debian's checks

tests/test_cmdline_tool.py
When the path to the openscad binary changed in issue 1362, the relative path
was not changed and therefore led into the void, falling back to system
paths.
=> Fix path discovery for fonts

src/value.cc
On arm64 the integer constructor returns 0 for an input value of NaN. To prevent this, index values are now checked against Inf/NaN and protected against overflow using boost::numeric_cast.
=> Check for infinite double values when using values as index (fixes #1420).

opencsg.pri, openscad.pro, src/OpenCSGRenderer.cc, src/mainwin.cc
This is just a patch so that the ENABLE_OPENCSG compiler define works again, should someone want to compile without OpenCSG for whatever reason.
=> Enable compilation without OpenCSG.

src/GLView.cc
This change scales the zNear and zFar orthographic projection parameters based on the camera zoom level.
With this change, a cube renders normally with no z-fighting on edges from sizes of 1e-20 to 1e18, in orthographic view.
=> Fix Z-fighting in Ortho view, Issue #1483

cgal/decompose.pro, src/export.cc, src/export.h, src/openscad.cc, src/svg.cc
This is a small patch to allow an easier dump of already existing debug code for CGAL Nef Polyhedrons. It also adds some code to dump Sphere Map information as well.
It allows the ".nefdbg" file extension that will trigger a dump of an SVG file containing detailed information about the Nef Polyhedron and it's associated Vertex Sphere Maps. This will make it a bit easier to debug Nef Polyhedron issues in the future. The feature is left as an "undocumented" feature so that users will not rely on the format and it can change as needed.
The SVG file has dual use - it contains very detail information as 'comments' within the text file, while the file itself can be opened in a web browser to view a graphic picture of the Nef Polyhedron faces.
Here is an example of the svg text for a vertex …
=> ".nefdbg" extension to dump debug info on CGALNefPolyhedron3+SphereMaps

src/Camera.cc, src/GLView.cc
This fixes the empty PNG export for me.
Update: found the root cause (2nd commit):
* PNG export initialized camera type NONE
* export calls ViewAll which sets the camera to VECTOR
* this means cam.object_trans is not initialized as this is for GIMBAL camera
* GLView uses the garbled object translation even with camera type VECTOR
=> Camera fix

patches/CGAL-OGL_helper-tesscombine.patch, src/OGL_helper.h
This was required to ensure pcache is cleared. Without it there
was a minor memory leak.
This got accidentally removed as can be seen in the following history:
https://github.com/openscad/openscad/commits/1b31c32638faa0429ffb6af0751a2199b33c52a0/src/OGL_helper.h
=> Restores the call to combineCallback with NULL args.

src/QGLView.cc
For now this only check the error code from `glReadPixels()` to prevent invalid zoom/translation values to be calculated.
=> Check error code from glReadPixels() to prevent invalid zoom.

contrib/scad-mode.el
The feature name has to match the file name.
=> Provide correct feature in scad-mode.el

doc/openscad.1
the option -x seems to be deprecated but was still in the examples of the manpage
=> remove deprecated option from the manpage

src/export_svg.cc
Fixes  #1597.
This also sets the export unit to mm which seems to be a bit more useful than the default pixel units.
Ultimately this (and some additional options) should be user configurable (see #649).
=> Restore width & height parameters and use mm in SVG header

src/mainwin.cc
See Qt docs
http://doc.qt.io/qt-5/qfileinfo.html#baseName
http://doc.qt.io/qt-5/qfileinfo.html#completeBaseName
=> Pre-fill full file base name on export. Fix #1552.

src/mainwin.cc
The file that didn't exist before is saved to current directory, not to directory we actually expect.
=> Save to right path when multiple files are opened. Fix #1530.

src/mainwin.cc
Fixes issue #1488. Now saving action doesn't break log output in window.
=> Do not clear handler after save

src/PlatformUtils-posix.cc
GNU Make 3.81 on ubuntu 14.04 sets RLIMIT_STACK to infinity, which propagates to the commands being run. This breaks openscad as shown by the "recursion-test-function.scad" test, since (I'm guessing) it uses stack limits to detect infinit recursion.
=> Handle RLIMIT_STACK set to infinity.

src/mainwin.cc
toLocal8Bit() returns a QByteArray which casts into a const char\*, so the QByteArray must be held for the const char\* to remain valid.
=> Fix invalid use after free in compileTopLevelDocument.

src/expr.cc
OBS checks that functions always return a value when building RPM based packages:
```
[  743s] I: Program returns random data in a function
[  743s] E: openscad-nightly no-return-in-nonvoid-function src/expr.cc:94, 109, 167, 215
[  743s] 
[  743s] I: Program returns random data in a function
[  743s] E: openscad-nightly no-return-in-nonvoid-function src/expr.cc:94, 109, 167, 215
[  743s] 
[  743s] build80 failed "build openscad-nightly.spec" at Sun Jun 26 02:44:21 UTC 2016.
```
=> Ensure to always return a value to fix OBS builds.

src/FileModule.cc, src/FileModule.h, src/MainWindow.h, src/ModuleCache.cc, src/mainwin.cc, src/modcontext.cc, src/modcontext.h
This cleans up FileModule a bit to avoid having to leak its internal FileContext to allow side-effects like updating the camera from an openscad script.
This becomes important later when we want to make FileModule inherit from ASTNode.
=> Filemodule cleanup

src/scintillaeditor.cpp
I found the bug. Follow the steps to repeat:
1) **Edit** -> **Find and replace...**
2) Enter **Search string** 
3) Enter **Replacement string**
4) Click **Replace**
_When you finish replacing all strings, go to 5)_
5) Click **Replace** again 
6) And again and again
You will see that replacement string added after ever click. 
It happened because selected empty string. Need check selected string is empty or not  and if yes do not replace
=> Fix replace function: when selected string is empty do not replace 

src/export.h, src/export_png.cc, src/openscad.cc
=> Indicate failure to create offscreen buffer for PNG export with non-zero exit status.

scripts/macosx-build-dependencies.sh
Looks like the project decided to change QScintilla-gpl-* to QScintilla_gpl-* in version 2.9.2 and 2.9.3.
=> File names changed to QScintilla_gpl-2.9.2.tar.gz

src/Assignment.h, src/annotation.cc, src/assignment.cc, src/comment.cpp, src/comment.h, src/comment_parser.y, src/parameter/ParameterWidget.cc, src/parameter/parameterobject.cpp, src/parameter/parameterset.cpp, src/parameter/parametertext.cpp
@amarjeetkapoor1 @t-paul 
Could you take a look at this patch?
During code review, I struggled with understanding the Annotation
class, but I eventually realized that it's just storing an Expression
object, but has a pretty convoluted way of retrieving it. To make this
simpler and more readable, I've refactored the Annotation class down
to the bare minimum.
All tests should still be green.
I might have misunderstood something, so please comment if there is something I've left out.
@amarjeetkapoor1 If this looks OK, could just merge it into the gsoc2016-refactored branch.
=> Green Refactoring: Rewrote Annotation to work directly on an Expression object

src/MainWindow.ui, src/mainwin.cc
Current design of panel is not usability(see issue #962), so I suggest redesign.
How it looks:  
_Find..._
_Find and replace..._
=> Redesign find and replace panel

patches/qt5/QTBUG-56004.patch, patches/qt5/QTBUG-56004b.patch, scripts/macosx-build-dependencies.sh
Successfully make qt5 on MacOS using XCode.  Fix for #1838 .
This corrects QT Bug 56004 in QT 5.7.0 .  It also corrects a similar QT bug in a different file.
After this fix, QT successfully makes.  However, QScintilla fails to build so this patch is not tested to the point of a successful build of openSCAD.
=> Successfully make QT5 fix for #1838

scripts/macosx-build-dependencies.sh
=> Build tweaks to not depend on DYLD_LIBRARY_PATH during building

src/lexer.l, testdata/scad/templates/include-tests-template.scad, testdata/scad/templates/use-tests-template.scad
allowing a weird use/include syntax; `include>>><file.scad>`
=> Fixed a long-standing typo in the lexer 

scripts/macosx-build-dependencies.sh
=> Build libgmp against the core2 CPU profile to support older CPUs. Fixes #1829

src/qtgettext.h
Failed on Debian build servers: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844881
=> Handle 2 argument translation calls generated by Qt 5.7.1 (fixes #1872).

scripts/uni-build-dependencies.sh
sed command was missing a \ that caused it to fail when using standard OpenCSG makefiles (no qmake).
=> Fix missing \ in uni build script

contrib/scad-mode.el
This allows meta-b/f to work properly when navigating variable names that
contain underscores.
=> Drop underscore from syntax table in scad-mode

src/mainwin.cc, src/printutils.cc, src/printutils.h
lastmessages now cleared at the start of the compilation.
=> Fix for #1961: Warnings and errors only shown five times

src/node.cc
In reference to issue #1815.  
It prints warning for all the root modifiers added in the program with line number.
=> Print warning  with multiple roots

src/MainWindow.h, src/mainwin.cc
- Decrease tab stop width for view consoles (such as AST and CSG Tree)
- Use a constant field for all of these views for consistency.
=> Issue 1994 - Decrease tab stop width in views.

scripts/uni-get-dependencies.sh
This package must be all lower or it doesn't install on linux mint 18.1 (ubuntu 16.04 based).  I don't think package names ever have captial letters in them on debian based distros.
=> fix package name in uni-get-depencies.sh

version.pri
Now strips leading zeros instead of appending .0 to prevent integers being interpreted as octal.
=> Fixed version going wrong on Windows when the day is less than 10.

tests/test_cmdline_tool.py
Fix for #2006. Changed the regex to filter numbers with or without decimal points.
=> Fix for dump test fail on Windows

mingw-cross-env.pri, openscad.pro, src/PlatformUtils.h, tests/CMakeLists.txt
Issue #2005. openscad.pro now defines the linker stack size for all Windows builds. It also defines the constant used in platform.h to ensure they match.
=> Fix recursion check when built with MSYS2.

src/parameter/parameterset.cpp
Solves issue #1940 by adding check for parameterSets object in JSON object and create paramaterSets object if not present.
=> Solves issue1940: Adds check for parameterSets object in json

version.pri
Partially reverted #2004 so version numbers are back to floats to avoid the leading zeros.
=> Now only uses num_add on Windows builds.

src/enums.h
C++11 might prefer scoped enums but they don't play well with #define.
=> Fix for #1996 DIFFERENCE clashes with winuser.h

src/lexer.l
Uses fs::path::generic_string() for used files so they have the same format as included files.
Before this fix used paths would be in Windows format and included files in Unix format in the dependency file.
=> Make used file paths generic in the dependency file.

.travis.yml, openscad.pro, src/Dock.cc, src/Preferences.cc, src/QGLView.cc, src/QSettingsCached.cc, src/QSettingsCached.h, src/UIUtils.cc, src/editor.cc, src/launchingscreen.cc, src/legacyeditor.cc, src/mainwin.cc, src/openscad.cc
QSettings is now cached. This reduces the number of file accesses that QSettings performs. Writes to persistent storage are done periodically by QSettings in background.
Note: This also intentionally disables the test run on Travis/Ubuntu 12.04.
=> 1917: QSettings is now cached

src/dxfdata.cc, src/dxfdim.cc, src/handle_dep.cc, src/import.cc, src/import_nef.cc, src/import_stl.cc, src/linearextrude.cc, src/openscad.cc, src/rotateextrude.cc, src/surface.cc
Fix for #2024.
Dependencies can now be written for all file types, e.g. echo because they are added at module instantiation time rather than when the file is read to create geometry.
=> Fixed imports and surface files missing from dependencies.

CMakeLists.txt
Fixes the following cmake errors encountered on linux:
CMake Error at CMakeLists.txt:381 (add_executable):
Cannot find source file:
src/MainWindow.cc
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
.hxx .in .txx
CMake Error at CMakeLists.txt:381 (add_executable):
Cannot find source file:
src/AboutDialog.cc
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
.hxx .in .txx
=> Fix cmake missing file errors

README.md
Make sure that the different options are enumerated correctly, and that the text preceding them notes that only one of the three steps is necessary. Addresses #2087
=> Make the dependency installation options clearer

.gitignore, src/OGL_helper.h
Use the screen's DPI when calculating the line width and point size of wireframes.
See #2091 
<details>
<summary>1x DPI Wireframe</summary>
> Note: The "DPR" value in this screenshot was for debugging and is not included in the PR.
</details>
<details>
<summary>2x DPI Wireframe</summary>
> Note: The "DPR" value in this screenshot was for debugging and is not included in the PR.
</details>
=> DPI Normalized Wireframe Rendering

CMakeLists.txt
At least because `QOpenGLWidget` was added only in that version:
http://doc.qt.io/qt-5/qopenglwidget.html
=> CMake: require QT version 5.4 (minimum) [fix]

src/openscad.cc, src/openscad.h
Handle the `-psn_*` argument that Finder on OSX sends to apps.
> It looks like Finder appends a process ID argument.
> 
> https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder
> 
> FreeSCAD had the same problem and posted a workaround in this thread.
> 
> https://forum.freecadweb.org/viewtopic.php?t=4447
https://github.com/openscad/openscad/issues/2089#issuecomment-328371812
Fixes #2089.
=> Fix MacOS First Run

src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/input/InputEventMapper.cc, src/settings.cc, src/settings.h
add button 0 and button 9 (/dev/input/js0 numbers the first button 0. button 9 is to have an even number of buttons)
renumber the axis starting from 0 to confirm with low-level tools like jstest-gtk
(maybe we should make the numbering OS dependent?)
=> fixing "off by one error" when using /dev/input/js0

cmake/Modules/FindQt5QScintilla.cmake
Building with cmake initially didn't work for me because it couldn't find the qscintilla library. I'm on Arch Linux and the library lives at `/usr/lib/libqscintilla2_qt5.so`, which seems to be different from some other distros. I added the new name to cmake to fix.
=> Add qscintalla2_qt5 to cmake search names

tests/OpenSCAD_Test_Console.py, tests/export_import_pngtest.py, tests/mingw_convert_ctest.py, tests/shouldfail.py, tests/test_cmdline_tool.py
whitespace-only changes.
.py source files had tabs mixed with spaces, all tabs removed and indented to the appropriate multiple of 4 spaces
=> Remove mixed tab characters from python source

.travis.yml, CMakeLists.txt, openscad.pro, scripts/macosx-build-homebrew.sh, tests/CMakeLists.txt
This caches compiled object files, which can significantly speed up partial re-builds. This is most useful when switching between git branches. Normally, any changed files and dependencies would need to be re-compiled each time you switch branches. With ccache, any file that was previously compiled with the same inputs can be re-used from the cache.
I added a check so that it will only use ccache if it is installed.
=> Add ccache to cmake. #2109

openscad.pro, src/Preferences.cc, src/feature.cc, src/feature.h, src/input/InputDriver.h, src/input/InputDriverManager.cc, src/input/InputDriverManager.h, src/input/InputEventMapper.cc, src/input/InputEventMapper.h, src/input/JoystickInputDriver.cc, src/input/JoystickInputDriver.h, src/openscad.cc
Added the inputdriver to the list of experimental features.
CONFIG+=experimental as we explicitly work on an experimental feature.
Add code to stop the drivers when the features gets disabled during run time.
Hide the UI when the feature is disabled.
I think it makes sense tobe able to disable the inputdriver(s), even when the feature becomes one day stable.
=> Make Inputdriver5 an experimental Feature

src/Preferences.cc, src/input/InputEventMapper.cc, src/settings.cc, src/settings.h
I think it is easier in the long run, when we use for-loops where possible instead of copy&paste code.
Offcourse, there are no input devices with an unlimited number of buttons, but the buttons on for e.g. a gamepad add up quickly.
"getSettingEntryByName" will also become infrastructure for things like axis calibration, where we need to save and restore values for currently nine axis. "getSettingEntryByName" allows the - as shown - to access the settings kind of like an array.
=> using for loops instead of copy&paste code

src/Preferences.cc, src/Preferences.h, src/input/InputEventMapper.cc, src/input/InputEventMapper.h
Showing which button the user is currently is pressing greatly simplifies the input mapping for the user.
It has to be "on time" and not "on event", as my cheap gamepad with turbo function managed to glitch and then crash the UI. Updating the UI "on time" naturally limits and bottlenecks this kind of abuse.
In order tobe able to do something "on time" I need to store the button state. To only update the UI when needed, I compare the current button state to the previous button state. In order to not constantly create QStrings, I use constants for the QStrings.
Note that I use findChild to find the label to be affected. The benefit is, that we can easily scale to more buttons. The drawback is, that the compiler can not check it.
Note that I use seperate for-loops for buttons and axis, …
=> show the pressed button in the preference UI

src/input/InputEventMapper.cc, src/input/InputEventMapper.h
I think we agree that using constant for array sizes is better then magic numbers.
How ever: I am uncertain how and where in openscad constants shall be declared.
I have no problem to change it how ever you like it.
Note that I lowered the number of axis intentionally from 10 to 9.
The reason is, that the UI currently only supports axis 0..8.
Nine axis has also the benefit, that I can arrange them in the UI in a nice 3x3 grid
This pull request is kind of both a question and a preparation for further code.
(I need these constants for trim and deadzone correction. Will also increase the number of buttons at some point.)
=> use constants for array sizes in the inputdriver

src/input/HidApiInputDriver.cc
This allows the use of the axis mapping.
Note: This was tested with an SpaceExplorer which reports values between -350 and +350.
This is in conflict to the comment just above in the code:
> // Values are in the range -10..10 at min. speed and -2595..2595 at max. speed.
Maybe we need to split hidapi_decode_axis again for different mice reporting different ranges or the range is somehow OS dependent. Unfortunately, I can neither cross compile nor use a different mice.
=> hidapi_decode_axis1 using the InputEventAxis

src/GLView.cc
There was an issue that caused the labels to be closely bunched up at
small zoom levels. This was because the axis scale calculation wasn't quite right.
We adjust the scale whenever the viewport changes in
size by a factor of ten by doing:
scale_length = 10**truncate(log10(viewport_size))
truncate(0.99) and truncate(-0.99) and everything in-between map to
zero, giving us a range twice as large between scale changes. Using floor() instead of truncate() fixes the problem.
=> Fixed bad axis labeling at small zoom levels. #2020

examples/Parametric/candleStand.scad, examples/Parametric/sign.scad
Lenght -> Length
varaible -> variable
=> correct typos in parametric examples

src/parameter/parameterobject.cpp, src/parameter/parameterobject.h
How to reproduce:
* open OpenSCAD
* enable customizer
* enter
* vector0=[];
* press F5
The refactoring is not necessary for the fix, but it makes sense to do it as that was the reason why I found that bug.
=> BUGFIX: customizer crashes with empty vector, refractored checkVectorWidget() method

src/GLView.cc
Before:
After:
Note: my guess on why this was originally backwards was wrong - the axis indices before were correct. The problem was that the digit variable was scoped outside of the loop, so reversing it in one iteration would leave it that way for the next iteration (for positive numbers).
cc @thehans
=> Fixed backwards labeling on +z axis

src/parameter/ParameterEntryWidget.ui, src/parameter/parametervirtualwidget.cpp
see #2184
With this change, re-enabling HTML support requires changes just two properties in the UI file from "plaintext" to "richtext".
=> disable HTML support  in descriptions of the costumizer

src/OpenSCADApp.cc, src/OpenSCADApp.h, src/QSettingsCached.h, src/openscad.cc
This should resolve the  segmentation fault reported by bug #2182
=> Explicitly destroy QCachedSettings object when last window closed

scripts/travis-ci.sh
Better timing and folding of Travis CI logs
=> Better timing and folding of Travis CI logs

scripts/uni-build-dependencies.sh
mpfr.org is down today, causing the build script to fail.  Googling a bit this seems to be relatively common:
* [https://github.com/Homebrew/legacy-homebrew/issues/12371](https://github.com/Homebrew/legacy-homebrew/issues/12371)
* [https://sourceforge.net/p/mspgcc4/bugs/26/](https://sourceforge.net/p/mspgcc4/bugs/26/)
This pr changes the build script to look for mpfr source at the gnu.org mirror.
=> Using gnu.org mirror for mpfr

.travis.yml, scripts/macosx-build-homebrew.sh, scripts/travis-ci.sh
The macos build often fails due to exceedingt travis-ci's job time limit (50min).  This is an attempt to speed up those jobs somewhat and reduce the probability of timeout failures.
-Cached homebrew, this seems to reduce the homebrew step by roughly 2-3minutes.
-Also added some timing info to homebrew script for "debugging" build times
-Tweaked parallel job count for ctest.  -j4 performed faster than -j8 in my testing.  There are only 2 cores available to us anyways ( https://docs.travis-ci.com/user/reference/overview/ ), running too many threads might cause slowdown due to memory swapping or just
=> Travis macos build speed tweaks

src/LibraryInfo.cc
i do see no reason for the "#ifdef USE_SCINTILLA_EDITOR" in context of the InputDriverManager.
=> listDrivers() regardless whether SCINTILLA_EDITOR is used or not

src/AppleEvents.cc, src/FontCache.cc, src/GeometryUtils.cc, src/LibraryInfo.cc, src/OffscreenContextAll.hpp, src/OffscreenContextCGL.mm, src/OpenSCADApp.cc, src/PlatformUtils-mac.mm, src/UIUtils.h, src/cache.h, src/colormap.cc, src/func.cc, src/legacyeditor.cc, src/libsvg/libsvg.cc, src/libsvg/shape.cc, src/mainwin.cc, src/openscad.cc, src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/groupwidget.cpp, src/parameter/groupwidget.h, src/parameter/parameterset.cpp, src/parameter/parametervirtualwidget.h, src/scadlexer.cpp, src/stackcheck.cc
C++ Core Guidelines ES.47:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-nullptr
Note: These were found by clang-tidy (see #2239)
=> C++11: Use nullptr instead of 0 or NULL

src/input/AxisConfigWidget.cc, src/input/AxisConfigWidget.h, src/input/ButtonConfigWidget.cc
Having to first init and then update each QWidget, bloats the code and can lead to confusing issues further down the road.
Downside of that change is, that the UI-Code for the preference-input is now starting to differ from the methods of the same/similarly named in the preference.
(in Preferences.cc, the init is done by init() and the update by updateGUI() - both directly called in the method create(). Even-tough the name "updateGUI()" implies, that it could be called from other methods as well, that currently never happens.)
=> changed initComboBox and initDoubleSpinBox to directly set the value

src/input/DBusInputDriver.h, src/input/HidApiInputDriver.h, src/input/JoystickInputDriver.h, src/input/QGamepadInputDriver.h, src/input/SpaceNavInputDriver.h
see #2237 
This pull request is to keep the coding style of our feature branch in line with the main development branch in line.
Feel free to squash all the commits during merge.
=> inputdriver5 C++11: Use override to mark overridden virtual functions

openscad.pro, src/parameter/ParameterEntryWidget.ui, src/parameter/ignoreWheelWhenNotFocused.cpp, src/parameter/ignoreWheelWhenNotFocused.h, src/parameter/parametercombobox.cpp, src/parameter/parameterslider.cpp, src/parameter/parameterspinbox.cpp, src/parameter/parametervector.cpp
Changed from "wheelFocus" to "StrongFocus"
possible solutions for Issue #2185
related to #2252 
Please squash the commits during merge to not bloat the revision history with my unnecessary fine tuning commits.
=> Customizer: Ignore Mouse wheel when Widget is not focused

.gitmodules
This existing .gitmodules file uses a relative path, rather than a full URL.  When a user forks the openscad repo and tries to `git submodule update --init`, it tries to download from `git://github.com/<user>/MCAD.git` rather than the upstream MCAD library.
This is probably not desirable behavior, since most new OpenSCAD contributors won't have (or want) their own fork of MCAD.
=> Add full git URL for MCAD to .gitmodules

README.md
As discussed on #2257, this updates the MCAD link to the current canonical repo.
I have requested an account on the reprap wiki to update the link there as well.
=> update MCAD link in README - resolves #2257

c++11.pri, openscad.pro, src/EventFilter.h, src/OpenSCADApp.cc
I had three issues building OpenScad on my mac. 
The first issue related to the identification of using libc++ vs libstdc++. Boost was build with libc++ but the qmake profile was unable to identify it properly. 
I also had an issue where STACKSIZE was undefined for some reason. Added it to the DEFINES section in the qmake project and everything worked. 
Finally, clang was getting confused with EventFilter. It kept looking for a function as opposed to the class: 
```
src/OpenSCADApp.cc:16:31: error: cannot initialize a new value of type 'EventFilter' (aka 'bool (*)(void *, long *)') with an rvalue of type
'OpenSCADApp *'
this->installEventFilter(new EventFilter(this));
^           ~~~~
1 error generated.
```
Renaming the EventFilter class fixed this particular issue.
=> Mac High Sierra 10.13.2 build

openscad.pro, src/input/AxisConfigWidget.cc, src/input/ButtonConfigWidget.cc, src/input/WheelIgnorer.cc, src/input/WheelIgnorer.h
A lot of GUI elements in OpenSCAD are in Scroll Areas.
This causes a conflict, as some elements within the Scroll Areas are also reacting to the mousewheel.
Especially in the settings, where the user might spend a considerable amount of time to get it just right, it is annoying when simply scrowling down unintentionally changes various settings.
for reference:
* https://stackoverflow.com/questions/3241830/qt-how-to-disable-mouse-scrolling-of-qcombobox
* https://stackoverflow.com/questions/5821802/qspinbox-inside-a-qscrollarea-how-to-prevent-spin-box-from-stealing-focus-when
* http://doc.qt.io/archives/qt-4.8/qobject.html#installEventFilter
=> Inputdriver5 ignore mousewheel on the combo boxes

src/MainWindow.h, src/mainwin.cc, src/settings.cc
#2130 "add toggle version of actions for use with buttons, e.g. viewActionOrthogonal v's viewActionPerspective"
This approach does work, but I am not really happy with it.
This Action is breaking the structure of calling actions on the menu bar.
Adding an option to toggle to the menubar would be redundant there.
Adding the option "hidden" would be confusing.
So, this implementation is the best compromise I was I able to comeup with.
Not beeing in the menu bar also means, that it is not know to the InputDriverManager via registerActions();.
Now, the currently, "QStringList actions;" is unused, but that might change (or we should remove that list).
On the other hand: The list is usefull to check for the completeness of the preferences. (Which also could be automated in the test scripts)
We …
=> InputDriver5: Toggle Perspective

src/input/ButtonConfigWidget.cc
Currently, when we do not know a setting that is set in the preferences, we reset that setting to its default.
This will be an issue, when people start using different versions in parallel. Off course, an old version does not know the new actions, but it could at least "not touch" the users settings.
This is now implemented. To mark the not supported feature, a translatable string and an icon is used:
Discovered while working on #2254
Feel free to squash the commits.
=> Inputdriver5: do not overwrite the user settings with the default 

src/settings.cc
Using a for loop and snprintf has the following benefits:
- we can easily adjust the number of axis
- the translation is simpler (only two strings to translate instead of 18)
The variable names come from the QCombox, where we ultimately use this values.
http://doc.qt.io/qt-5/qcombobox.html#addItem-1
snprintf is part of c++11 http://www.cplusplus.com/reference/cstdio/snprintf/
ngettext (https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html) does not apply, as we are not dealing with plural, but an enumeration.
=> inputdriver5: create the "axisValues" using a for loop and snprintf

src/parameter/ignoreWheelWhenNotFocused.cpp, src/parameter/ignoreWheelWhenNotFocused.h, src/parameter/parametercombobox.cpp, src/parameter/parameterslider.cpp, src/parameter/parameterspinbox.cpp, src/parameter/parametervector.cpp
based on a comment(s) by kintel in #2252
> This object should probably receive a parent so it gets deleted at some point.
> On this note, you should be able to pass this to the WheelIgnorer contructor; that's the common way of assigning parents in Qt. Adding a constructor also makes it clear that this is how the object is supposed to be used (e.g. you could require an argument to be passed).
=> make the IgnoreWheelWhenNotFocused aware of its parent

src/input/AxisConfigWidget.cc, src/input/ButtonConfigWidget.cc, src/input/WheelIgnorer.cc, src/input/WheelIgnorer.h
based on a comment by kintel in #2252
> On this note, you should be able to pass this to the WheelIgnorer contructor; that's the common way of assigning parents in Qt. Adding a constructor also makes it clear that this is how the object is supposed to be used (e.g. you could require an argument to be passed).
=> more elegant way to make the WheelIgnorer aware of its parent

org.openscad.OpenSCAD.xml, src/input/DBusInputDriver.cc, src/input/DBusInputDriver.h
usage/example see https://github.com/MichaelPFrey/openscad-dbus-reference/pull/1
I am not to sure about the data type.
I could use array or QStringList, but QString maps to String which should be easy to use in any programming language. Using newline and splitting on it is also simple and easy.
=> inputdriver5, dbus: methode to get the name of supported actions

scripts/check-dependencies.sh, scripts/uni-get-dependencies.sh
In order to properly build OpenSCAD on Fedora 27 a couple of fixes
are required:
* Check for QT VERSION in arch-specific header files
* Install lizip-devel and ccache as build dependencies
=> Fix build on Fedora 27

src/nodedumper.cc, src/nodedumper.h
doesn't use any less memory, but runs recur(1000) in 4s instead of 8s
=> Optimize NodeDumper string building

src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/parameterset.cpp
* move the writeable check from "readParameterSet" to "readFile"
* This also fixes an issue with empty (0 bytes) json files: Empty json files cause an exception, causing readParameterSet to return false, without actually checking if the file would be writable.
* checking if the file exists, before trying to check for readability or writeabilty
*central setFile function with replace_extension instead of replace (closes #2307)
=> costumizer: improved file handling

locale/de.po, locale/openscad.pot, scripts/docker-build.sh, src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/mainwin.cc
When auto reload happens, the main window is raise()d to the front.
This is very useful with generating the .scad file from another application that
would cover most of the screen space. I use openscad together with inkscape
and inkscape likes to be in front most of the time...
An option is added to the Preferences advanced page to disable that new feature. 
I suggest to enable by default.
Also added scripts/docker-build.sh -- a quick wrapper to build on linux
bringing all prerequisites into a docker container to not pollute the build host.
Read and adjust the script before use, some things are hardcoded there.
It works with a git checkout outside the container, so that all object files and
the binary are easily accessible.
It shortcuts to the next needed step, but is quite slow doing so.
=> Feature addition: Option to raise the window upon auto-reload

src/FileModule.cc
path / path under windows causes boost to use backslash.
The file paths within openscad are normalized to normal slash.
Issue was discovered by  MichaelAtOz  while trying to test a new build for #2185
this fix was tested under windows 10 using https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Building_on_Microsoft_Windows for build instructions.
see also #2322
=> FileModule::getFullpath(): fixing issue under windows with backslash

src/parameter/parameterobject.cpp, src/parameter/parametertext.cpp
It would make sense tobe able to limit the string length, so I implemented just that:
test1 = "123"; //[3]
~~test2 = "1234"; //[0:4]~~
~~test3 = "12345"; //[0:1:5]~~
=> customizer: add support for text max. length

src/Preferences.cc, src/Preferences.h, src/mainwin.cc
This now uses the combo box index, so it needs to be in sync with the UI file.
=> Make editor type setting independent from translations.

org.openscad.OpenSCAD.xml, src/MainWindow.h, src/input/AxisConfigWidget.cc, src/input/AxisConfigWidget.h, src/input/AxisConfigWidget.ui, src/input/DBusInputDriver.cc, src/input/DBusInputDriver.h, src/input/InputDriver.h, src/input/InputEventMapper.cc, src/input/InputEventMapper.h, src/mainwin.cc, src/settings.cc, src/settings.h
this is building on #2280 (which are the first two commits in this pull request)
Naming it rotate2 is not ideal, but I am unable to come up with a better one.
The name rotate2 comes from the method of the same name that was unused in qglview.
Naming it relative rotate would be confusing with the relative flag of the normal rotate function.
On the other-hand: Rotate2 could be confused with RotateTo which is not ideal either.
=> inputdriver 5: expose rotate2 via dbus 

tests/export_import_pngtest.py, tests/test_cmdline_tool.py, tests/test_pretty_print.py
Also defined the charset as utf-8 in the generated HTML.
Added a flush to test_cmdline_tool sothat  output appears in the order it is printed.
=> Various fixes to the test scripts for Python3.

doc/testing.txt
The test scripts have been updated for Python3 and no longer work on Python2.
=> Specify Python3 as 2 no longer works.

src/comment_parser.y
The current comment parser tries and manages to parse things, it really shouldn't:
```
a=2; // [[1,2,3],[4,5,6],[9,5,4,2,3,1]]
echo(a);
d=4; // [[1,2,3]:a,50:d]
echo(d);
```
Looking into the details, due to the recursive nature, I can imagine that internally, the parse can generate a lot of interesting data-structures (which also makes unclear to a human reading the parser, what the parser is actually supposed to do).
The restructured code should be easier to read.
The simplification should also prevents/fixes various bugs, as the UI is not expecting the complex the data structures the current parser can generate.
refactored based on #2191
=> parser simplified

scripts/macosx-build-dependencies.sh
a few tweaks so high Sierra build works, but untested on Sierra / el capitan
qt 5.11.1 is required because of a lot of new C++ stuff... maybe there is a way to force build with different C++ standard but it seemed easier to just bump version a few notches
the other thing I'm not sure about is the HarfBuzz... when building with autogen it required ragel and pkg-config which I did not want to install, so I tried instead to download the release version of HarfBuzz, which comes with 'configure' script already built... and I ran that while disabling gtk-doc-html and it seemed to work, but I'm not sure if that will work for other OSX
=> osx high Sierra  fixes

src/parameter/ParameterWidget.cc, src/parameter/parameterextractor.cpp
there are for different possible implementation for hidden variables:
1. hidden variables are stored and retrieved from the json file
1. hidden variables **NOT stored** in json file, but are retrieved from the json file
1.  hidden variables are stored in the json file, but are **NOT retrieved** from the json file
1. hidden variables are **neither** stored and  nor retrieved from the json file
Originally, the OpenSCAD customizer has behaved as in 1.
Currently, the OpenSCAD customizer behaves as in 2. The customizer applying variables from the hidden group when found in a json file does not make sense.
Implementing 3 would be a reasonable compromise. Hidden variables are not applied, but still stored. Meaning: If a once hidden variable becomes visible, it also becomes applicable. This …
=> save hidden variables, but to not apply them (see #2450)

src/mainwin.cc, src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/ParameterWidget.ui
* adding a "design default values" parameter set. 
* Always reset to the "design default values" before applying any preset.
-> this should prevent various issues like variables from one parameter set being transferred to an other parameter set that those not have the specific parameter has not set.
=> adding a "design default values" parameter set

src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/parameterset.cpp, src/parameter/parameterset.h
This handles the case, where a "new" parameter set has the same name as an existing one.
=> customizer: check if a parameter set name already exists and ask before overwritting 

doc/translation.txt, locale/cs.po, locale/de.po, locale/es.po, locale/fr.po, locale/openscad.pot, locale/pl.po, locale/ru.po, scripts/translation-update.sh, src/Preferences.ui
for issue  #2431 
side notes:
* clarify, that CONFIG+=experimental should be used when updating the translation files (relates to #2316)
* update the translation
* adding translation context
* adding `-keyword=_:1,2c` to `xgettext` `OPTS`
* `<string comment="preferences">Advanced</string>`
=> Translation context

src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/ParameterWidget.ui
make the comboBoxPreset editable
* if the set name is changed to "" asks if the user want to delete the current preset
* if the set name is changed and  no  values are changed, rename the current preset
* if the set name is changed and some values are changed, create a new set
The ability to directly rename the parameter set is new.
Adding and removing sets is redundant to the + and - buttons.
As the name is now editable, I had to move the change indicator "*" into its very own label.
Interestingly, when the user enters a name of a preset that already exists, QT does automatically changes to it. That might need some testing and tweaking.
=> make the comboBoxPreset editable

src/ModuleCache.cc, src/lexer.l, src/mainwin.cc, src/openscad.cc, src/parser.y, tests/regression/echotest/scope-assignment-tests-expected.echo, tests/regression/echotest/search-tests-expected.echo, tests/regression/echotest/value-reassignment-tests-expected.echo, tests/regression/echotest/value-reassignment-tests2-expected.echo
addressing #2439 #1770.
This still allows the root module to overwrite variables from includes without warning (which is an indented feature) and includes to overwrite variables from the root module without warning (which we can discuss).
It also avoids warnings from issues within used and inlcuded files.
The command line option `-D ` is an issue with that approach.
In the ModulCache, the command line is simply appended to the rootmodule:
`		textbuf << "\n" << commandline_commands;`
making the patch fail `openscad-override_override`. I mean I could regenerate the test, but the warning is not really acceptable:
`+WARNING: a was assigned on line 2 but was overwritten on line 6` as the scad file has only 5 lines. the 6th line are the appended `commandline_commands`.
=> warn, when a variable from the root module is overwriten in the root module

doc/testing.txt, src/FileModule.cc, src/parser.y, testdata/scad/misc/include-overwrite-after.scad, testdata/scad/misc/include-overwrite-before.scad, testdata/scad/misc/include-overwrite-main.scad, tests/CMakeLists.txt, tests/regression/astdumptest/include-overwrite-main-expected.ast, tests/regression/dumptest/include-overwrite-main-expected.csg, tests/regression/echotest/include-overwrite-main-expected.echo
I used the uncomplete code as used by assert, so I added an "assert(false);" into my test files.
=> warn, when an assigment from the RootModule overwritten by an include

src/openscad.cc
The command line help message is now programmatically generated from the  boost::options_description. The descriptions have been tidied up and extended to show the experimental features available and the color schemes available with the default marked by a star.
Unrecognised options give an error again, reversing @kintel's commit https://github.com/openscad/openscad/commit/752f35eab6c7b20d188bc36836e622665c8eba42. This assumes #2107 makes it no longer necessary.
This is an example of the error handling:
```
$ ./release/openscad.exe -fred
unrecognised option '-fred'
Usage: openscad.exe [options] file.scad
-o [ --o ] arg        output specified file instead of running the GUI, the
file extension specifies the type: stl, off, amf, csg,
dxf, svg, png, echo, ast, term, nef3, nefdbg
-D [ --D ] …
```
=> Boost options_description now used to generate command line help.

src/boost-utils.cc, src/boost-utils.h
The function is unused for years. Mid therm, we will use/maintain `boostfs_uncomplete` until we can replace that with c++17 or boost 1.60.0 `lexically_relative`.
=> remove the unused boostfs_relative_path function

.travis.yml, scripts/travis-ci.sh
Tests are failing again on `xenial` with
```
Unable to open a connection to the X server.
DISPLAY=:1063
Can't create OpenGL OffscreenView. Code: -1.
```
So I think we need to revert to `-j1` as we did for `trusty`. This does not seem to have much impact on runtime anyway. In this instance with one test failing with `-j4` on `xenial` the runtime was ~13min for both.
This also moves the setting to travis.yml so we don't have to switch again in the travis run script based on other env variables.
=> Move PARALLEL_CTEST setting to travis.yml

appveyor.yml
There's too much stuff pre-installed in C:\msys64 so cache is not working or potentially even killing a good build due to timeout.
```
Updating build cache...
Cache 'C:\msys64' - Zipping...Unable to save cache - skipping
Compressed cache item cannot exceed 1,048,576,000 bytes.
```
=> Remove cache setting

src/FileModule.cc, src/UserModule.cc, src/boost-utils.cc, src/exceptions.h, src/expr.cc, src/function.cc, testdata/scad/misc/recursion-test-function3.scad, testdata/scad/misc/recursion-test-function4.scad, tests/CMakeLists.txt, tests/regression/echotest/assert-expression-fail1-test-expected.echo, tests/regression/echotest/assert-expression-fail2-test-expected.echo, tests/regression/echotest/assert-expression-fail3-test-expected.echo, tests/regression/echotest/assert-fail1-test-expected.echo, tests/regression/echotest/assert-fail2-test-expected.echo, tests/regression/echotest/assert-fail3-test-expected.echo, tests/regression/echotest/include-overwrite-main-expected.echo, tests/regression/echotest/recursion-test-function-expected.echo, tests/regression/echotest/recursion-test-function2-expected.echo, tests/regression/echotest/recursion-test-function3-expected.echo, tests/regression/echotest/recursion-test-function4-expected.echo, tests/regression/echotest/recursion-test-module-expected.echo, tests/regression/echotest/recursion-test-vector-expected.echo
For tracing a recursion, a call stack would be best, but this is (currently) out of reach.
So, let us see if something lower hanging could be potentially be useful.
=> Better error message for Recursion Exception

src/MainWindow.h, src/MainWindow.ui, src/mainwin.cc
A blank line is printed instead to separate each compilation.
The console clearing was not consistent because it depended on whether the main file changed or just its dependencies. It also cleared duplicate assignment warnings and the start up messages prematurely.
=> No longer clears the console.

src/input/InputDriverManager.cc
Constructor will be called also from non-GUI context from library info,
e.g. when calling "openscad --info".
=> Move timer and signal initialization to init().

README.md
Badges in OpenSCAD color scheme. Unfortunately the name color seems to be fixed to white.
Preview via branch: https://github.com/openscad/openscad/tree/shield-io-badges
=> Changing to shield.io badges (in README.md).

src/control.cc, src/expr.cc, tests/regression/echotest/for-tests-expected.echo, tests/regression/echotest/range-tests-expected.echo, tests/regression/echotest/special-consts-expected.echo
going back to #1843
This PR shows in the test case one of the side effecs of adding the line number and other context information: The warnings are now unique, so they are not considered repeats anymore.
=> add the line number to the bad range warning

src/context.cc
this is based on #2640
I do not understand what
` s << boost::format("Context: %p (%p)") % this % this->parent; `
is supposed to do. Currently, it does something like
`Context: 0x7ffc9a68bad0 (0)`
as the parent of the top_ctx is off course a `nullptr`, which is kind of messy.
=> Context::dump debug

src/func.cc, testdata/scad/misc/search-tests.scad, tests/regression/echotest/search-tests-expected.echo
One example why we need `->toEchoString()`:
```
data=[ ["a",1],123 ];
echo(search("a", data, num_returns_per_match=0)); 
```
```
Compiling design (CSG Tree generation)...
WARNING: Invalid entry in search vector at index 1, required number of values in the entry: 1. Invalid entry: 0x557571988eb0, line 3
ECHO: []
```
And off-course I added a test case to prevent regression.
=> testing and debugging the search warnings

src/mainwin.cc, src/parser.y, src/printutils.cc, tests/regression/echotest/include-overwrite-main-expected.echo, tests/regression/echotest/scope-assignment-tests-expected.echo, tests/regression/echotest/search-tests-expected.echo, tests/regression/echotest/value-reassignment-tests-expected.echo, tests/regression/echotest/value-reassignment-tests2-expected.echo
hardwarning does not work within the parser, causing openscad to be unable to properly reparse the scad text even after fixing the error.
=> hardwarning debug

Info.plist, Info.plist.in
This should fix #2277. In the existing code, an attempt was made to allow insecure access, however some tags were missing.
This is the reference I used: https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http/32560433#32560433
I wasn't able to test it since I'm not able to successfully set up the build environment on macOS 10.14.2. Manually copying the new Info.plist into the App bundle leads to a successful http request, though.
Finally - as noted in the stackoverflow thread - this should be a short-term fix and long-term enabling https would be preferred.
=> Fixed Info.plist to allow http request for update check

src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/QGLView.cc, src/QGLView.h, src/mainwin.cc, src/settings.cc, src/settings.h
* http://forum.openscad.org/Turn-on-off-cursor-centered-mouse-wheel-zoom-td25184.html
* #1857
* #2611
Maybe it is not a good idea to potentially read the settings multiple times per second.
I personally prefer mouse centric zoom, but I have other issues with the 3D view, so this option is not in my interest, but adding options in general is in my interest.
=> option to disable mouse centric zoom

src/OctoPrint.cc, src/mainwin.cc
More useful error message if no URL is configured.
=> Check for empty URL in OctoPrint settings.

src/func.cc, testdata/scad/misc/islist-test.scad, tests/CMakeLists.txt, tests/regression/echotest/islist-test-expected.echo
partially addressing #1584, but mainly addressing the mailing list thread "A warning too far?":
> WARNING: length() parameter could not be converted, in file global.scad, line 104
> v = is_undef(len(d)) ? [0, 0, d] : d;
> I think this is the standard OpenSCAD idiom to test if a parameter is a vector or a scalar. Is there any other way to do it?
> I think it is sufficient that taking the length of a scalar gives undef and using undef other than in is_undef() gives a warning, so you can't do it accidentally.
=> add is_list builtin

openscad.pro
For #2771 
I made a commit already that fixed MXE warnings, trying to take care of MSYS2 warnings also.
=> Change gcc CFLAGS to ignore bugged warnings on MXE *and* MSYS2.

CMakeLists.txt, openscad.pro, src/CGALCache.cc, src/GeometryCache.cc, src/Tree.cc, src/Tree.h, src/cache.h, src/nodedumper.cc, src/nodedumper.h
Note: I had a PR already for this, from my master, but recreated it on its own branch now.  I rebased my fork's master(force push) to match openscad which auto-closed the previous PR #2766 since it has no changes now.
This change reduces duplicate cache entries which can be caused by empty or single child groups.
I also changed idPrefix setting to be a preprocessor define, and reverted the cache debug PRINTB/PRINTDB statements to their previous 40character limit.
Here is some sample code
```
module expensive(test, $fn=40) {
if (test) 
echo(test);
difference()  {
sphere(10);
translate([5,0,0]) sphere(10);
}
}
module test2() {
expensive();
}
expensive();
expensive("hi");
test2();
if(1) test2();
```
Before
```CGAL Cache insert: difference(){sphere($fn=40,$fa=12,$fs=2,r=10);multmatrix([[1,0,0, …
```
=> Optimize away group nodes with <=1 children from node idStrings

src/openscad.cc, src/printutils.h
The default colourscheme marker was shown on every scheme.
Also fix for libintl.h snprintf clash with boost.
=> Fixed regression when colorscheme usage message was converted to inline join.

src/input/AxisConfigWidget.cc
to prevent getting operating specific animated progressbars, addressing https://github.com/openscad/openscad/issues/2786#issuecomment-465025853
implementation roughly based on
- https://stackoverflow.com/questions/15009132/qt-qprogressbar-aligning-text
- https://stackoverflow.com/questions/9368824/change-the-color-of-a-qprogressbar
=> use a custom style for the axis indicators

releases/2019.02.md, src/localscope.h, src/primitives.cc, testdata/scad/misc/errors-warnings.scad, tests/regression/echotest/errors-warnings-expected.echo, tests/regression/echotest/errors-warnings-included-expected.echo
fixes #2804, partially adresses #596 
Todo:
- add test case
- update changelog
- ...
In scope of this PR:
- builtin modules
Not in scope of this PR:
- user modules
=> warning, when a builtin module without support for it has children

src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/input/HidApiInputDriver.cc, src/input/HidApiInputDriver.h, src/settings.cc, src/settings.h
So we could not get the Universal Receiver to work yet, but the tracing code is updated to be mergable and has a Preferences setting to enable/disable.
Logging goes to `${BACKUP_DIR}/hidapi.log` and is limited to max file size of 20k.
Lets merge this and maybe get additional feedback. Also it hopefully helps to get the SpaceMouse Compact running on MacOS (#2810).
=> Add the 3Dconnexion Universal Receiver USB id

src/Preferences.cc, src/input/AxisConfigWidget.cc, src/input/AxisConfigWidget.h, src/input/ButtonConfigWidget.cc, src/input/ButtonConfigWidget.h, src/input/HidApiInputDriver.h, src/input/InputDriver.h, src/input/InputDriverManager.cc, src/input/InputDriverManager.h, src/input/JoystickInputDriver.h, src/input/QGamepadInputDriver.h, src/input/SpaceNavInputDriver.h
XBox 360 Controller has 8 axis, meaning axis 0 to 7 are active and 8 is grayed out:
XBox 360 Controller has 11 buttons, meaning buttons 0 to 10 are active and 11 to 15 are grayed out:
I will do a double check on Windows with QGamepad. In QGamepad, the D-Pad is consider 4 more buttons, but that means two axis less.
=> Inputdriver UI: grayout irrelevant UI elements

src/FileModule.cc, src/FileModule.h, src/ModuleCache.cc, src/ModuleCache.h, src/StatCache.cc, src/lexer.l, src/mainwin.cc
Massive speed up in handleDepedencies by only checking each module once.
Fixed StatCache timeout being 1000 times too small since using chrono.
Made module cache paths generic to avoid mixed slashes on Windows.
Stopped double compilation when file is first loaded by initialising the includes time.
Made console buffer 10 times bigger.
=> Speed up handle dependencies

tests/export_import_pngtest.py, tests/test_cmdline_tool.py
This helps fix a few test failures in Debian packaging, where the
testsuite is run out-of-tree, and where we would otherwise fail to
pick up the correct font file.
=> Use an absolute path for OPENSCAD_FONT_PATH in the testsuite

CMakeLists.txt
Modification to CMakeList.txt file to instruct link command to include system double conversion library
=> modify CMakeList to ensure linking against double-conversion library

src/parser.y
Ensure that mainFilePath is an absolute path during parsing.
The logic for generating warnings about double assignment generally
seems to assume relative paths, and in fact mainFilePath is made
absolute in the recursive parse() call for a use <...> statement. So
if mainFilePath is not absolute from the start the code gets confused.
=> Fix missing warning about double assignment

src/parser.y, src/parsersettings.cc
Prevents error messages with mixed slashes on Windows.
Boost seems to think file separators should be \ in Windows, which is a pain. I don't know anywhere where they need to backslash inside a C program.
=> Remove backslashes in paths on Windows earlier.

src/ModuleInstantiation.cc, src/ModuleInstantiation.h, src/localscope.cc, src/localscope.h, testdata/scad/misc/ifelse-ast-dump.scad, tests/CMakeLists.txt, tests/regression/astdumptest/ifelse-ast-dump-expected.ast, tests/regression/astdumptest/include-tests-expected.ast, tests/test_cmdline_tool.py
Also don't strip leading/trailing whitespace in test output so we can monitor any future changes.
I've looking at the code related to AST and testing the AST dump feature to see how it all works.  I noticed that any inlined/chained module was clearing the indentation, which bugged me so I fixed it.
The only other issue I can see with AST dump, not currently addressed, is that "use"d libraries are not placed in the dump, meaning the result is not re-compilable.
=> Fix AST dump indentation to not lose track after "inlining" a ModuleInstantiation.

src/openscad.cc
Fix for issue #2877 
Previous commits at PR #2887 
The --export-format option will overwrite the file extension provided in -o option. If no -o option is given with --export-format option, --export-format is ignored
=> Added --export-format option to command line

src/import.cc, testdata/scad/templates/import_dxf-tests-template.scad, tests/regression/dumptest/import_dxf-tests-expected.csg
The bug was caused by passing 0 to the PolySet constructor when the file type is unknown. That gave a zero dimension object. The rendering code assumes it will be 2 or 3.
The simplest test is just
```import();```
F5 and then F6.
=> Fixes #2784.

scripts/mingw-x-build-dependencies.sh
Fixed git url to clone mxe repo: using git:// protocol does not always work.
Might be a firewall issue but on one machine I got 
$ git clone git://github.com/openscad/mxe.git
Cloning into 'mxe'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection timed out
github.com[1: 192.30.253.113]: errno=Connection timed out
whereas I have no issue with https
=> Fixed git mxe url

src/scintillaeditor.cpp
As noted in [#2885](https://github.com/openscad/openscad/issues/2885),
Option+Arrow keys don't work in OpenSCAD on OS X anymore.  This updates
OpenSCAD so that Alt+Shift (AKA Option+Shift) is the modifier to use
the number precision extension that is bound to Alt+Left and Alt+Right
on other OSes.
=> Restore Option+Arrow behavior on Mac.

src/CSGTreeNormalizer.cc
I ended up ditching my original iterative solution since it was really too complex to try to understand and maintain.  This new one is still iterative and manages its own stack but I think its much clearer and deviates minimally from the original recursive implementation.
=> Rewrite iterative CSGTreeNormalizer::normalizePass to be comprehendible and correct.

src/surface.cc
This commit Fixes issue no #2278. To solve this issue, we are checking the return value returned by the lodepng_filesize() function (from /ext/lodepng/lodepng.cpp file) which is been called from the load_file() function(from the surface.cc file), the load_file() function (is from ext/lodepng/lodepng.cpp file) .The function lodepng_filesize return a  -1   when the file to be open is not found or when the file to open is too big.
This solves the issue that the a file which was not exits was identified as a dat file, now instead a warning message is been shown which informs that the file doesn't exits or its to big to open.
=> Fixes#2278 Surface errors should reflect the file type

contrib/scad-mode.el
This adds a basic "completion at point" function (`capf`) for builtin keywords, functions and modules in `scad-mode.el` (Emacs), directly usable with Emacs autocompletion packages (e.g. `company-mode`), as an alternative to `dabbrev`-based completion.
=> Add basic completion-at-point function for Emacs OpenSCAD mode.

src/primitives.cc
This PR removes a few instances of new/delete pairs with equivalent usages of std::vector. This makes the code base a little more modern, although it has no effect on performance or correctness.
=> Replace new/delete with std::vector

src/MainWindow.h, src/mainwin.cc
Fix for issue #2871 
Added the functionality such that detached console window can lie behind the main window.
=> Main Window on top of detached console window 

tests/CMakeLists.txt
This fixes failures in these tests for Debian packaging, where the
tests are run out-of-tree.
It also seems to match what other tests do, for example spec-paths-arcs01.scad:
import("../../../svg/svg-spec/spec-paths-arcs01.svg");
So might be worth it to include upstream as well.
=> Use a relative import() path for svg viewbox tests

scripts/check-dependencies.sh
It looks like #2961 fixed a whole bunch of spelling and punctuation mistakes, but in changing `doesnt` to `doesn't` in `scripts/check-dependencies.sh` it left an unmatched single quote in the script. In case anyone else is searching for this error, the output I got was:
```
./scripts/check-dependencies.sh: line 304: syntax error near unexpected token `)'
./scripts/check-dependencies.sh: line 304: `  bison_sver=`echo $bison_sver | awk -F ")" ' { print $2 } '`'
```
Double-quoting the whole argument to `debug` fixes it for me.
=> Fix typo in scripts/check-dependencies.sh

src/mainwin.cc
Ampersand has special meaning for QAction. It can be escaped by double ampersand.
=> Fix for issue #2988

src/mainwin.cc
=> Corrected interpretation of '&' in title bar of undocked widget

src/linearextrude.cc
Casting inf/nan to int is undefined behaviour. In practice the
behaviour differs between linux x86, arm, and mips, causing a failure
in the test liniear_extrude-parameter-tests on non-x86 platforms.
This patch adds an explicit test for non-finite double value to make
the behavior consistent between platforms.
Fixes #3015
=> Avoid undefined behavior for `convexity' parameter to linear_extrude

src/context.cc, src/context.h, src/evalcontext.cc, src/modcontext.cc
While working on another PR to improve tail recursion, I noticed that creating a Context can be faster; the document_path member was always copied.
This wraps it in a shared_ptr. The speedup is about 10% to 15% when doing lots of Context creation.
=> Use shared_ptr for Context::document_path

src/OffscreenContextGLX.cc, tests/CMakeLists.txt
So this isn't pretty, but it does provide a possible solution to an annoying problem. With this patch I am able to consistently run the openscad testsuite with -j8 without failures. Whereas without this I'll see random failures every 2-3 test run or something like that.
----
When running the testsuite against an Xvfb $DISPLAY with -jN, there
are occasional failures with "Unable to open a connection to the X
server". This appears to be a bug in Xvfb with rapid parallel connects.
This patch implements a work-around: The testsuite sets the
environment variable OPENSCAD_X_CONN_RETRY; this causes openscad to
retry the X connection in case of failure, which avoids the test
failure.
=> Work-around for test failure at high -jN

src/mainwin.cc, src/scintillaeditor.cpp
The dock settings and autocomplete settings were not properly initialized when config file of OpenSCAD was removed. This bug emerged due to blocking of signal in updateGUI() of Preferences.cc
=> Corrected reading of Preference settings

src/openscad.cc
The --export-format option did not actually work for me; with this fix it does.
Also made some localized whitespace consistency fixes (in separate commit).
=> Fix dangling pointer in "--export-format"

tests/CMakeLists.txt, tests/virtualfb.sh
Tests fail occasionally at high -jN with a failure to connect to the X
server on Xvfb. By default, the X server resets itself when all
clients disconnect, and this leaves a window where new connects can
fail during the reset. This can be avoided by passing the -noreset
flag to the X server.
This replaces the previous https://github.com/openscad/openscad/pull/3024
patch to solve the same problem.
=> Better fix for test failures at high -jN

tests/CMakeLists.txt
The llvmpipe software-renderer of Mesa seems not stable on the MIPS
architecture. There are numerous crashes in the test suite when using
llvmpipe, as seen in the Debian build farm.
This patch implements the similar work-around that already exists for
PowerPC, to use the softpipe renderer (which was significantly faster
than llvmpipe anyway on MIPS in my tests).
=> Work-around for test failures on mips

src/openscad.cc
Not sure what the expected behavior should be, but to me the current behavior seems strange.
Running:
```openscad input.scad --export-format stl -o /dev/null```
tries to write a STL file to ```/dev/null.stl```.
With this change, the filename given by "-o" is respected; probably the user knows what they are doing.
Side effect is that extension is no longer lower-cased now:
```openscad input.scad -o output.STL```
now produces ```output.STL``` instead of ```output.stl```.
=> Don't replace extension of output file

src/MainWindow.ui, src/editor.h, src/legacyeditor.cc, src/legacyeditor.h, src/mainwin.cc, src/scintillaeditor.cpp, src/scintillaeditor.h, src/tabmanager.cc, src/tabmanager.h
Scintilla/scite has a very useful "bookmarks" feature - allowing a user to
bookmark any line in the code with CTRL-F2,
then jump around between the bookmarks with F2 (next) and SHIFT-F2 (backwards).
This is very helpful when dealing with large code base, jumping from/to specific points.
In the screenshot below, two bookmarks are set at lines 3 and 11.
The cursor is at line 8. Pressing F2 will jump to line 11. Pressing SHIFT-F2 will jump to line 3.
The jumps "wrap around" so pressing F2 endlessly will cycle through all bookmarks.
CTRL-F2 on an existing bookmarks removes the bookmark ( toggle ).
The white bookmark icon isn't great (hides the line number), but it can be changed.
This PR is broken into very small patches, one per topic, to ease review.
Comments and suggestions very welcomed. …
=> GUI: add Scintilla "bookmarks" feature

src/scintillaeditor.cpp, src/scintillaeditor.h
Update handling of margins.
- Separate line number and symbol margins
- Minimize line number margin
- Hide symbol margin (showing errors and bookmarks) if no markers are active
- Add color scheme support for bookmarks
=> Update handling of margins.

src/MainWindow.ui, src/editor.h, src/legacyeditor.cc, src/legacyeditor.h, src/scintillaeditor.cpp, src/scintillaeditor.h, src/tabmanager.cc, src/tabmanager.h
This makes debugging easier: if the source code has an error, a quick keypress jumps to it.
The weird keyboard shortcut (CTRL-ALT-E) is just a suggestions, happy to change it.
(also: this PR conflicts with my other one(#3059), if one is accepted, I'll amend the other accordingly.
=> GUI: Jump to errors

src/context.cc, src/context.h, src/expr.cc, src/expression.h, src/function.cc, src/function.h, src/parser.y, testdata/scad/misc/function-scope.scad, testdata/scad/misc/tail-recursion-tests.scad, tests/CMakeLists.txt, tests/regression/echotest/function-scope-expected.echo, tests/regression/echotest/recursion-test-function-expected.echo, tests/regression/echotest/recursion-test-function2-expected.echo, tests/regression/echotest/tail-recursion-tests-expected.echo
This re-implements tail recursion of functions; now any self-call in tail position gets to enjoy tail recursion, instead of functions that follow a very specific structure. In particular, let/assert/echo and nested ternary operators can be used freely now.
Unlike at parse time as before, now the decision to use tail recursion is made at run-time, and for each function call instead of each function declaration.
Tried to separate it in a few commits. Here's a summary of changes:
- Remove FunctionTailRecursion and its factory method
- For a few Expression subclasses, factor out method ```evaluateStep``` from ```evaluate```. It returns the following Expression, instead of evaluating it.
- Use a nested while-loop for function evaluation; the inner loop iteratively follows a single execution …
=> Generic tail recursion

src/mainwin.cc
The reload confirmation dialog box counter-intuitively turns off automatic reload on choosing No option. The pr removes this behavior and No option simply does not reload the file.
=> Update working of No option in reload

src/scintillaeditor.cpp, src/scintillaeditor.h
This adds line/block copy&move.
Keys are for now, we probably want to look at handling via actions, but for now it's following the implementation of the number handling:
- Copy: SHIFT + CTRL + Cursor UP/DOWN
- Move: ALTGR + CTRL + Cursor UP/DOWN
=> Block copy and move

.circleci/config.yml, scripts/macosx-build-dependencies.sh
@t-paul This should perhaps make the CI build for macOS more robust. Still doesn't manage dependencies though.
Update: As the  rabbit hole always goes a bit deeper than we think, this took some more time, but it looks good now.
TODO:
=> macOS: Rewrote version checks to explicitly write the built version to file

snap/snapcraft.yaml
Update snap build:
- Add 'audio-playback' interface which will replace deprecated 'pulseaudio'
- Disable Wayland as that causes crashes, e.g. on Debian testing
=> Snap updates

src/scintillaeditor.cpp
Text position of the underlying buffer in Scintilla is byte based, not character based. Searching via utf8 encoded QByteArray should take care of most cases.
=> Fix search highlight with multi-byte utf8 characters (fixes #3068).

src/parser.y
Regressed by boostorg/filesystem@9a14c37d6f95. See [error log](https://github.com/openscad/openscad/files/3772674/openscad-2019.05.10_3.log).
=> Unbreak build with Boost 1.72

src/lexer.l
This is needed because yyerror() is using lexerget_lineno() and not the location object.
=> Update yylineno on include<> to track error line numbers.

cgal/decompose.cpp, cgal/export_nef.cpp, src/CGAL_Nef_polyhedron.cc, src/CGAL_Nef_polyhedron.h, src/Geometry.h, src/GeometryEvaluator.cc, src/Polygon2d.h, src/cgalutils-applyops.cc, src/cgalutils.h, src/import_3mf.cc, src/import_amf.cc, src/mainwin.cc, src/polyset.h, src/progress.cc, src/progress.h
This change uses a priority_queue (min heap) sorted by number of face(t)s in each geometry.  So the two least complex objects are always merged first.  Temporary results go back into the priority queue so it adapts as complexity changes.  The queue is also secondarily sorted by `node.progress_mark` when complexity matches, which should act as a stable sort.  
Reasoning for keeping the sort stable is based on the assumption/heuristic that consecutive sibling nodes are likely to be close to each other in space, which is more likely to cause reduction in complexity for example in a loop of identical translated objects.
Also change to progress bar update during union.
For issue #1234
=> Change CGAL Union to join least complex geometries first.

src/expr.cc, src/value.cc, src/value.h, tests/regression/echotest/children-tests-expected.echo, tests/regression/echotest/concat-tests-expected.echo, tests/regression/echotest/errors-warnings-included-expected.echo, tests/regression/echotest/for-tests-expected.echo, tests/regression/echotest/list-comprehensions-expected.echo, tests/regression/echotest/range-tests-expected.echo
based on http://forum.openscad.org/Infamous-warnings-td28054.html
- (just focusing on literals for now)
- Warn for
- correct (do not warn)
- not addressed with this PR
-  expression containing variables like `for(i=[0:a])` `for(i=[a:0])` `for(i=[0:a:10])`  `for(i=[a:1:10])`  `for(i=[0:1:a])` 
- non-numbers like
- for(r=[1:true:5]) echo(r);
- for(r=[1:"test":5]) echo(r);
- for(r=["a":"z"]) echo(r);
=> Range Warnings begin<end

scripts/macosx-build-homebrew.sh
This fixes Travis macos builds which broke recently due to conflicts between Python 2 & 3.  
Likely caused by some change (in homebrew?) related to Python 2 reached End Of Life on 1/1/2020.
=> Travis macos fix

src/expr.cc, testdata/scad/issues/issue3118-recur-limit.scad, tests/CMakeLists.txt, tests/regression/echotest/issue3118-recur-limit-expected.echo
This small change addresses the issue defaultArguments growing without bounds when a call has no arguments, which was causing recursion limit to not be reached in any reasonable time frame.
=> Minimal fix for #3118  Tail recursion limit not working

src/FileModule.cc, src/FileModule.h, testdata/use-order-test/file1.scad, testdata/use-order-test/file2.scad, testdata/use-order-test/file3.scad, testdata/use-order-test/file4.scad, testdata/use-order-test/use-order-test.scad, tests/CMakeLists.txt, tests/regression/echotest/use-order-test-expected.echo
Searches for module and functions in used files are now in reverse order of use. This ensures later uses override earlier ones when they define the same name.
=> Use search order fix

src/scintillaeditor.cpp
Fixed issue #3155 
When you don't select an autocomplete suggestion and press '(', then the first suggestion is selected for auto-completion.
This PR fixes this intrusive behaviour.
=> fix intrusive autocomplete

src/Preferences.cc
This commit disables the 'Indent' spin-box when 'Indented' option is chosen from 'Line Wrap Indentation Style'.
The purpose of doing this is explained in issue #2670  (for future contributors)
=> disable indent-spinbox in IndentLineWrap style

src/scintillaeditor.cpp, src/scintillaeditor.h
Add shortcuts for:
- Autocomplete: CTRL + Space (pretty much the default for IDEs)
- Calltips: SHIFT + CTRL + Space (function parameters)
=> Shortcuts for autocomplete

src/GeometryEvaluator.cc
I think the condition `if (this->x > 0 && this->y > 0 && this->z > 0 && !std::isinf(this->x) && !std::isinf(this->y) && !std::isinf(this->z))`  in PrimitiveNode::createGeometry() method creates an empty nef_polyhedron. and the application crashes when CGAL_forall_halffacets method in createPolySetFromNefPolyhedron3 tries to access that empty nef_polyhedron. issue #3229
=> fix to issue #3229 

src/parameter/parametervector.cpp, src/parameter/parametervirtualwidget.cpp, src/parameter/parametervirtualwidget.h
I have tried to do a quick fix for #3243 
Two approaches came into my mind-
1) To look over the highest precision by dividing the value by 10.0 and keeping the count until the value becomes 0.0
2) Converting the value into the string and using string manipulation (I found this approach on the internet), while I was searching for some inbuilt C++ function to do the same.
As, toDouble() already truncates(roundoff) the doubles to 5 decimal places, so both the approaches will take nearly constant time.
I chose the second approach, as working with doubles/floats is always tricky.
=> fix customizer vectors highest precision bug

c++std.pri, scripts/macosx-build-homebrew.sh
* Update boost to fix dependency on icu4c.
```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicudata.64.dylib
Referenced from: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
Reason: image not found
```
* Use c++14 config from Qt instead of directly adding compiler option.
=> Fix MacOS build

src/FileModule.cc, src/GroupModule.cc, src/UserModule.cc, src/cgaladv.cc, src/cgaladvnode.h, src/color.cc, src/colornode.h, src/control.cc, src/csgops.cc, src/csgops.h, src/import.cc, src/importnode.h, src/linearextrude.cc, src/linearextrudenode.h, src/node.cc, src/node.h, src/offset.cc, src/offsetnode.h, src/primitives.cc, src/projection.cc, src/projectionnode.h, src/render.cc, src/rendernode.h, src/rotateextrude.cc, src/rotateextrudenode.h, src/surface.cc, src/text.cc, src/textnode.h, src/transform.cc, src/transformnode.h
Added `const std::shared_ptr<EvalContext> &ctx` as the current evaluation context to all constructors of `AbstractNode` and store the declaration location in the node.
This will improve the #3276 mouse selector (AbstractNode is cleaner to resolve than CSGNode!) and other synatx referencing features like #3283
=> AbstractNode: location

src/export.cc, src/export.h, src/export_3mf.cc, tests/regression/3mfexport/3mf-export-expected.3mf
This also converts the export to use the same strategy as STL which makes
it possible to export non-manifold geometry (with warning).
Vertices and Triangles are sorted so output should be reproducible with
same input geometry (ignoring other automatically changing features in
3MF like the object UUIDs generated internally).
=> Fix 3MF export to produce correct winding order for internal cavities (fixes #3133).

src/UserModule.cc, src/UserModule.h
This still uses a static vector which should be guarded by the global GUI lock. Using RAII it does ensure that exceptions like "Stop on first Warning" or asserts are cleaning up the stack and prevent leaking module names into later compiles.
=> Fix parent module handling (fixes #3264).

src/input/InputEventMapper.cc, src/input/InputEventMapper.h
Fixes #2921 
The effect is that the timer is now only enabled when (i) there is a joystick and (ii) either (a) it has been moved or buttons pressed recently and we haven't processed that yet or (b) the joystick is sufficiently off-centre and out of the dead zone that we must generate input events.  When this ceases to be true, the timer is disabled again.  So this should solve the cpu usage (and battery wastage) problem for all users, even those with joysticks.
I have tested this by rebasing these patches onto Debian's 2019.05-3 package, as found in Debian testing.  I observe in strace that the program now only polls every 200ms again.  I don't have a joystick-like device so it is difficult for me to test that my change is correct, but I think it should be.
(As far as I can tell the …
=> Only enable 30ms joystick timer when needed

src/openscad.cc
Allows multiple `-o` options from same command line.  
I did a quick manual test, but probably should have a test or two added.  
I think it will require some more extensive changes to the test framework or a new test "type" since all previous tests assume single output.  I'm just not really sure the best way to go about that yet.
=> Initial support for multi-export.

CMakeLists.txt, openscad.pro, src/CSGTreeEvaluator.cc, src/GLView.cc, src/GLView.h, src/MainWindow.h, src/OpenCSGRenderer.cc, src/OpenCSGRenderer.h, src/QGLView.cc, src/QGLView.h, src/ThrownTogetherRenderer.cc, src/ThrownTogetherRenderer.h, src/csgnode.cc, src/csgnode.h, src/editor.h, src/export_png.cc, src/feature.cc, src/feature.h, src/mainwin.cc, src/mouseselector.cc, src/mouseselector.h, src/node.cc, src/node.h, src/parsersettings.cc, src/parsersettings.h, src/polyset.h, src/renderer.cc, src/renderer.h, src/scintillaeditor.cpp, src/scintillaeditor.h
**Click on the Model Jump to the file.**
Or: Make the internal editor more powerful than any external editor.
it is started from two sides: `CSGNode`s do now carry their Index, whereby using the CSGTreeEvaluator we can get back to their parser information and therefore to Line/Column of the definition.
secondly the mouseselector defines its own shader encoding the newly created index into the color of the object.
Currently Working:
* Upon a Click in the renderer, the scene is redrawn into a FBO, and the Object ID is selected
* The object is selected based on its ID.
* The stored location is used to put the cursor in the editor to the beginning of the object defined.
* use tabmanager::open to open the referenced file and jump to the location
* display a context menu with the path through …
=> initial support for a mouse selecting renderer

src/transform.cc, testdata/scad/3D/features/mirror-tests.scad, tests/regression/dumptest/mirror-tests-expected.csg
Less operations and avoiding sqrt makes for more accurate matrix values.
Previous code resulted in some small non-zero values:
```
group() {
group() {
multmatrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) {
cube(size = [1, 1, 1], center = false);
}
}
group() {
multmatrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]]) {
cube(size = [1, 1, 1], center = false);
}
}
group() {
multmatrix([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) {
cube(size = [1, 1, 1], center = false);
}
}
group() {
multmatrix([[1, 0, 0, 0], [0, 2.22045e-16, -1, 0], [0, -1, 2.22045e-16, 0], [0, 0, 0, 1]]) {
cube(size = [1, 1, 1], center = false);
}
}
group() {
multmatrix([[-1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) {
cube(size = [1, 1, 1], center = false);
}
}
group() …
```
=> Improved float accuracy of mirror matrix calculation.

src/clipper-utils.cc
GCC 11 defaults C++ standard to C++17 (http://www.gnu.org/software//gcc/projects/cxx-status.html#cxx17)
openscad.pro selects the default standard ('CONFIG += c++std')
C++17 introduces a std::apply() function (https://en.cppreference.com/w/cpp/utility/apply)
this leads to a name clash in a call to apply() in src/clipper-utils.cc
Thus adding a namespace qualifier.
=> Changing apply() to ClipperUtils::apply() to prevert name clash in C++17 (default for GCC 11)

src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/export.cc, src/export.h, src/export_stl.cc, src/mainwin.cc, src/openscad.cc, src/settings.cc, src/settings.h, tests/CMakeLists.txt, tests/export_import_pngtest.py, tests/validatestl.py
This provides binary stl output, resolving issue #1555.  Since the binary stl files are about 27% the size of the ascii stl files, I've set this as the new default.  Ascii stl file output is still supported, now selectable in the gui under preferences, advanced, export, use ascii stl.  From command-line, ascii stl file output can still be selected by using --export-format asciistl
The binary stl files seem to show up as a correct match to the ascii ones in my tests, load in other programs, and can be successfully reimported into OpenSCAD with the import command.
=> Enable default binary stl output, and ascii option

.github/workflows/cmake.yml
Just noticed the uploads were failing due to recent slight path change.
=> Fix test path for uploads from github CMake builds.

contrib/scad-mode.el
When extending directly from `prog-mode`, it seems there are some edge cases that cause font-lock to hang until you interrupt with `C-g`, as discussed in #2996 
Deriving from `c-mode` fixes the problem. By default, such derived modes call `c-mode-hook` during initialization, but it's not really desirable for scad-mode, so we disable this hook (unless the user overrides this by customizing `scad-mode-disable-c-mode-hook`).
Fixes #2969
=> Make scad-mode derive from c-mode

src/mainwin.cc
Addresses https://github.com/openscad/openscad/issues/3420
- Setting the active editor to read only when hidden 94cc6b4 
- If an autocomplete is being shown, cancel it 2b470a0
=> [#3420] disable editor when hidden

src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/scintillaeditor.cpp, src/scintillaeditor.h, src/settings.cc, src/settings.h
This feature-PR will allow the user to scroll the numbers in the text-editor by scrolling the mouse wheel.
Done:
<hr>
Todo:
=> Number scroll by mouse

src/mainwin.cc, src/scintillaeditor.cpp, src/scintillaeditor.h
I hadn't thought to test additional text input after setting the editor to read only, thought that would already block everything, my bad. Thanks for the comments and sorry for the delay!
Second PR addressing: https://github.com/openscad/openscad/issues/3420
First PR: https://github.com/openscad/openscad/pull/3423
- 7ab7624 fixes https://github.com/openscad/openscad/pull/3423#issuecomment-684084541
- 8d5e046  fixes https://github.com/openscad/openscad/pull/3423#issuecomment-684124142
- f92e0e1 fixes another issue I was encountering where the active call tip wasn't disappearing after hiding the editor
=> [#3420] disable autocomplete on hide - pt.2

src/openscad.cc, src/printutils.cc, src/printutils.h, tests/regression/echotest/errors-warnings-expected.echo, tests/regression/echotest/errors-warnings-included-expected.echo
=> Bring back ECHO: prefix for stderr output.

cmake/Modules/FindLib3MF.cmake, features/lib3mf.prf, src/export_3mf.cc, src/import_3mf.cc, tests/CMakeLists.txt, tests/test_cmdline_tool.py
In working #3477, needed to build lib3MF v1.8 package, and already had distribution lib3MF v2.0.
These changes keep the existing lib3MF v1.8 API export/import unchanged. Adds new code in ifdef to support lib3MF v2.0 API depending on which version is found during compile. Disable lib3MF tests if library not found.
Implements enhancement #3116
=> Add support for lib3MF v2.0 API

src/MainWindow.ui, src/mainwin.cc
This removes the special case for editActionZoomTextIn which had defined an additional Ctrl+= shortcut as this collides with the new one and did not seem to work anyway (at least collides on German keyboard where = is Shift+0).
=> Set keyboard shortcut for "reset translation" as Ctrl+Shift+0 (fixes #3488).

src/QGLView.cc
This will change the selection-Click to **CTRL + Click**. (The modification is 1 line of code - this here should be a discussion about the "correct" UX!)
**Benefits**
* No possible confusion with double click to center object (talking to you @nophead :smiley: )
* This allows for a "Selection-Mode" while Ctrl is pressed in future work, for example to select vertices, edges and faces for measurements.
* has roughly the same meaning in source code, when ctrl + clicking on `include`d/`use`d files
**Downsides**
* I think Apple handles Ctrl + Click not always as ctrl + click, did not find good ressources on that (Maybe @kintel can help out here or suggest a "apple-feel" way to do this.)
* The feature is not as prominent as before, and users might miss it
@t-paul This has to be resolved for the …
=> RFC: mouse selector with ctrl+click

src/mainwin.cc
I didn't do anything with the timestamp portion of the issue. If you want that added maybe you could create a separate issue for that alone.
I just display "Caches Flushed" in the console when the Design->Flush Caches menu option is selected.
=> show message in console when caches are flushed  (fixes #3540)

src/openscad.cc
The do_export() function wants to switch to the parent directory of
the .scad source file for .ast and .csg output. But the path to that
directory is computed at the wrong place, when a different directory
is the current one. This causes failure when the source file is
specified by relative path.
Fixes #3579
=> Fix uncaught exception from boost::fs

src/scadapi.cc
Autocomplete will be disabled inside string literals. When the editor wants to show an auto complete this code will scan the current line up to the cursor position using '"' characters to determine if the user is in a string literal. 
This will fail on the second and subsequent lines of a multi-line string literal. To fix that would require a lot more scanning of the current text.
=> don't show autocomplete in strings (fixes #3563)

tests/export_import_pngtest.py
This patch fixes a bunch of testsuite failures in the Debian packaging. The
packaging uses the testsuite in a different way from normal upstream build
(eg. running it outside of the build directory for autopkgtests), which
triggered this issue.
I do not think this patch is critical to get into the release, I'll just
carry the one-line patch in the packaging along with a few other patches. So
no need to do an RC6 just for this, for sure.
Use an absolute destination path for .csg output. This is necessary to
put the destination file in the correct place when the source path is
a relative path.
When outputting .csg, openscad interprets the destination path
relative to the parent directory of the source file, not relative to
the current directory when the program was started. This means that …
=> Fix export_import_pngtest.py for relative source path

src/mainwin.cc
This is a minimal fix for #3421, which I decided to separate from #3602 since those are larger changes which there isn't much time to test before release.
Also fixed a segfault which was noticed during testing of the console logging (close app during long/infinite recursion echos).
=> Fix for issue 3421

src/Console.cc, src/Console.h, src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/mainwin.cc
Also changed appearance of some other preferences on advanced tab, to not stretch fill the entire width.
BEFORE:
AFTER:
=> Add GUI Console font to Preferences.

src/Console.cc, src/printutils.cc
Fixes #3645 by setting the default background color to transparent and setting the foreground to black for text that has a set background color.  
Before:
After:
=> Update console text colors for dark theme

src/mainwin.cc
A detached Error Log refuses to reattach if the Customizer is also detached, due to a typo, fixed here.
=> Fix errorLog float misreading parameterDock state

src/QGLView.cc
Bring back double click to center, which occasionally did not work - problem was the Framebuffer was not current. 
closes #2466 (superseeded, simpler solution)
closes  #1787 (once and for all!)
=> bring back doubleclick to center

README.md
It seems boost >= 1.56 is required to support move-only types in `boost::variant`.
=> Update minimum supported version of boost.

src/FileModule.cc, tests/CMakeLists.txt
As reported in #3616, --hardwarnings didn't always cause openscad to
exit with a non-zero error code when a warning was encountered. It did
for STL (and likely other geometry outputs) because those exports exited
with an error code if the root node was empty, but PNG and ECHO don't
check that.
I thought that relying on the geometry check seemed a little accidental,
so the fix I've made is to prevent the file context initialization from
swallowing the HardWarningsException.
I also fixed the hardwarnings test. The test passed only because it was
running the openscad executable with invalid commandline parameters.
OpenSCAD printed usage and exited with an error. The SUFFIX parameter is
not supported by the Cmake add_failing_test function, and shouldfail.py
does not automatically add a - for …
=> support --hardwarnings for PNG and ECHO output (#3616)

src/text.cc
In text() call-tip, removed duplicate `string`, added `text=""` and `font=""`
changed the position of `spacing = 1` to match similar code in other files.
=> Improved editor call-tips (fixes #3655).

src/control.cc, src/import.cc, src/linearextrude.cc, src/rotateextrude.cc, src/surface.cc, src/text.cc, testdata/scad/misc/leaf-module-warnings.scad, tests/CMakeLists.txt, tests/regression/echotest/children-warnings-tests-expected.echo, tests/regression/echotest/leaf-module-warnings-expected.echo
Add warnings when child module instantiations are present on builtin modules that do not support them.
Fixes #596.
=> Add warnings when child module instantiations are present on builtin modules that do not support them.

src/control.cc
Use name-based argument parsing in children(), normalizing special variable passing.
Fixes #2104.
=> Use name-based argument parsing in children(), normalizing special variable passing.

patches/qt5/qt-5.15.2-macos-tabbar.patch, scripts/macosx-build-dependencies.sh
This fixes the ugly-looking tab bar on macOS 11 (Big Sur), mentioned in #3775.
The fix is an improved modified backport of the official fix for [QTBUG-86513](https://bugreports.qt.io/browse/QTBUG-86513). It is only required for the time OpenSCAD stays on Qt 5, as the bug is fixed in Qt 6.
Before:
After:
=> Fix styling of tab bar on macOS 11

src/GeometryEvaluator.cc, src/GeometryEvaluator.h, src/Polygon2d.cc, src/Polygon2d.h, src/clipper-utils.cc, src/clipper-utils.h, src/offsetnode.h
The Clipper library used for 2D operations represents vertex coordinates internally with `signed long long` integers (should be 64bit on most if not all supported architectures).
To convert double precision values into integers we have been scaling those doubles by a constant `CLIPPER_SCALE = 1 << 16;` before coercing into integral types.  This can leave a lot of imprecision on the lower end of the scale.
This PR replaces the static with an adaptive scale, which tries to maximize the usable bits of integer precision, depending on the scale of the geometry involved.
Here is a short example I used to show the differences between this nightly and this PR:
```
scalepow2 = -10;
$fn = 100;
d = 2^scalepow2;
linear_extrude(d/10) offset(r=d/10) difference() {
circle(d=d);
translate([d/2,0,0]) …
```
=> Implement variable clipper scale for wider range of effective precision.

src/GeometryEvaluator.cc, src/Polygon2d-CGAL.cc, src/cgalutils-applyops.cc, src/cgalutils-polyhedron.cc, src/cgalutils-project.cc, src/cgalutils.cc, src/cgalutils.h, src/export_amf.cc, src/import_nef.cc, src/openscad.cc, src/polyset-utils-old.cc
edit: I had originally tried removing `#pragma push_macro("NDEBUG")` etc, in addition to the error behavior change, but had to revert those changes.
It appeared to work fine on my local machine at the time that I created the PR, but I guess I just hadn't properly cleaned the build.
=> Call CGAL::set_error_behaviour(CGAL::THROW_EXCEPTION) only once from main.

CMakeLists.txt
This updates the previously forgotten macOS deployment target value.
Re-issuing this separately because I closed #3784. For details, see #3775.
=> Update macOS deployment target for QT 5.15.2 upgrade

src/openscad.cc
This is the new version of #3784. For details, see the comments of this merge request.
Thanks to @icecream95 for proposing this fix in #3837. The new solution checks if there are some windows left and deletes them, rather than just exit as my old solution did.
Because this issue also happens outside of macOS, I decided to point the merge request to 'master' rather than 'qt5-upgrade-macos'.
=> Fix segfault on exit

src/export_dxf.cc
dxf export converted to polyline, so each island comes out as single entity when imported.
Most users would probably need it to be as such, after all what's the use of 100's of separate line 
segments for a circular path.
Removed extra dxf sections for inkscape compatibility as it is not needed anymore.
Tested in inkscape and https://sharecad.org/# only.
If this is acceptable will do more test on other apps.
=> dxf export as polylines

src/CGALCache.cc, src/CGALCache.h, src/CGAL_Nef_polyhedron.cc, src/CGAL_Nef_polyhedron.h, src/GeometryCache.cc, src/GeometryCache.h, src/MainWindow.cc, src/MainWindow.h, src/Polygon2d-CGAL.cc, src/Polygon2d.h, src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/RenderStatistic.cc, src/RenderStatistic.h, src/Settings.cc, src/Settings.h, src/export.h, src/export_png.cc, src/input/QGamepadInputDriver.h, src/openscad.cc, tests/data/python/gen_svg_viewbox_tests-template.py
Draft for extended summary output, first intended to support #3827 but should be also able to cover #433 eventually.
New command line arguments:
`--summary all|camera|cache|time|geometry|bounding-box`
`--summary-file filename|-`
If `--summary-file` is given, information is exported in JSON format, using `-` it will be sent to `stdout`.
Example for just the camera data:
`echo 'sphere(5);cube(10);' | ./openscad --summary camera --summary-file - -o /tmp/x.png - --render | jq`
```
{
"camera": {
"distance": 66.16001403043475,
"fov": 22.5,
"rotation": [ 55, 0, 25 ],
"translation": [ 2.548037052154541, 2.548037052154541, 2.548037052154541 ]
}
}
```
Output with `all`:
```
{
"cache": {
"cgal_cache": {
"bytes": 276376,
"entries": 1,
"max_size": 104857600
},
"geometry_cache": {
"bytes": 17776, …
```
=> Add summary output.

src/Preferences.ui, src/handle_dep.cc
This PR resolves every warning I'm seeing in the build process, except for the shift/reduce warnings in the comment parser for customizer settings.  (This is because I can't find any complete test cases or specification for the expected behavior of that part, meaning I cannot properly evaluate attempted edits to this.  So resolving that goes to later work.)
This resolves a non-substantive UI warning, and makes a substantive improvement to the processing of the command-line -m make_cmd, adding in proper error reporting for failures of the resulting system() call.
=> Resolve build warnings

src/printutils.h
Undefine `vsnprintf` in addition to `snprintf`.
Closes #3913
Fore more info see https://github.com/msys2/MINGW-packages/pull/9612.
=> Undefine some defines from libintl.h

CMakeLists.txt
This was originally added in https://github.com/openscad/openscad/pull/3941, but must have gotten lost during refactoring in https://github.com/openscad/openscad/pull/3948
=> Put back accidentally removed -DCGAL_DEBUG

.circleci/config.yml, scripts/macosx-build-dependencies.sh
Similar to #3973 but for the CircleCI snapshot build:
* Use Homebrew tools to build dependencies, to avoid using MacPorts' cmake which hardcodes the MacPorts library path
* Use CircleCI built-in caching support
* Validate OpenSCAD binary
I've also validated that the 3 different macOS builds (CircleCI snapshots, GitHub snapshots, CircleCI release) have exactly  the same dependency chain of all direct and implicit library dependencies (i.e. all libraries also have exactly the same dependency chain).
=> Rewrite CircleCI macOS snapshot to use Homebrew and CircleCI caching

openscad.appdata.xml.in
Use of &lt;mimetypes&gt; is deprecated in appdata [1]. Replace it by the now
recommended &lt;provides&gt; => &lt;mediatype&gt;.
Motivated by a warning shown for package openscad  in the Debian infrastructure [2].
[1] https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-mimetypes
[2] https://appstream.debian.org/sid/main/issues/openscad.html
=> Fix deprecated use of <mimetypes> in appdata

.circleci/config.yml, scripts/macosx-build-dependencies.sh, scripts/msys2-install-dependencies.sh
With this change we can incrementally build the cache by just running the build multiple times. The always stored cache should also ensure we are not completely losing the cache after 15 days.
=> Add timeout option for macos dependency build.

CMakeLists.txt, src/MainWindow.cc, src/ext/json/json.hpp, src/feature.cc, src/feature.h, src/func.cc, src/import.h, src/import_json.cc, tests/CMakeLists.txt, tests/data/json/data.json, tests/data/scad/json/import-json.scad, tests/regression/echotest/import-json-expected.echo
Extracted from #3087 as the internal object data type is already available.
Example with JSON file:
```
{
"number": 2,
"float": 3.5e-10,
"bool": true,
"string": "hallo world!",
"array_number": [ 0, 1, 2, 3, 5 ],
"array-string": [ "one", "two", "three" ],
"array-mixed": [ "one", 1, false ],
"object": {
"name": "The object name",
"nested": {
"value": 42
},
"number": 4
}
}
```
Usage:
```
j = import("scad-data.json");
echo(j.string); // ECHO: "hallo world!"
echo(j.array_number); // ECHO: [0, 1, 2, 3, 5]
echo(j["array-string"]); // ECHO: ["one", "two", "three"]
echo(j.object.name); // ECHO: "The object name"
echo(j.object.nested.value); // ECHO: 42
```
=> Add JSON import.

src/DrawingCallback.cc, src/libsvg/path.cc
Improve SVG arc rendering to use logic closer to circles with $fn, $fs, $fa
Add comments about bezier rendering that could use $fs, $fa if we moved to a chord/arc length instead of parameter subdivision.
=> improve svg arc rendering to use logic closer to circles with $fn, $fs, $fa

.github/workflows/windows.yml
..the individual test output is too large to upload
=> Windows CI: Only output test report and log

scripts/macosx-build-dependencies.sh
Now that the build use Homebrew instead of MacPorts, we can remove the workaround for the bad MacPorts CMake build
=> Use built-in libz on macOS

.circleci/config.yml, scripts/macosx-build-dependencies.sh
Goal is mostly to reduce build time to make our build more robust against CI resource limitations: qt5 build time seems to have dropped from 48min to 31min.
=> Remove more unused features from qt5 build

src/ScintillaEditor.cc
This is a partial fix for issue #1172
While we can't allow full syntax coloring on lines starting with # (without major changes), we can color everything after the first word.
=> partial fix for issue #1172, allow partial syntax coloring on lines starting with #

cmake/Modules/FindLib3MF.cmake
Update the FindLib3MF.cmake to correct version 2.0 build. Previous change did not update necessary LIB3MF_FOUND used in version 2.0 check, and include file was missing from find_path.
Added secondary pkg_check_modules for lowercase lib3mf pkg-config file.
Tested with lib3MF 1.8.1 and 2.0.1.
May fix #3709, but was not able to test with 2.1.1.
=> Fix lib3MF version 2.0 build

README.md
Link to macOS building instructions wasn't working
=> Updates link in toc of README.md

.gitignore, cmake/Modules/FindGLIB2.cmake, scripts/macosx-build-dependencies.sh, scripts/setenv-macos.sh, scripts/translation-make.sh, scripts/translation-update.sh
Mostly for macOS:
* Removing libxml2, as it comes with macOS
* QScintilla wasn't properly cleaned before build, potentially leaving caches from old build. This caused the build to break after a compiler update.
* Removed qmake-specific comments
* `scripts/setenv-macos.sh` can now be used interactively, for manual builds.
* Fixed `sed` invocation causing a couple of stray `-e` backup files.
* GLIB2 may use built-in libs, don't limit lib searches to our install dirs
=> Minor build system fixes

src/comment.cc
This is a security fix, mitigating an out-of-bounds read as outlined in issue #4043
=> Add file bounds check to comment parser, issue #4043

src/lexer.l
Remove some unicode specific error position offsets from comments and strings in lexer.l, so the error position is now in bytes as expected the the qscintilla line/position code, so we can correctly highlight errors after unicode in strings and comments.
=> fixing #3939, removing some unicode specific error position offsets from lexer

src/ScintillaEditor.cc
pretty straightforward.... but will still take 90 minutes to finish automated testing.
=> use byte length instead of glyph length in qscintilla apis, fixing #4050

patches/uuid-1.6.2.patch, scripts/macosx-build-dependencies.sh
* Removed custom `libffi`; it comes with macOS
* Removed custom `ragel`; harfbuzz now ships with ragel-generated files
* Removing libxml2 could cause the script to fail, added `-prune` argument to `find`
* use `-arch` and `-mmacos-version-min` instead of `--target` arguments to `configure` for gmp and mpfr.
* The GLEW pkg-config file had the wrong prefix, added GLEW_PREFIX
* uuid.pc is now correctly installed
=> More macOS build fixes

.circleci/config.yml, .github/workflows/macos-release.yml, .github/workflows/macos-snapshot.yml, scripts/macosx-build-dependencies.sh
Glib has deprecated the old build system in favour of meson. In preparation for x86_64/arm64 cross builds, we need to bite the bullet and get this updated.
=> macOS dependencies: Update glib to 2.71

CMakeLists.txt
=> Avoid installation of mimalloc header files during "make install"

scripts/builder.sh, scripts/travis-ci-before-install-linux.sh
Build script should use secure https connection to files.openscad.org to avoid possible man in the middle attacks.
=> Change: use secure connection to files.openscad.org

resources/docs/docs_downloader.py
Downloader script should use secure https connection to files.openscad.org to avoid possible man in the middle attacks.
If reformatting the code is undesirable. Simply cherry-pick only the according commit.
=> Secure docs downloader

src/primitives.cc, tests/regression/dumptest/polyhedron-tests-expected.csg
This is to avoid crashing upcoming mesh-based code in fast-csg (https://github.com/openscad/openscad/pull/3641) with files like tests/data/scad/3D/features/polyhedron-tests.scad
=> Skip incomplete faces in polyhedron builtin

src/CGAL_Nef_polyhedron.cc, src/cgalutils.cc, src/cgalutils.h
New in CGALUtils: transform, computeResizeTransform, createAffineTransformFromMatrix.
Also a boundingBox overload now accepts Geometry
This is to prepare fast-csg changes (see https://github.com/openscad/openscad/pull/3641)
=> Extract transform logic from CGAL_Nef_polyhedron to CGALUtils

src/export_stl.cc
It was pointed out that the size_t triangle_count > 4294967295 is always false on 32-bit systems, which should be inconsequential because of process memory limits preventing any possible runtime issue, but might result in warnings.  This cleans it up by using uint64_t.
=> size_t to uint64_t for triangle count

CMakeLists.txt, scripts/sort_cmake_filelist.sh
This helps fail builds fast (and can pick which files to build first by just touching them), esp. when many files need to be rebuilt (e.g. when modifying a core header often but mostly caring about the compilation of a couple of C++ files).
Disabled on Windows (forks out to bash script tested on Mac and Linux), or if -DSORT_BUILD=0 passed to cmake
Note that it all relies on make to build files in the order they're provided (modulo -j parallelism), which only POSIX make seems to guarantee (but others still seem to do).
cmake needs to be re-run to sort the files again (e.g. at each step of a git rebase, which you'd probably do anyway)
=> Build most recently modified files first

src/dxfdata.cc
* Add safety (test for, and continue past, bad indices)
* Report warnings about bad indices
* Add variables just to make the array indices easier to read and debug
=> Add safety to line lookups in DXF import (fixes #4037)

src/context-mm.cc, src/context.cc, src/context.h
Only subtract from accounting if we added to accounting in the first place, avoiding crash/assert due to subtracting too many counts from the heapSizeAccounting.
Fixes #3871
=> add status to context accounting, fixes #3871

src/import_3mf.cc
I wasn't able to build against lib3mf 2.2.0 because of this error:
```src/import_3mf.cc: In function ‘Geometry* import_3mf(const string&, const Location&)’:
src/import_3mf.cc:379:53: error: cannot convert >‘std::shared_ptr<const Geometry>’ to ‘CGAL_Nef_polyhedron*’ in initialization
379 |     CGAL_Nef_polyhedron *N = CGALUtils::applyUnion3D(children.begin(), children.end());
|                              ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                                                     |
|                                                     std::shared_ptr<const Geometry>
```
I was able to fix it with this patch, and I think potentially this instance of the `applyUnion3D` call was missed in this commit: …
=> Convert remaining instance of applyUnion3D in import_3mf.cc

CMakeLists.txt, src/CGALHybridPolyhedron.cc, src/CGALHybridPolyhedron.h, src/cgalutils-applyops-hybrid-minkowski.cc, src/cgalutils-applyops-hybrid.cc, src/cgalutils-applyops.cc, src/cgalutils-convex.cc, src/cgalutils-hybrid.cc, src/cgalutils-mesh.cc, src/cgalutils-polyhedron.cc, src/cgalutils.h
Saves ~40% render time off a simple example like this compared to the last snapshot (with `--enable=fast-csg --enable=fast-csg-trust-corefinement`), and 18x faster than without `fast-csg`:
```js
$fn=50;
minkowski() {
difference() {
hull() {
translate([3, 0, 0]) cube(0.5, center=true);
cube(1, center=true);
}
translate([0, 0, 0])
sphere(1);
}
sphere(1);
}
// Baseline: 10m55s
// Baseline w/ fast-csg & trust: 1m20s
// This PR w/ fast-csg & trust: 35s
```
Notes:
-   I've tried switching things from Polyhedron_3 to Surface_mesh but it's still slower for some reason. Might revisit.
-   Models using minkowski are likely to hit the over-triangulation of corefinement, which is a known issue that should be fixed by https://github.com/openscad/openscad/pull/4107 (maybe when CGAL 5.5 gets out).
=> [fast-csg] Port minkowski to the hybrid fast-csg world

src/cgalutils-corefine.cc
Allows calling exact less for the same effect.
=> [fast-csg] Use the new new_vertex_added callback in CGAL5.4 for fast-csg-exact-callbacks feature

src/MouseSelector.cc
Testing the fix for screen going black on context menu from https://github.com/openscad/openscad/issues/3725#issuecomment-1042413285
Fixes #3725
=> Disable depth test after extracting pixel data.

CMakeLists.txt
With CGAL 5.0, the in-line version request fails (tested with 5.0.2 in Ubuntu 20.04, the latest LTS for a couple months yet).  This PR swaps it for a version check right afterward.  I currently recommend switching it back to the in-line version request when we upgrade requirements to a higher CGAL version minimum.
=> Switch to an afterwards check for CGAL version

examples/Functions/recursion.scad, scripts/builder.sh, scripts/release-common.sh, src/feature.cc, src/input/InputEventMapper.cc, src/libsvg/path.cc, src/value.h, tests/CMakeLists.txt, tests/export_pngtest.py
Found via `codespell -q 3 -S *.po,./src/ext,./libraries/MCAD,./submodules/mimalloc -L childs,clen,nd,synopsys,tesselate,tesselation,tesselator,uncomplete,vie`
=> Fix various typos

.circleci/config.yml, CMakeLists.txt
Threading support has been dropped from the WASM build. This makes it much easier to consume and with that this flag can be removed. 
The flag does not break the new build but its not needed anymore.
=> Remove -pthread for WASM build

src/gui/ScadLexer.cc
this fixes #4144
```
union(){
// parsed }
// inside [ will collapse the curly brace from the union
}
```
```
str1 = "Hallo { ";
cube();
str2 = "} Welt";
```
this has one side effect worth noting:
currently brackets within commented out section can be folded:
```
/*
if(true){
while(true){
cube();
}
}
*/
```
This fix sees this whole comment block as one fold-able comment, ignoring the brackets within.
I could expand the code so that the code makes a "best effort" of matching brackets within the comment, but given that comments are by no means guaranteed to be well formatted, commented out code, this seams more trouble then it is worth.
**Todo:** I will to some more testing and at screenshots for documentation.
=> only process syntactically relevant brackets for folding (fixes #4144)

src/core/Value.cc, src/core/Value.h
This change was tested against the sample code in #4172, and while it does not fix the crash, it delays the crash until higher values of `b`, by going through fewer function calls, and re-using `tostream_visitor` instead of constructing new ones for each nested vector. 
My testing showed the lowest value to trigger a crash went up by about 1000 after changes.
Lowest b value required to trigger a crash, built with `g++-10`
```
RelWithDebInfo build:
unedited master: b=5390
with changes:    b=6378
Release build:
unedited master: b=4936
with changes:    b=6081
Debug build:
unedited master: b=3465
with changes:    b=3905
```
Also removed some `Value::toString|toStream` functions which were not being used.
=> Stack usage optimization for tostream_visitor

scripts/uni-get-dependencies.sh
Remove unused (and non existing in package archive) fedora build dependency: qscintilla-devel
Openscad builds just fine without this dependency and fails while trying to install this non-existing package. 
qscintilla-qt5-devel should include all the neccessary files.
=> Remove unused qscintilla-devel build dependency for fedora

README.md
Simple update to README to help potential contributors get set up.
=> Update sample git clone command in README to use https: instead of git:.

src/glview/OffscreenContextWGL.cc
Fixes #4180
When animating from the command line interface, the code registers the
window class on each frame. This worked for the first frame, but the
registration for the second frame seemed to fail. Actually,
RegisterClassW was merely indicating that the second registration was
redundant.
This change ignores ERROR_CLASS_ALREADY_EXISTS, which seems to be the
least intrusive way to solve the problem.
I tested the solution in a proof-of-concept program, but I haven't tested
this actual patch because building OpenSCAD for Windows is onerous.
(There will probably still be bugs here.  It looks like the code never
destroys the windows it creates, and it creates a new one for each frame.
And each of those windows has its own DC because of the CS_OWNDC in the
window class.  So a many-frame …
=> Fix error handling when creating an offscreen OpenGL context on Windows.

scripts/macosx-sanity-check.py, tests/mingw_convert_ctest.py
"Testing whether an object is 'None' using the == operator is inefficient and potentially incorrect."
=> Fix python 'testing equality to None' issue

src/gui/ScadLexer.cc
`use` and `include` are not normal keywords. The usage of angle brackets `<>` is unique and has some interesting effects, that should be reflected by the syntax highlighting.
I will post some examples in future comments.
The main reference for openscad syntax for the purpose of this discussion is the lexer:
https://github.com/openscad/openscad/blob/667abf11c60a514ab28456e410309c621557f03a/src/core/lexer.l#L142-L147
https://github.com/openscad/openscad/blob/667abf11c60a514ab28456e410309c621557f03a/src/core/lexer.l#L151-L166
This merge request should bring syntax highlight closer inline with the current syntax interpretation.
If any of the example look like bugs (not features) this is out of scope for this merge request.
=> syntax highlight: include and use have a unique syntax

src/gui/Editor.h, src/gui/MainWindow.cc, src/gui/ScadLexer.cc, src/gui/ScintillaEditor.cc, src/gui/ScintillaEditor.h
#4205 works well, when opening a new file.
When editing, not restoring the lexer state for `include` and `use` can create artifacts.
Here an example:
Take this text:
```
echo("test");
use<test123>;
echo("test");
```
add two new lines after use<
```
echo("test");
use<
test123>;
echo("test");
```
and you see incorrect highlighting:
This merge requests fixes that by recoloring the whole text after a parse of the top level document.
This merge request also removes all indicators, when parsing the file was not successful.
=> recolor the whole text after evaluation

src/core/lexer.l, tests/regression/echotest/include-recursive-test-expected.echo, tests/regression/echotest/include-tests-expected.echo, tests/regression/echotest/use-tests-expected.echo
I think it is useful to know, in which file a failing include/use statement is, as include and use can be nested.
I think that the location being set to none could go back to the times where why did not have the filename in the location datastructure and thus only outputted the line number (which is of little use for this warning). But now that we have filepaths, having the location of the statement is actually useful.
Generating the relative path of the file is a bit tricky/wonky (I think due to include/use within include/use being relative to the file being parsed) as the test cases show, when comparing GUI and console.
The main reason for the relative paths was so that the test results are stable.
=> add location to "Can't open library" and "Can't open include file" warning

src/gui/MainWindow.cc, src/gui/MainWindow.h
ISSUE:
During application close widgets are cleaned up, so the MainWindow::progresswidget pointer is cleared.  This causes a segfault in 
MainWindow::report_func here:
// FIXME: Check if cancel was requested by e.g. Application quit
if (thisp->progresswidget->wasCanceled()) throw ProgressCancelException();
Perhaps the comment is implying that this is a known bug?
REPRODUCE:
Close the app while running this (broken) .scad file (or any file that generates a lot of warnings):
```
module shell(x)
{
for(i=[0:360])
{
hull()
{
cube([x,x,1]);
rotate([0,i,0]) translate([i,0,0]) cube([x,x,1]); 
}
}
}
shell(x=foo);
```
FIX:
In MainWindow::closeEvent() progress_report_fin() is called to stop any global progress reports from passing through to the deleted window.  
In MainWindow an "isClosing" flag is …
=> Fix segfault if app closed while lots of logging

RELEASE_NOTES.md, doc/TODO.txt, src/core/lexer.l
* I accidentally left a debug output in the lexer.
* my text editor was confused by the Gravis in the Release Log
* the todo list contains resolved task
* Allow specifying viewpoint in the scad file
* More strict checking of module parameters to make e.g. this fail:
> o More strict checking of module parameters to make e.g. this fail:
>   module test(a,b) { a=1; b=2; echo(a,b,c); } test(c=3);
>   (also for built-in modules)
that seams to be done:
```
WARNING: variable c not specified as parameter in file , line 1
WARNING: Parameter a is overwritten with a literal in file , line 1
WARNING: Parameter b is overwritten with a literal in file , line 1
```
=> clean up of small things

cmake/Modules/FindCairo.cmake, scripts/release-common.sh
This is needed mainly for the static build on MXE as this needs to link to other libraries like pixman too.
=> Rely on pkg-config only for finding cairo.

src/gui/input/AxisConfigWidget.cc, src/gui/input/AxisConfigWidget.h
this adresses on aspect of #3937
> Also `rotateVPRelGain` is not saved at all. (Seems to be missing at [AxisConfigWidget.cc](https://github.com/openscad/openscad/blob/8d59f235d40f0b34a87a24f1121e54913311be48/src/input/AxisConfigWidget.cc#L157))
=> fix preference setting for RotateVPRelGain

src/core/lexer.l, tests/data/scad/misc/linenumber.scad, tests/regression/echotest/linenumber-expected.echo
this is supported syntax:
```
use <test>
use
<test>
use
<test>
```
This is a quirk of the lexter, not a feature:
```
use
<
test
>
use <
ignored line
used line
>
assert(false);
```
**In release**, it even throws of the line counting.
`[\n\r]` was unhandled, only the last path/filename was used as such.
**In nightly**, I recently fixed the line counting.
Doing so, I specifically added handling of `[\n\r]`.
That feels wrong, as it really is not well defined. But I do not want to make it an error for compatibility.
Making it a warning is a fair compromise.
We could argue, that this is a feature:
```
include<folder/
file.scad>
include
<folder/
file.scad>
```
but it is inconsistent
```
include<folder/
subfoler/
file.scad>
include<folder\
file.scad>
include
<folder\
file.scad>
use
<folder/ …
```
=> warning when a \n is found in use<> or include<>

src/core/Expression.cc, src/core/ImportNode.cc, src/core/LinearExtrudeNode.cc, src/core/Parameters.cc, src/core/Parameters.h, src/core/RotateExtrudeNode.cc, src/core/TransformNode.cc, src/core/Value.cc, src/core/Value.h, src/core/builtin_functions.cc, src/core/control.cc, src/core/primitives.cc, tests/regression/echotest/cross-tests-expected.echo, tests/regression/echotest/errors-warnings-expected.echo, tests/regression/echotest/errors-warnings-included-expected.echo, tests/regression/echotest/issue1528-expected.echo, tests/regression/echotest/len-tests-expected.echo, tests/regression/echotest/lookup-tests-expected.echo, tests/regression/echotest/min-max-tests-expected.echo, tests/regression/echotest/norm-tests-expected.echo, tests/regression/echotest/ord-tests-expected.echo, tests/regression/echotest/rands-expected.echo, tests/regression/echotest/text-metrics-test-expected.echo, tests/test_cmdline_tool.py
That was a puzzle.
The ord-tests did not match what I got, when I regenerated the expected files.
No matter how I changed the expected file, the test would always passed.
The problem is here:
https://github.com/openscad/openscad/blob/d777dc24af688b2becff8ac01581ebf1612b42bf/tests/test_cmdline_tool.py#L126-L133
Python throws an exception, as it is not a valid UTF8 file.
Which ord-tests claims to be:
https://github.com/openscad/openscad/blob/d777dc24af688b2becff8ac01581ebf1612b42bf/tests/data/scad/misc/ord-tests.scad#L2-L4
As exception handling, the python script sets the text to empty string.
As both files are not valid UTF-8 Files, both are represented as empty string, which off-course matches.
see http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html#files- …
=> fix and regenerate ord-tests

src/gui/ErrorLog.cc, src/gui/ErrorLog.h, src/gui/ErrorLog.ui
* static constexpr -> enum
* map various resizes to resizeRowsToContents()
* the effect is that row height auto adjusts, which leads to line break
* (instead of Ellipsis/`...`)
* add tool tip 
* disable drag and drop
* I did not find functionality linked to drag and drop
* remove TRACE from the ErrorLog UI options
this is #4225, but with TRACE and Message Nr. removed
=> error log improvement

src/glview/Renderer.cc
boost::filesystem deprecated the string_file.hpp header with 1.79.0 [1],
which implicitly pulled in <fstream>.
In this case only std::fstream is used anyway, so just include <fstream>
directly.
[1] https://www.boost.org/users/history/version_1_79_0.html
=> Include <fstream> to fix the build with boost >= 1.79.0

src/core/builtin_functions.cc, tests/CMakeLists.txt, tests/data/scad/json/import-json-relative-path.scad, tests/data/scad/json/submodule/submodule.scad, tests/regression/echotest/import-json-relative-path-expected.echo
Previously we took the filename as-is, which caused us to attempt to
open skewed paths.
Add a test.
=> Fix using a relative path to `import` JSON in a `use`d file

src/handle_dep.cc, src/handle_dep.h, src/openscad.cc
The depsfile was written for each output file, resulting in only the very last output filename actually being in the dependency file. This means that all outputs but the last won't have their dependencies known to make.
This PR changes this so that the depsfile is only written once, after all outputs have been created.
=> fix depsfile when using multiple outputs

src/geometry/GeometryUtils.cc
Changes for src/geometry/GeometryUtils.cc:296: Non-boolean value (-1) returned from function returning bool.
According to discussion in #4247 `-1` changed to false
=> tessellatePolygonWithHoles() return value fix

src/core/FreetypeRenderer.h, src/geometry/cgal/cgalutils-polyhedron.cc, src/glview/VertexArray.h
Due `std::unary_function<>` [link](https://en.cppreference.com/w/cpp/utility/functional/unary_function) is a deprecated с++11 and removed in c++17 and seems not necessary here, we can remove it to fix warnings:
'unary_function<std::vector<signed char>, unsigned long>' is deprecated [-Wdeprecated-declarations]
'unary_function<const FreetypeRenderer::GlyphData *, void>' is deprecated [-Wdeprecated-declarations]
Also minor fix for cgalutils-polyhedron.cc file: signed-unsigned compare and syntax error in alternative implementation (it's disabled by preprocessor by-default)
Checked with gcc and clang, but they are too fresh to spot compatibility problems (or my build flags can be differ from CI)
=> Removing deprecated std::unary_function 

src/platform/PlatformUtils-mac.mm
This PR adds an error check to `userConfigPath` on MacOS. Without this, I was getting segfaults in some edge cases (like running openscad as a system user).
In the event of error, it returns an empty string, which is the same behavior as on Linux (in `PlatformUtils-posix.cc`).
=> Add error check to userConfigPath on mac

src/gui/MainWindow.cc, src/gui/MainWindow.h, src/gui/TabManager.cc
In response to #4353, we really need to be catching std::exception and logging to the console its .what() message for exception throws during compilation, which this PR does.  The unknown exception remains as a fallback.
=> Catch and log std::exception for compilation

CMakeLists.txt, src/gui/QGLView.cc, src/gui/QGLView.h, src/gui/QGLView2.cc
Take special note of the voodoo warning, and of the NEEDSWORK note for the copyright notice on a new file.
=> Save and restore GL context on double click.  Fixes #4332.

src/gui/MainWindow.cc, src/gui/MainWindow.h, src/gui/TabManager.cc
Fixes #3690
The source of this bug was that the 'filename' field in the editor interface object does not always hold the filename and path of the recently saved file.  
I change the call to `updaterRecentFiles()` argument from a pointer to the editor interface to a QString with the recent filename and path, which is available in both of the functions which call `updateRecentFiles()`.
=> Fix recent file list bug

.github/workflows/codeql-analysis.yml, .github/workflows/linux.yml, .github/workflows/macos-release.yml, .github/workflows/macos-snapshot.yml.disabled, .github/workflows/macos-tests.yml, .github/workflows/windows.yml
inline with the blog entry below project CI is generating warnings relating to the soon to be deprecated node runtime.
project ci files checked for uses: clauses and updated where current imported actions were using node 12 runtime.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> Update to github ci to migrate to node 16 compatible versions

src/core/FreetypeRenderer.cc, src/core/FreetypeRenderer.h
- Avoiding redundant inheritance from `std::vector`
- Releasing resource in dtor, instead of external functor, should improve readability
- Straightforward memory allocation pattern: one chunk for all GlyphData of each `text` command. Technically I found a small difference in average runtime: from 34.5 to 33.9 seconds 734 symbols of 'Lorem ipsum" text, and J5040 CPU, but I believe it's not the main goal of this patch.
=> FreetypeRenderer::GlyphData destruction simplification

src/geometry/cgal/Polygon2d-CGAL.cc
Some builds were failing after changes from #4402
=> Fix for OBS builds

src/gui/input/SpaceNavInputDriver.cc
Adds #include "utils/printutils.h" to fix build issue. 
Thanks Peepsalot on IRC for the actual fix!
=> Add missing include to SpaceNavInputDriver.cc

CMakeLists.txt, scripts/macosx-build-homebrew.sh, src/core/Builtins.cc, src/core/ContextFrame.cc, src/core/ContextMemoryManager.cc, src/core/Expression.cc, src/core/Expression.h, src/core/RotateExtrudeNode.cc, src/core/Value.cc, src/core/Value.h, src/core/ValueMap.h, src/core/control.cc, src/core/customizer/ParameterObject.cc, src/core/customizer/ParameterObject.h, src/core/function.h, src/core/lexer.l, src/core/parser.y, src/ext/json/json.hpp, src/geometry/cgal/CGALHybridPolyhedron.cc, src/geometry/cgal/CGALHybridPolyhedron.h
Testing if builds still work when switching from C++14 to C++17.  
I also may have gotten carried away trying out `std::variant` in lieu of `boost::variant`.
I'm still not sure if there's any benefit to doing so, and I haven't seen any measurable difference in performance.
The visitors in `Value.cc` are slightly cleaner by not having to inherit `boost::static_visitor<return_T>`.
=> C++17 Update

.github/workflows/windows.yml, tests/CMakeLists.txt, tests/CTestCustom.template, winconsole/CMakeLists.txt
I found `tests/CMakeListst.txt` difficult to follow, and wanted to give it a more clear structure.
So I did a large refactoring, mostly re-ordering chunks of the file so that similar commands are grouped into major sections, each having its own prominent label.
- Check Dependencies
- Platform Specific Configurations
- Define Macros and Functions
- Configure Templated Files and Generated Tests
- Define test configurations
- Define Various Test File Lists
- Add experimental features tests
- Add tests
- Disable Tests with Known Issues
- Extra Debug Info
Due to the way certain data is stored or generated, some steps should only be done before/after others. 
One of the reasons for splitting things up this way, was to make it easier to verify/enforce this ordering.  For example
- "Define test …
=> Major rearrangement of tests/CMakeListst.txt

.github/workflows/codeql-analysis.yml
OS has been updated from Ubuntu 20.04 to 22.04, which does not contain `qt5-default` package.
=> Remove qt5-default from CodeQL CI

scripts/common-build-dependencies.sh, scripts/uni-build-dependencies.sh, src/core/SourceFile.cc
Existing version numbers did not compile or were not available for download anymore.
With  the proposed changes, the dependencies and OPENSCAD compiles without any warning/issue in my FC37
(glib 2.75 uses meson & ninja  now to compile), this could be added the the documentation as base requirement)
=> Adapt Version numbers in uni-build-dependancies

scripts/macosx-build-dependencies.sh
The current harfbuzz-2.3.1 fails to build on M1 on macOS 12.6.1, Xcode 13.4.1.
See https://github.com/harfbuzz/harfbuzz/pull/2995
=> Upgrade harfbuzz to 2.8.2 to fix compilation error

.github/workflows/macos-release.yml, .github/workflows/macos-tests.yml, .github/workflows/windows.yml
A couple of existing actions are just displayed as "build"; this will show which platform the actions are for.
=> Improve display name of github actions

cmake/Modules/FindHidAPI.cmake
Verified that this correctly detects HID devices in the GUI.
I don't have a compatible HID device to test with, but this at least allows people to try.
=> Make hidapi findable on macOS. Fixes #4194

CMakeLists.txt
..and don't look for the executable if not.
=> Make clang-tidy required if requested

.github/workflows/macos-tests.yml
This really just buys us some time, so we can investigate the issue offline.
=> Downgrade macOS runner to macos-11, to silence #4470

scripts/macosx-build-dependencies.sh
This should fix the CircleCI macOS build issue
=> Make sure libunistring isn't picked up from the Homebrew environment

patches/OpenCSG-1.5.1-MacOSX-port.patch
It was malformed and didn't get applied cleanly on macOS 13.
=> Fix OpenCSG macOS patch

.github/workflows/macos-tests.yml
It's a bit wasteful to wait 6 hours for a hanging test to finish. Kill it after 1h; we can adjust this if it ever takes longer.
=> Set macOS timeout to 60 minutes

.github/workflows/macos-tests.yml
The macOS runner was downgraded in #4490 to silence a hanging test (#4470). The hang was mitigated in #4501, so we can revert to macos-latest again.
=> Run on macos-latest

src/io/export_png.cc
Found this when generating an animation resulted in the error:
> Maximum number of clients reached
> Unable to open a connection to the X server.
> DISPLAY=:0
> Can't create OpenGL OffscreenView. Code: -1.
=> Fix leaking xsessions in export_png.cc

scripts/uni-get-dependencies.sh
Hey @t-paul, didn't realize the app image was built using that script, might need another update sorry!
(context: https://github.com/openscad/openscad/pull/4533)
Edit: Now I see the [latest workflow](https://app.circleci.com/pipelines/github/openscad/openscad/3399/workflows/f388688a-cce4-4fc6-bcbe-de70c00e5335/jobs/13941) succeeded, maybe you already added the dep to the image 🥳
=> Add TBB to uni-get-dependencies.sh so it makes it to the AppImage

.circleci/config.yml, CMakeLists.txt
[This example now runs great](https://ochafik.com/openscad/#%7B%22source%22%3A%7B%22name%22%3A%22input.stl%22%2C%22content%22%3A%22%2F%2F%20Copyright%202021%20Google%20LLC.%5Cn%2F%2F%20SPDX-License-Identifier%3A%20Apache-2.0%5Cn%2F%2F%5Cn%2F%2F%20Author%3A%20Olivier%20Chafik%20(http%3A%2F%2Fochafik.com)%5Cn%2F%2F%5Cn%2F%2F%20This%20is%20my%20little%20print-in-place%20chain%2Fscalemail%20project%20where%20I%20wanted%20to%20be%5Cn%2F%2F%20able%20to%20draw%20on%20each%20scale%20separately%2C%20or%20across%20all%20of%20them%20(3D%20printing%20of%5Cn%2F%2F%20large%20etchings%20may%20work%20best%20with%20support%20material%2C%20but%20for%20small%20text%20it's%5Cn%2F%2F%20fine).%5Cn%2F%2F%5Cn%2F%2F%20This%20is%20my%20little%20chain%2Fscalemail%20project%20where%20I%20wanted%20to%20be%20able%20to% …
=> Enable Manifold in WASM builds

src/Feature.cc, src/Feature.h, src/geometry/cgal/CGALHybridPolyhedron.cc, src/geometry/cgal/cgalutils-coplanar-faces-remesher.h, src/geometry/cgal/cgalutils-corefine.cc, src/geometry/cgal/cgalutils-corefinement-visitor.h, src/geometry/cgal/cgalutils-mesh.cc, src/io/export_stl.cc, tests/CMakeLists.txt
There's been too many features for too long, time to tidy things up!
- `fast-csg` now implies former `fast-csg-remesh`, `fast-csg-exact`, `fast-csg-exact-callbacks`, `fast-csg-trust-corefinement`
- `fast-csg-safer` is same as formerly not enabling `fast-csg-trust-corefinement`
- `predictible-output` implies former `sort-stl` and `fast-csg-remesh-predictibly`
These might be the last days of [fast-csg](https://github.com/openscad/openscad/pull/3641) anyway 😅 (see https://github.com/openscad/openscad/pull/4533).
=> [fast-csg] Simplify experimental features.

src/glview/GLView.cc, src/glview/GLView.h, src/gui/OpenCSGWarningDialog.cc, src/gui/OpenCSGWarningDialog.ui, src/gui/Preferences.cc, src/gui/Preferences.h, src/gui/Preferences.ui, src/gui/QGLView.cc, src/gui/QGLView.h
I don't expect there to be any real usage of pre-OpenGL 2 devices in the wild, so proactively removing this to keep future code cleaner.
=> Remove support for OpenGL < 2

src/glview/NULLGL.cc, src/glview/OffscreenContextAll.hpp, src/glview/OffscreenContextCGL.mm, src/glview/OffscreenContextEGL.cc, src/glview/OffscreenContextGLX.cc, src/glview/OffscreenContextWGL.cc, src/glview/OffscreenView.cc, src/glview/OffscreenView.h
Done in anticipation of cleaning up the offscreen context code.
=> Green refactoring: Move duplicated FBO handling out of platform-specific context code

scripts/uni-get-dependencies.sh
The makefile can not be generated if tbb-devel is
not installed.
=> Fix dependencies on openSUSE

src/geometry/GeometryEvaluator.cc
The old code rounded down the number of fragments in rotate extrude, which lead to weird results when working with a low number of $fn. By rounding up that number we always at least get the number of fragments needed to span a real body when working with degrees > 180.
=> round up number of fragments in rotate_extrude

src/geometry/GeometryEvaluator.cc
We should move the range check outside the loop calculating min/max x coordinates. There are two reasons behind this:
1. With the old implementation a violation might get detected early without going through all loops but this approach makes the loop processing in the non-error case slower due to repeated testing. It is advisable to optimize for the non-error case of optimization for error case since the non-error case is the one users will execute normally.
2. With the old implementation the printed range is incorrect since it will only print the range of all the vertices processed so far instead of the full range as printed in the new implementation. This produces quite confusing values in the error case.
=> move range check outside loop in random_extrude

CMakeLists.txt
ENABLE_TBB is still possible to turn off
=> EXPERIMENTAL now always builds with Manifold.

scripts/macosx-build-dependencies.sh
glib2 2.75 is required to be build on MacOS with latest clang (14.0.3). More info https://gitlab.gnome.org/GNOME/glib/-/issues/2759
=> Fix: Bump required version of glib2

.github/workflows/manual.yml
This is here to easily enable custom workflow runs; a `workflow_dispatch` even must be present in the master branch to allow running custom workflows from other branches.
=> Added empty manual workflow

src/glview/OpenGLContext.h
An update in the compiler toolchain to gcc 13 detected this obvious oversight.
=> add missing include of <cstdint> for uint32_t

scripts/macosx-build-dependencies.sh
Reverts openscad/openscad#4610 as it broke snapshot builds
=> Revert "Fix: Bump required version of glib2"

tests/CMakeLists.txt
Added tests, some of which fail, but are disabled, due to #4632.
=> Add some tests exercising relative output filenames

src/core/SurfaceNode.cc, src/core/primitives.cc, src/geometry/GeometryEvaluator.cc, src/geometry/PolySet.cc, src/geometry/PolySet.h, src/geometry/PolySetUtils.cc, src/geometry/cgal/Polygon2d-CGAL.cc, src/geometry/cgal/cgalutils-mesh.cc, src/geometry/cgal/cgalutils-polyhedron.cc, src/geometry/cgal/cgalutils.cc, src/io/export_stl copy.cc, src/io/import_3mf.cc, src/io/import_amf.cc, src/io/import_obj.cc, src/io/import_stl.cc
PolySet is a vector of polygons (vectors), so we can avoid a myriad of tiny (or big) reallocs by:
*  Reserving the vector of polygons when it's easy (e.g. in binary STL import, primitives...)
*  Requiring a polygon size arg in PolySet::append_poly to reserve the polygon's vector
`sphere(10, $fn=1000);` renders 1.18x faster with this!
And this one that does some actual CSG ops, still 1.13x faster (`--enable=manifold --export-format=binstl`):
```
sphere($fn=1000);
translate([0.5, 0, 0])
sphere($fn=1000);
```
=> Avoid excessive reallocations in PolySet

src/core/builtin_functions.cc, tests/regression/echotest/search-tests-expected.echo
Follow-up to #1312, which removed one of the warning cases, but not this.
=> Remove unnecessary warning when a search string wasn't found in a vector

patches/glib-iconv-macos.patch, patches/glib-pcre-macos.patch, scripts/macosx-build-dependencies.sh
Bump to latest (2.76.3) version of glib.
Includes a patch to make the latest glib build correctly for our build variant. See https://gitlab.gnome.org/GNOME/glib/-/issues/3025 for related discussion.
=> Bump glib to 2.76.3 for macOS

.circleci/config.yml, scripts/macosx-build-dependencies.sh
This allows us to add local patches to a package without having to force-rebuild dependencies.
Also bumping CircleCI xcode version as the existing one is deprecated.
=> Support patch version in macosx-build-dependencies + bump xcode

scripts/github-ci.sh
-> be more robust if we run github-ci.sh without the build action
=> don't package .gcov if it doesn't exist

README.md
Might be needed on non-ARM Macs, but my M2 wouldn't build without meson installed.
=> meson required for MacOS M2 build

src/glview/VertexStateManager.cc, src/glview/VertexStateManager.h, src/glview/cgal/CGALRenderer.cc, src/glview/preview/OpenCSGRenderer.cc, src/glview/preview/ThrownTogetherRenderer.cc
This PR also removes a couple of `GL_TRACE` statements. All these fixes address some feedback that @kintel previously left on #4675 that I decided to make into a separate PR.
=> Gsoc 2023: Rename vertices_size to num_vertices where appropriate

CMakeLists.txt, src/glview/OffscreenContextFactory.cc, src/glview/OffscreenContextGLX.cc, src/glview/OffscreenContextGLX.h, src/io/export_png.cc, src/utils/scope_guard.hpp
This is the GLX portion of https://github.com/openscad/openscad/pull/4582 - splitting up that PR as testing on all platforms is time consuming.
* Automated tests
* export test
=> Add new, more capable, GLX offscreen support

.circleci/config.yml
As notified by CircleCI:
> This is your final reminder to update any projects using the macOS medium resource by October 2nd. After 10/2, any jobs that run on the medium macOS resource will show an “invalid resource class” error.
> Please update the resource class key in your configuration file to macos.x86.medium.gen2 before October 2nd.
=> Set resource class for macOS runner.

.github/workflows/macos-tests.yml
Homebrew's cairo >= 1.18 uses the Quartz backend which doesn't have the 'Liberation Sans' font
=> Disable PDF export test on macOS with homebrew

scripts/macosx-build-dependencies.sh
macOS 13 build fix: If libclang is installed with Homebrew it would be picked up without this fix.
=> macOS deps: Disable Qt5 qdoc to avoid libclang dependency

tests/image_compare.py, tests/test_pretty_print.py
This adds in support in the testing suite for generating an image with a bright red overlay on the parts of the image that differ between expected and actual.  It also adds an output column to the html report that includes this difference highlighting image.  The highlight image is only generated if there is a test failure result from image comparison, which occurs if and only if there is some part of the image which could be highlighted.
For future clarification, the mask is added onto the actual rather than the expected.  In most cases this doesn't matter much, but this could make a difference in certain cases where the test does not pick up a difference (such as 1 or 2 pixel width stripes).  In that case those additional anomalies in the actual image created by the current test run …
=> Add image difference mask to tests

tests/CMakeLists.txt
Since it's becoming increasingly likely that Manifold will become preferred over fast-csg, and the test system has some conflicts around which is being used as default, we're removing the fast-csg tests.
The main goal is to clean up some cruft, and removing fast-csg tests makes that a bit easier.
If needed, we can put it back post-cleanup.
=> Remove fastcsg tests

src/core/SurfaceNode.cc, src/core/primitives.cc, src/geometry/GeometryEvaluator.cc, src/geometry/PolySetBuilder.cc, src/geometry/PolySetBuilder.h, src/geometry/PolySetUtils.cc, src/geometry/cgal/Polygon2d-CGAL.cc, src/geometry/cgal/cgalutils-mesh.cc, src/geometry/cgal/cgalutils-polyhedron.cc, src/geometry/cgal/cgalutils.cc, src/geometry/manifold/ManifoldGeometry.cc, src/geometry/roof_ss.cc, src/geometry/roof_vd.cc, src/io/export_obj.cc, src/io/export_off.cc, src/io/export_wrl.cc, src/io/import_3mf.cc, src/io/import_amf.cc, src/io/import_obj.cc, src/io/import_stl.cc
Smallish refactoring of PolySetBuilder:
* Move all PolySet allocation to the `build()` method
* Return a unique_ptr. Some mess (releasing unique_ptr) moved to the call site, which will be cleaned up next
* Allow building without CGAL
* Coding style fixes
* Fixes an indexing bug in export_wrl.cc
=> PolySetBuilder refactoring

src/io/import_amf.cc
```
[ 25%] Building CXX object CMakeFiles/OpenSCAD.dir/src/io/import_amf.cc.obj
C:/msys64/home/jordan/openscad/binary-arithmetic/src/io/import_amf.cc: In member function 'virtual xmlTextReader* AmfImporterZIP::createXmlReader(const char*)':
C:/msys64/home/jordan/openscad/binary-arithmetic/src/io/import_amf.cc:328:51: warning: 'int zip_get_num_files(zip_t*)' is deprecated: use 'zip_get_num_entries' instead [-Wdeprecated-declarations]
328 |     if ((zipfile == nullptr) && (zip_get_num_files(archive) == 1)) {
|                                  ~~~~~~~~~~~~~~~~~^~~~~~~~~
In file included from C:/msys64/home/jordan/openscad/binary-arithmetic/src/io/import_amf.cc:282:
C:/msys64/mingw64/include/zip.h:383:68: note: declared here
383 | ZIP_DEPRECATED("use 'zip_get_num_entries' instead") ZIP_EXTERN …
```
=> Replace zip_get_num_files() with zip_get_num_entries().

src/core/lexer.l
It was using a mix of tabs and spaces, and the tabs seemed to be set up for 4-space indents so didn't display correctly anywhere (by default).
Switch to all spaces, using 4-space indents.
Some actions were not aligned with the rest.  Align them.
The net is no change in the resulting c/h files, other than whitespace changes.
If this is OK, merge this one first and then I'll resync #4891 with it.  I don't want to do both in one PR because I want to keep the formatting changes (this one) easy to separate from the semantic changes (#4891).
=> Standardize lexer.l on 4-space indents using spaces.  Align all actions.

locale/ru.po, src/gui/Preferences.ui, tests/data/scad/issues/issue4172-echo-vector-stack-exhaust.scad
Some trivial updates to preferences. All the other advanced preferences start with a capital letter.
=> Preferences typo and Capitalisation

src/gui/Animate.cc, src/gui/ErrorLog.cc, src/gui/ErrorLog.h, src/gui/MainWindow.cc, src/gui/MainWindow.h, src/gui/Preferences.cc, src/gui/Preferences.h, src/gui/ScadLexer.cc, src/gui/ScintillaEditor.cc, src/gui/TabManager.cc, src/gui/ViewportControl.cc, src/gui/parameter/ParameterVirtualWidget.cc, src/openscad.cc
With Qt5Compat and without gamepad support.
and Fix slots not matching signals with Qt 6
---
These changes allow me to do a non-experimental build and run OpenSCAD on Qt 6 (and still with Qt 5 too).
N.B. I am really a Python person so do please check carefully - especially the use of QSoundEffect, and I kinda guessed what the return value of `ScadLexer2::description()` should be.
=> Changes to allow building with Qt 6

src/gui/ScintillaEditor.cc
Dropped in Qt Core 6.
---
I can say this compiles on both Qt 5 and 6. But not sure what these regular expressions do; pressing keys in the editor seems to still work as usual.
=> Replace use of QRegExp

src/Feature.cc, src/Feature.h, src/glview/VertexArray.cc, src/glview/VertexArray.h, src/glview/cgal/CGALRenderer.cc, src/glview/cgal/CGAL_OGL_VBO_helper.h, src/glview/preview/OpenCSGRenderer.cc, src/glview/preview/ThrownTogetherRenderer.cc, tests/CMakeLists.txt
This enables the `vertex-object-renderers-direct` and `vertex-object-renderers-prealloc` functionality together with `vertex-object-renderers` is enabled, and removes them as options.
The main reason is that `glBufferSubData()` is too slow on macOS, so we'll prefer preallocating buffers, but this has proven to be very slow on Linux too for certain types of models.
Related to https://github.com/openscad/openscad/issues/4782
Fixes #4883, #4504
=> VBO: Make vertex-object-renderers-direct and -prealloc enabled by default

src/gui/MainWindow.cc
Dropped in Qt 6:
D:/a/openscad/openscad/src/gui/MainWindow.cc:457: error: use of deleted
function 'constexpr void Qt::operator+(QFlags<Modifier>::enum_type, QFlags<Modifier>::enum_type)'
---
Compiles on Qt 6, let's see if it does so on Qt 5. Haven't run it (MS Windows only).
=> Stop using + operator when creating QKeySequence

src/glview/preview/LegacyThrownTogetherRenderer.cc
Forgot to pass shaderinfo to setColor(), causing shader uniforms to not be set.
Fixes #4915
=> Fix edge rendering in legacy Throwntogether mode

src/gui/Preferences.ui
Remove duplicate (and non-operative) Toolbar Export 3D/2D options from "Console" section.
Move working Toolbar Export 3D/2D options from "User Interface" to "Export Features".
Before (note that bottom one does not match toolbar buttons):
After:
Note:  There's one section of the file that's just deleted; there's another that's moved unchanged from one place to another.
=> Clean up Toolbar Export 3D/2D preferences

src/glview/OffscreenView.cc
This fixes a bug causing fallback to GLX to not work as expected.
=> Use strcmp() to compare char* strings

src/gui/Preferences.cc, src/gui/Preferences.h, src/gui/Preferences.ui, src/gui/TabManager.cc, src/gui/parameter/ParameterWidget.cc, src/gui/parameter/ParameterWidget.h
This (probably) isn't ready to be merged.
It adds entries to Preferences/Advanced allowing control of the font and size used in the customizer data pane.
It mostly works, but:
* Some aspects are stretching my knowledge of C++ and there might be better answers.
* The text inside spinboxes resizes dynamically, but the box around the text doesn't.
I considered trying to control the stuff *above* the data pane, the preset control stuff, and decided that that should be part of a more general "UI font size" control that would affect all text in forms, menus, et cetera.
Review comments solicited.  I'll write something up tomorrow about the areas that I'm not happy with, but right now it's bedtime.
=> Make customizer font and size selectable.

src/io/import_off.cc
Rewrote the OFF import as I initially thought it didn't work, because of a badly scaled KiCad export converted through MeshLab.
This version removes the dependency on CGAL, and should be at feature parity.
Still missing is color support but we miss the API for that, and binary format support as I couldn't find any sample file.
=> Rewrite OFF import

CMakeLists.txt
This fixes the issue that re-running cmake causes a `TBB::tbb target not found` error.
Also, added fallback to pkg-config if find_package(TBB) failed.
=> Update manifold to get TBB fix, print TBB version

src/geometry/GeometryUtils.cc, src/geometry/GeometryUtils.h, src/geometry/manifold/ManifoldGeometry.cc, src/geometry/manifold/ManifoldGeometry.h, src/geometry/manifold/manifold-applyops-minkowski.cc, src/geometry/manifold/manifold-applyops.cc, src/geometry/manifold/manifoldutils.cc, src/geometry/manifold/manifoldutils.h, src/io/export.h, src/openscad.cc, tests/CMakeLists.txt, tests/export_import_pngtest.py
`--render=cgal` was really meant for converting to the internal format of the current geometry engine to utilize any of its built-in mesh validation and repair tools. When using another geometry backend, we're changing this to `--render=force` to force conversion into the current backend-specific geometry.
`--render=cgal` is still useable for backwards compatibility, but not sure for how much longer we need to support it.
Also added some opportunistic refactoring.
=> Rename --render=cgal to --render=force to force-convert to the current backend-specific geometry

src/glview/Renderer.cc
Was catching spurious Qt 6.6.2 error:
GL_INVALID_OPERATION in glDrawBuffers(unsupported buffer GL_BACK_LEFT)
https://bugreports.qt.io/browse/QTBUG-122819
=> Remove GL check from Renderer glLinkProgram()

src/gui/Preferences.cc, src/gui/Preferences.h
The currentTextChanged signal triggered at the wrong moment, overwriting the syntaxhighlight setting in OpenScad.conf; this is solved by using the textActivated signal.
This fixes the issues mentioned in #4992 and #4920.
=> Fix syntax highlight colorscheme persistence (#4992 and #4920)

scripts/git-archive-all.py, tests/data/python/gen_issue2342-template.py, tests/data/python/gen_svg_viewbox_tests-template.py, tests/export_import_pngtest.py, tests/export_pngtest.py, tests/test_cmdline_tool.py, tests/test_pretty_print.py
=> chore(python): remove py2 compatibility imports

scripts/git-archive-all.py, tests/mingw_convert_ctest.py, tests/validatestl.py
`open` always uses read in utf8 mode.
=> chore(python): remove redundant open modes

tests/shouldfail.py, tests/test_cmdline_tool.py
=> chore(python): migrate string format

tests/test_pretty_print.py
=> chore(python): remove py2 import

src/gui/MainWindow.cc, src/gui/OpenSCADApp.cc, src/gui/Preferences.cc, src/gui/QGLView.cc, src/gui/ScintillaEditor.cc, src/gui/TabManager.cc, src/openscad.cc
Only the Q_OS_MACX ones are creating deprecation warnings at the moment, but that is something anyway. But get ahead and be consistent.
Deprecated in Qt 5:
https://doc.qt.io/qt-5/qtglobal.html#Q_OS_MAC
https://doc.qt.io/qt-5/qtglobal.html#Q_OS_OSX
=> Replace deprecated Q_OS_MAC and Q_OS_MACX

scripts/git-archive-all.py, tests/data/python/gen_issue2342-template.py, tests/data/python/gen_svg_viewbox_tests-template.py
=> chore(python): migrate to f-string

src/glview/cgal/CGALRenderer.cc
When rendering geometry resulting in pure PolySets (primitives or anything rendered using `manifold` or `fast-csg`), and change the color scheme afterwards, this geometry would _not_ change color. Only CGAL Nef polyhedrons would.
This fixes this by forcing VBO rebuild from PolySets.
=> Bugfix: Color scheme changes didn't affect rendered polysets

src/geometry/GeometryEvaluator.cc, src/geometry/cgal/cgalutils-project.cc, src/geometry/manifold/ManifoldGeometry.cc, src/geometry/manifold/ManifoldGeometry.h, src/geometry/manifold/manifoldutils.cc, src/geometry/manifold/manifoldutils.h, tests/data/scad/2D/features/projection-cut-tests.scad, tests/regression/dumptest/projection-cut-tests-expected.csg
This should give `projection(cut=true)` a few orders of magniture speed boost.
Also fixes #2584
=> Use Manifold's Slice() and Project() to implement projection()

.github/workflows/macos-tests.yml
..since github upgraded to a broken macos-14 runner.
Upstream issue: https://github.com/actions/runner-images/issues/9712
=> Temporarily downgrade to macos-13

src/gui/MainWindow.cc, src/gui/Preferences.cc
Change default for "Auto-Reload and Preview" to false, so new installations have to manually turn it on.
The initial GUI state (new install / cleared configuration) is very messy:
This changes the default to dock Console/ErrorLog/Animate as tabs and hide the Customizer and ViewportControl docks:
=> Fix initial GUI setup.

scripts/git-archive-all.py, scripts/macosx-sanity-check.py
Convert regex with escape sequences to raw string to avoid invalid escape sequence.
Closes #5040
=> fix(python): invalid escape sequences

src/gui/ViewportControl.cc, src/gui/ViewportControl.ui
Addresses #5116 - Viewport-Control widget can be made too narrow & tab order was lost is now weird.
PR #5107 improved the Viewport-Control widget by allowing it to morph to a vertical layout when the widget became too narrow for the original horizontal layout.  Very nice!
However, after that change the widget could be made too narrow and look bad because the controls were "cut off" and only partially visible.  #5107 also lost the left-to-right top-to-bottom tab order within the widget. This PR fixes both of these issues.  See #5116 for screenshots and detailed steps.
=> Viewport-Control widget: Limit width to at least dynamic minimum size of widget. Add tab order back in.  Fixes #5116

src/gui/input/HidApiInputDriver.cc
Following up on #5153 - I cannot build this right now, but the USB ID should be of general use.
=> Add USB ID for 3Dconnexion Space Mouse Wireless BT

.github/workflows/codeql-analysis.yml, .github/workflows/linux-tests.yml, .github/workflows/manual.yml, .github/workflows/non-experimental.yml, scripts/github-ci-linux-get-dependencies.sh, scripts/github-ci.sh
Some tidying up of github-ci-linux-get-dependencies.sh and its use with old and misnamed Ubuntus and an attempt to avoid similar problems in future by defaulting to ubuntu-latest (although that still does have to be defined in one place).
gcovr completes, but the reports show no coverage - which actually isn't any different to the existing tests on other PRs as far as I can see.
`gcovr -r ../src` does seem an improvement on `gcovr -r ..` in that it doesn't collect source files from the build directory or submodules.
=> Test on Ubuntu 24.04 and Qt 6

scripts/uni-get-dependencies.sh
Hopefully (= I have tested. But it won't show in the PR checks) this fixes the recent linux-build-matrix.yml failures. Also removes some code for long unsupported distros.
=> Run apt-get update for Debian based OS's in uni-get-dependencies.sh

.github/workflows/linux-tests.yml, scripts/github-ci-linux-get-dependencies.sh
Save an additional change every time ubuntu-latest is updated.
An unknown code name causes an error.
---
OK it's only every 2 years but this felt a bit half-done at the time.
=> Look up the Ubuntu code name in github-ci-linux-get-dependencies.sh

color-schemes/render/daylight-gem.json, color-schemes/render/nocturnal-gem.json
This adds two new color schemes, paired for dark and light background preferences, for an overall prettier OpenSCAD render.
The nocturnal gem color scheme:
The daylight gem color scheme:
=> Add daylight gem and nocturnal gem color schemes

src/core/Builtins.h, src/core/builtin_functions.cc, src/gui/MainWindow.cc
The following code should have random values at each run for the first 3 sets of values output, so that unseeded random values can be utilized easily in combination with seeded random values, without the seed sticking BETWEEN runs.  This PR resolves this by calling a new initialize_rng function when a compile is done, restoring the prior behavior of reliably having randomness before a seed is used.
```
echo(rands(0, 100, 3));
echo(rands(0, 1, 1, 42));
echo(rands(0, 100, 3));
```
=> Reseed rng at compile for unseeded initial vals

.github/workflows/linux-tests.yml, scripts/uni-get-dependencies.sh
Only still available on Ubuntu 20.04 which has neither Qt 4 or Qt 6.
=> Stop installing qt5-default on Debian based OS's

scripts/check-dependencies.sh
Was reporting:
```
opencsg           1.4.2             1.6.              OK
fontconfig        2.10              2.15.             OK
```
Now:
```
opencsg           1.4.2             1.6.0             OK
fontconfig        2.10              2.15.0            OK
```
=> Fix installed version numbers reported by check-dependencies.sh

scripts/uni-build-dependencies.sh
Bison 2.6.1 is twelve years old and fails to build on Ubuntu 20.04.
---
On Ubuntu 20.04:
```
CC       fseterr.o
fseterr.c: In function 'fseterr':
fseterr.c:77:3: error: #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
77 |  #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
```
3.8.2 compiles fine, and is itself 3 years old so should be widely compatible.
Unlikely anyone will hit this if everything else is working, but it is an easy update and still functions.
Closes #5186.
=> Update build_bison to version 3.8.2

src/geometry/cgal/cgalutils-triangulate.cc
..doesn't allow two consecutive equal vertices in a constraint. Fixes #5198
=> Bugfix: CGAL's constrained delaunay triangulator 

.circleci/config.yml, CMakeLists.txt, README.md
As part of deploying development versions of https://github.com/openscad/openscad/pull/5180 to the web playground, I struggled a bit to build for WASM. This PR should improve the DX (and allow incremental WASM builds).
(preparing changes to the wasm image too [here](https://github.com/openscad/openscad-wasm/compare/master...ochafik:openscad-wasm:simpler-wasm))
cc/ @t-paul @DSchroer
=> `build`: move WASM build options into CMakeLists.txt, remove unneeded steps

src/geometry/manifold/manifoldutils.cc
- Don't return a failed manifold from createManifoldFromSurfaceMesh
- Try/catch when repairing a manifold w/ CGAL, which has high chances of exploding (in createManifoldFromPolySet)
(actually now seeing https://github.com/openscad/openscad/pull/5223 may now been catching some of these at a higher level, catching errors is a hot trend :-D)
=> Handle invalid manifolds with more care

scripts/github-ci-linux-get-dependencies.sh, scripts/uni-get-dependencies.sh
Linux Mint 18 & 19 are EOL
git-core is a virtual package provided by git
libboost-dev installed by libboost-all-dev
libcgal-qt5-dev related bug was resolved in libcgal-dev-4.8-1
libfontconfig1-dev is installed by a virtual package in Ubuntu 20.04, subsequently a dummy package
libgmp3-dev is a dummy package
libqt5scintilla2-dev is a virtual package provided by libqscintilla2-qt5-dev
=> Simplify Debian dependencies

src/glview/cgal/CGAL_OGL_VBO_helper.h
A vector may be resized during use, which would invalidate all pointers into it.
=> Fix freed memory access issue when using gluTess

CMakeLists.txt, README.md, src/gui/OpenSCADApp.cc, src/gui/OpenSCADApp.h, src/gui/qt-obsolete.h, src/utils/version_check.h
https://bugreports.qt.io/browse/QTBUG-65592
was duplicated by:
https://bugreports.qt.io/browse/QTBUG-67069
and then by:
https://bugreports.qt.io/browse/QTBUG-70571
which was fixed by:
https://code.qt.io/cgit/qt/qtbase.git/commit/?id=e2d79b496335e8d8666014e900930c66cf722eb6
Reverts:
36bc309a7 ("Add workaround for jumping dock widgets.", 2018-12-08)
---
I can't recreate the problem on Linux with Qt 5 or 6 with this patch.
On QTBUG-65592 ? and macOS users reported the bug fixed.
There was a late comment from a Windows user however, but that was 5 years ago and I can't find any subsequent bugs plus there have been 3 more Qt 5 releases since.
Ubuntu 20.04 has Qt 5.12.
=> Increase minimum Qt version to 5.12.0

src/gui/Editor.h, src/gui/MainWindow.cc, src/gui/MainWindow.h, src/gui/ScintillaEditor.cc, src/gui/ScintillaEditor.h
Hi all, 
With @lakfel we would like to implement parts of the work presented in this paper https://thomaspietrzak.com/bibliography/gonzalez23.pdf by [Johann Felipe Gonzalez](https://cil.csit.carleton.ca/staff-members/johann-felipe-gonzalez-avila/) et Al . 
The present PR is the first part containing interactive visual feedback in the text editor when user is selecting different object in the 3D view. The second part will consist in interactive visual feedback as overlay in the 3D view.
A small video of the first part: 
[![Video showing the feature](https://img.youtube.com/vi/4_XNRgZO_MY/0.jpg)](https://youtu.be/4_XNRgZO_MY)
In this video we can see how the active selection impact the text editor content. In green are represented the selected objects and the call stack depth (with the …
=> Add interactive visual feedback when selecting object using the rightClick menu in the 3D view

src/glview/GLView.cc
Patch from https://github.com/openscad/openscad/issues/5292#issuecomment-2351044029
=> Fix Axis Font Not Rendering Correctly Windows 11 (fixes #5292).

.gitignore, scripts/run-clang-tidy-cached.cc
A self-contained c++ program that runs clang-tidy in parallel on all files that changed since last invocation. It also takes changed headers into acccount and re-processes all files that depend on these.
Fully self-contaiend, so it can be invoked as a 'script' as it compiles itself; a simple
scripts/run-clang-tidy-cached.cc
works (but also invoking with 'sh -c' if you wish).
The results are cached in ~/.cache/clang-tidy out of tree, so different checkouts or switching between branches
will also only need to process the different files.
The output are two files
* OpenSCAD_clang-tidy.out : contains the detailed 'compiler warning'-like output (I usually use `cat OpenSCAD_clang-tidy.out` as 'compile command' in my editor to be able to step through it.
* OpenSCAD_clang-tidy.summary : A summary …
=> Development: add a script that caches clang-tidy results.

scripts/beautify.sh, scripts/coverity.sh, scripts/generate-potfiles.sh, scripts/generate-svg-icons.sh, scripts/git_merge_fix_false_deletions.sh, scripts/github-ci-linux-get-dependencies.sh, scripts/github-ci.sh, scripts/github-release.sh, scripts/installer-linux.sh, scripts/macosx-build-dependencies.sh, scripts/macosx-build-homebrew.sh, scripts/msys2-install-dependencies.sh, scripts/release-common.sh, scripts/sort_cmake_filelist.sh, scripts/update-snapshots.sh, scripts/update-web.sh, tests/data/modulecache-tests/cascade.sh, tests/data/modulecache-tests/cascade2.sh
The baked-in assumption that bash resides in /bin/bash is not always true, so invoke with /usr/bin/env to be more compatible.
=> Make invocation of bash scripts posix compatible.

.clang-format
Configured, so that it is similar to what uncrustify would produce, but applyig it will still be a massive change, so there needs to be a large scale submit once. The output looks (to my eyes) strictly better than uncrustify, which sometimes does qeustionable
Started in a comment-thread in another PR
https://github.com/openscad/openscad/pull/5306#issuecomment-2363622267
How to apply:
```bash
clang-format -i $(find src -name "*.cc" -o -name "*.h" | grep -v src/ext/)
```
Some comments
* I did not attempt to fully recreated the uncrustify configuration (is there an automatic tool ?), but mostly looked at the style 'manually' and applied  configuration options that mostly match it.
* there are numerous options to tweak https://releases.llvm.org/18.1.6/tools/clang/docs/ClangFormatStyleOptions.h …
=> Add .clang-format configuration file.

CMakeLists.txt, scripts/github-ci-linux-get-dependencies.sh
Since:
4b645fc30 ("updated manifold to latest version with double precision floating point (#5282)", 2024-09-20)
=> Thrust is no longer used

CMakeLists.txt, src/core/BuiltinContext.cc, src/geometry/roof_vd.cc, src/io/DxfData.cc, src/utils/calc.cc, src/utils/degree_trig.cc
Setting the #define in the compilation unit makes it dependent if the same header had been included before; if <cmath> has been included before (and we don't know that, as we don't know what system headers do between each other), the include-guard will prevent our definition to ever been seen.
So the only way to make sure <cmath> sees the _USE_MATH_DEFINES define is to set it on the compile command line, i.e. in the CMakeLists.txt
=> Don't #define _USE_MATH_DEFINES in *.cc files but as compile define.

src/geometry/roof_ss.cc
CGAL changed the return type of `CGAL::create_interior_straight_skeleton_2()` from boost::shared_ptr to std::shared_ptr.
=> CGAL 6.0 build fix

src/core/ContextMemoryManager.cc, src/core/SurfaceNode.cc, src/core/Tree.h, src/core/Value.cc, src/core/customizer/ParameterObject.cc, src/geometry/cgal/cgalutils-applyops-hybrid.cc, src/geometry/manifold/manifoldutils.cc, src/glview/ColorMap.cc, src/glview/OffscreenView.h, src/glview/RenderSettings.cc, src/gui/Preferences.cc, src/gui/ScadApi.cc, src/gui/parameter/ParameterWidget.cc, src/io/DxfData.cc, src/io/import_off.cc, src/openscad.cc, src/platform/PlatformUtils.cc, src/utils/boost-utils.cc, src/utils/svg.cc
One commit per header. Addressing headers needed for
* `std::bad_alloc`
* `std::optional`
* `std::endl`
* `std::priority_queue`
* `std::invalid_argument`
* `std::out_of_range`
* `std::runtime_error`
* `std::getline`
* `std::string`
* `std::u32string`
* `std::errc`
* `std::tie`
* `std::tuple`
* `std::get_if`
* `std::holds_alternative`
* `std::visit`
=> Address some long-tail missing std::* includes

src/gui/CGALWorker.cc
The worker may return an unevaluated manifold geometry, which will be evaluated when the renderer attempts to get the underlying mesh, and freeze the GUI thread. This also throws the render time off.
=> force manifold evaluation before worker exit

src/Feature.cc, src/Feature.h
Easy way to disable fast-csg for now. Unless someone complains loudly, let's kill it later on.
=> Hide fast-csg

src/io/export_pov.cc
Also, replace one 'auto' variable with explicit type, so that clang-tidy does not consider PolySet an unneeded header.
=> Add missing headers in export_pov.

tests/CMakeLists.txt
Fixes: 
```
CMake Deprecation Warning at tests/CMakeLists.txt:5 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
=> Sync tests/CMakeLists.txt cmake versions requirement with top level requirements

src/core/parser.y
=> Fix difference between boost and std library treatment of empty path in filesystem::absolute

src/FontCache.cc, src/core/parsersettings.cc, src/openscad.cc
This addresses a difference in behavior between `boost::filesystem::absolute` and `std::filesystem::absolute` where passing an empty path to boost would return `fs::current_path()`, and the std library now throws a `std::filesystem_error`.
I don't know if an empty path can even necessarily reach all these calls, but better to just handle the possibility regardless, than wait for another bug report.
=> Add protection/workaround for every possible call to fs::absolute with empty path

.github/dependabot.yaml
Limit bot to update only monthly to avoid spam and save resources. Also group to one PR to limit PR spam.
=> feat(ci): add dependabot to keep GH Actions up to date

CMakeLists.txt
These haven't been relevant for a while:
- Manifold does not have googletest as a submodule since https://github.com/elalish/manifold/commit/a7eac920871b90e7593e117d32d24f9c9fad72dd (and MANIFOLD_TEST is OFF)
- nanobind is used now
=> Remove obsolete Manifold Python CMake commands

src/LibraryInfo.cc
Update to v3.0.0 release of Manifold.
This release provides a version.h which we can use to print
the library info.
Fixes #5432
=> Update manifold to v3.0.0; print manifold version in library info.

scripts/release-common.sh
Forgot to add the USE_QT6 CMake option
=> Build OpenSCAD with Qt6 for macOS

src/gui/MainWindow.cc, src/gui/MainWindow.ui, src/gui/Preferences.cc, src/gui/Preferences.h, src/gui/Preferences.ui, src/gui/Settings.cc, src/gui/Settings.h, src/io/export.cc, src/io/export.h
This also moves from having ASCII STL export a separate advanced preference setting into having separate menu entries for ASCII vs. binary STL.
Fixes #5466
@gsohler: FYI
=> More export action refactoring

src/gui/MainWindow.cc
=> Workaround for Qt crash bug related to resizing/moving a bad geometry

src/libsvg/shape.cc
There's an identical include in src/core/OffsetNode.cc so should be OK for everyone - let's see...
=> Fix libsvg build with external Clipper2

.circleci/config.yml, tests/wasm-check.html
Follow up from https://github.com/openscad/openscad/pull/5210, which I should have left as draft a bit longer 🫣 
- fix path for wasm binary in web test
- install latest node for node job (not just for web branch)
=> Fix circleci wasm workflows

src/core/parsersettings.cc, src/platform/PlatformUtils.cc, tests/wasm-check.html
This fixes file imports in web wasm builds.
Similar to https://github.com/openscad/openscad/pull/5210 & https://github.com/openscad/openscad/pull/5515
=> Fix a few more fs::canonical on emscripten

scripts/check-dependencies.sh, scripts/uni-get-dependencies.sh
After installing the dependencies using uni-get-dependencies.sh, Fedora 41 fails to recognize qscintilla2:
```
$ ./scripts/check-dependencies.sh 
depname           minimum           found             OKness            
qt                5.12              5.15.15           OK                
./scripts/check-dependencies.sh: line 230: -query: command not found
./scripts/check-dependencies.sh: line 230: -query: command not found
qscintilla2       2.9               unknown           NotOK             
cgal              5.4               5.6.2             OK                
gmp               5.0               6.3.0             OK                
mpfr              3.0               4.2.1             OK                
boost             1.61              1.83              OK …
```
=> Fix check-dependencies.sh on Fedora 41

src/gui/Preferences.cc, src/gui/Preferences.h
Fix remaining issue from #5026
Using `BlockSignals` instead, to avoid emitting signal when combobox is populated.
=> Don't use the textActivated signal as it was introduced first in Qt-5.14

src/core/ImportNode.cc, src/core/LinearExtrudeNode.cc, src/core/RotateExtrudeNode.cc, src/core/SurfaceNode.cc, src/core/TextNode.cc, src/core/control.cc, src/core/module.cc, src/core/module.h, src/core/primitives.cc
I got annoyed by how many times I saw the exact same "check for children and warn if there are any" sequence, so I centralized it.  The mechanism is kind of cool:  since the registration mechanism passes the builtin_* function to the constructor, it was easy to just have an alternate constructor that wanted a builtin_function that didn't have a children argument.
=> Centralize checking for children of modules that don't accept children.

src/core/LinearExtrudeNode.cc, src/core/LinearExtrudeNode.h, src/core/Parameters.cc, src/core/Parameters.h, src/core/RotateExtrudeNode.cc, tests/data/scad/3D/features/linear_extrude-parameter-tests.scad, tests/data/scad/3D/features/linear_extrude-tests.scad, tests/data/scad/3D/features/rotate_extrude-angle.scad, tests/regression/echotest/linear_extrude-parameter-tests-expected.echo, tests/regression/echotest/localfiles-compatibility-test-expected.echo, tests/regression/echotest/localfiles-test-expected.echo
linear_extrude allows "h" as an alias for "height". rotate_extrude allows "a" as an alias for "angle". Provides a general-purpose alias-capable lookup function in Parameters. Cleans up linear_extrude parameter processing.
=> Parameter aliases in linear_extrude, rotate_extrude.  Fixes #1609.

src/gui/ScintillaEditor.cc
Turns out alt+scroll on my Linux machine (and probably Windows, given openscad/openscad#4997) switches between horizontal and vertical scroll. If you're holding alt (the default modifier key for the scroll-number feature), the scroll direction is switched, dy is 0, and the code in `master` will always take the false branch. One workaround is to just change the modifier key to LMB.
Here, we just look to see if there _is_ a y delta, and if not, grab the x one instead.
Tested with vertical and horizontal scroll with both LMB and alt as modifiers. Awkwardly, when using an actual horizontal scroll wheel, scrolling right is considered negative (since it moves down the page). Negating `deltaX` would affect the alt+vscroll behavior, though (which currently behaves as expected). Couldn't find a …
=> Bugfix: Alt-scroll with event dx if dy is 0 (address openscad/openscad#4997)

scripts/macosx-build-dependencies.sh
Clipper 1.5.0 reported itself as 1.4.0. 1.5.2 fixes that issue.
=> Bump Clipper2 to 1.5.2

src/geometry/cgal/CGALCache.cc, src/glview/GLView.cc, src/glview/preview/OpenCSGRenderer.cc, src/glview/preview/ThrownTogetherRenderer.cc
#5622 introduced two bugs:
* Doing a preview render _without_ edges, then turning edges on caused bad results or segmentation fault (depending on GL driver)
* A unnecessary warning, "Shader not available" was emitted sometimes
=> VBO refactoring bugfix

src/gui/Animate.cc, src/gui/Animate.h, src/gui/ErrorLog.cc, src/gui/ErrorLog.h, src/gui/FontListDialog.cc, src/gui/FontListDialog.h, src/gui/LibraryInfoDialog.cc, src/gui/LibraryInfoDialog.h, src/gui/MainWindow.cc, src/gui/MainWindow.h, src/gui/MouseSelector.cc, src/gui/MouseSelector.h, src/gui/TabManager.cc
It seems that both camlCase and joint_lower naming scheme are used in openScad, with more names in camlCase. In this PR I renames the ones that were using joint_lower scheme to unify with camlCase.
I didn't renamed the slot because the  automatic of signal/slot relying on naming like the following on_camlCaseName_triggered.
=> [COSMETIC] Renames the method and attributes so they use camlCase

src/geometry/manifold/manifoldutils.cc
Can be seen by attempting to build without CGAL:
```
src/geometry/manifold/manifoldutils.cc:118:17: error: 'optional' is not a member of 'std'
118 |   std::map<std::optional<Color4f>, std::vector<size_t>> colorToFaceIndices;
```
=> std::optional is now always used in manifoldutils.cc

src/gui/TabManager.cc
=> Fix Console output on save error

src/core/LinearExtrudeNode.cc, src/core/Parameters.cc, src/gui/input/HidApiInputDriver.cc, src/openscad_gui.cc
* performance-for-range-copy
* misc-unused-alias-decls
* NOLINT a bugprone-unused-local-non-trivial-variable clang-tidy was confused about.
* performance-unnecessary-copy-initialization
=> Some small clang-tidy fixes

scripts/uni-get-dependencies.sh
[Pop!_OS](https://pop.system76.com/) is a popular distribution[^1] based on Ubuntu.  As for Ubuntu itself, the Debian dependencies are required to build OpenSCAD, so add it to the list of supported distros in the script.
Example /etc/issue content on a machine running Pop!_OS:
Pop!_OS 22.04 LTS \n \l
[^1]: Top 10 in January 2025, per https://distrowatch.com/table.php?distribution=popos
=> scripts/uni-get-dependencies.sh: add support for Debian-like distros using /etc/os-release

src/core/BuiltinContext.cc, src/core/BuiltinContext.h, src/core/Builtins.cc, src/core/Context.cc, src/core/Context.h, src/core/ContextFrame.cc, src/core/ContextFrame.h, src/core/EvaluationSession.cc, src/core/EvaluationSession.h, src/core/Expression.h, src/core/FreetypeRenderer.h, src/core/Parameters.cc, src/core/Parameters.h, src/core/ScopeContext.h, src/core/SourceFile.h, src/core/UserModule.cc, src/core/UserModule.h, src/core/builtin_functions.cc, src/core/customizer/ParameterObject.cc, src/core/function.cc, src/core/node.cc, src/geometry/manifold/manifold-applyops.cc, src/gui/MainWindow.cc, src/io/dxfdim.cc, src/io/import_3mf_dummy.cc, src/io/import_json.cc, src/io/import_obj.cc, src/openscad.cc
Done semi-automatically using the output from clang tidy.
```
../dev-tools/insert-header "core/AST.h" $(awk -F: '/^src.*no header providing.*"Location"/ {print $1}' OpenSCAD_clang-tidy.out)
```
=> Include core/AST.h when using class Location

src/gui/MainWindow.cc, src/gui/MainWindow.h, src/gui/OpenSCADApp.cc, src/gui/OpenSCADApp.h, src/openscad_gui.cc
This cleans up the exit code:
* Try to drive everything using QCoreApplication::quit()
* Remove duplicate "quit on last window closed"
* Removes MainWindow::quit()
* Use QCoreApplication::aboutToQuit to perform cleanup
* Use Qt::QueuedConnection when calling QCoreApplication::quit()
=> Cleanup application exit code

src/glview/GLView.cc
Fixes https://github.com/openscad/openscad/issues/3689
Tested on GNOME Wayland and Qt6
=> Fix transparency issues on Wayland

src/gui/MainWindow.cc, src/gui/MainWindow.h, src/gui/MainWindow.ui, src/gui/RubberBandManager.cc, src/gui/RubberBandManager.h
The issue #5695 was introduced in PR #5630 and reported by @kintel.
The issue is caused by inconsistent handling of the next/prev window action when triggered from menu navigation with mouse and when triggered using their Ctrl+K and Ctrl+H shortcuts. 
To fix it, I had to implement the shortcut Ctrl+K and Ctrl+H differently to differentiate the two cases. When a next/prev dock is activated/hovered because of a keyboard shortcut or because of hovering with mouse the over a menu entry.
The positive consequence is that now the rubberband states are more consistant and are the following:
- when a window menu entry (next/prev or jump to) is hovered, the rubberband is made visible and indicates which dock will be the one activated on menu entry validation/trigerreing. 
- when a window menu entry …
=> Fix issue #5695

src/gui/Animate.cc, src/gui/Dock.cc, src/gui/Dock.h, src/gui/MainWindow.cc, src/gui/MainWindow.h, src/gui/MainWindow.ui, src/gui/TabManager.cc
We have recently start using using https://doc.qt.io/qt-6/qdockwidget.html#toggleViewAction to handle the dock visibility as well as the checkboxes in the menuWindows, 
We also have recently replace the windowActionSelectXXXDock with the"Jump-To" one.  
The consequence of these two is that the show/hide/select/triggered docks methods/slot are not needed anymore. 
So in the PR is remove them and update the connected code. 
The hard part was that the show/hide method were used to handle the visibility, the checkbox states but also to implement "dock" specific behavior when the visibility change. 
This behavior has been preserved  and moved in dedicated slots named onXXXDockVisibilityChanged(bool). 
Normally this PR shouldn't break/change anything. If it does, please report.
=> Clean MainWindow show/hide action

src/glview/cgal/CGALRenderer.cc, src/glview/cgal/CGALRenderer.h, src/gui/MainWindow.cc, src/gui/MainWindow.h, src/io/export_png.cc
Minor cleanup to make #5530 easier to read.
```
[misc-const-correctness]   -57
[misc-include-cleaner]   -93
[misc-unused-parameters]    -2
[misc-use-anonymous-namespace]    +2
[modernize-make-shared]    -3
[performance-unnecessary-value-param]    -2
```
=> Fix a few clang-tidy issues

src/glview/CsgInfo.h, src/glview/NULLGL.cc, src/glview/OffscreenContextNULL.cc, src/glview/cgal/VBOPolyhedron.h, src/glview/preview/ThrownTogetherRenderer.cc, src/glview/preview/ThrownTogetherRenderer.h, src/glview/system-gl.cc, src/glview/system-gl.h
```
[clang-analyzer-deadcode.DeadStores]    -1
[misc-const-correctness]   -10
[misc-include-cleaner]   -25
[misc-unused-parameters]    -4
[misc-use-anonymous-namespace]    +1
[modernize-use-equals-default]    -5
[modernize-use-override]    -1
```
=> clang-tidy fixes: src/glview

cmake/Modules/FindNettle.cmake
Gentoo Linux rewrites /usr/include/nettle/version.h to support multiple ABIs.
Even with Nettle 3.10 installed this results in:
-- Could NOT find Nettle: Found unsuitable version ".", but required is at least "3.0" (found /usr/lib64/libnettle.so)
---
This is from libzip: https://github.com/nih-at/libzip/commit/135bd6dc0523da4d8d2315189e12cebeb7568f9e.
Needed to enable OpenSCAD Python support on Gentoo.
=> FindNettle: Prefer pkg-config Nettle version

.github/workflows/macos-tests.yml
This avoids picking up OpenCSG-1.8.0 from Homebrew as it causes rendering artifacts
=> Use builtin OpenCSG on macOS

src/openscad.cc
Also capitalize ASCII properly in the help message.
=> Remove deprecated -s and -x options.  Fixes #5582.

src/gui/TabManager.cc, src/gui/TabManager.h
Issue #5749 is about segfault on closing the last tab open. 
The issue appears recently because of PR refactoring ux (eg: #5609)
To fix the issue it was suggested to remove the different UI possibilities to do so. 
This is what the PR is actually doing. 
Actually one path remains (but it don't lead to a crash) which goes through the general menu [File] then [Close].
This one goes through TabManager::closeCurrentTab() which, when there is only one tab and the close requested, close the whole application.
=> FIX issue #5749

src/gui/Console.cc, src/gui/Editor.cc, src/gui/InitConfigurator.cc, src/gui/MainWindow.cc, src/gui/OpenCSGWarningDialog.cc, src/gui/Preferences.cc, src/gui/Preferences.h, src/gui/QGLView.cc, src/gui/ScintillaEditor.cc, src/gui/TabManager.cc, src/gui/input/InputEventMapper.cc, src/gui/parameter/ParameterWidget.cc
The class Preferences is currently a mix of static behavior and non static. 
The instance is initialized by calling the method Preferences::create().
Calling it is mandatory to avoid crashing when calling inst(). 
Currently the Preferences creation is done in TabManager::createTab. But I see no rational of having the TabManager in charge of constructing a static variable for the whole application. 
To remove this I refactored the Preferences class to make a purely non static class. 
The static part has been moved into a new class only in charge of this purpose called GlobalPreferences. 
TabManager/Editor specific first initialization is now done once in MainWindow::MainWindow.
=> Refactor Preferences to extract the static part in a singleton

src/core/node.cc, src/core/node.h, src/gui/MainWindow.cc
The getCodeLocation is a free function in MainWindow.cpp while it may/could/should be a member of AbstractNode. 
So I made this.
The advantage is that it removes some lines in MainWindow.cpp (which is quite big:))
=> [CLEAN] Move getCodeLocation from MainWindow to Node::getCodeLocation

src/gui/InitConfigurator.cc, src/gui/InitConfigurator.h, src/gui/Preferences.h
This PR is for fixing the recursive call in static initialization that resulted from the merge of #5779
I have no way to test if the fix is enough..
I did the following to see if there is remaining recursion:
```cpp
Preferences* GlobalPreferences::inst()
{
std::cout << "ENTERING INST" << std::endl;
{
static auto* instance = new Preferences();
std::cout << "LEAVING ENTERING INST" << std::endl;
return instance;
}
};
```
But it would be better if tested on someone's where the segfault happens.
=> Removes the recursive calling to Preferences.

tests/CMakeLists.txt
This fixes Linux non-experimental tests.
=> 3mfexport_3mf-export is experimental and can only be disabled in experimental mode

patches/lib3mf-macos.patch, scripts/macosx-build-dependencies.sh
Before merging, we may need to wait for https://github.com/msys2/MINGW-packages/pull/23855
=> macOS: Bump lib3mf to 2.4.1

.github/workflows/macos-tests.yml
QScintilla for qt5 is not longer available on Homebrew, and it's too much work to keep that running.
Until that's fixed upstream, we're disabling the Qt5 build on macOS.
Qt5 Scintilla Broke in https://github.com/Homebrew/homebrew-core/pull/166414
=> Disable Qt5 build for macOS

doc/openscad.1
Add the following options listed in `--help` that are missing in the manpage:
* -O
* --help
* --help-export
I copied help messages where possible and kept the arguments in the same order.
Screenshot of relevant section of manpage:
=> Add export options to manpage

src/core/ColorNode.cc, src/core/ColorUtil.cc, src/core/ColorUtil.h, src/io/export_3mf_v1.cc, src/io/export_3mf_v2.cc, src/python/pyfunctions.cc, tests/regression/echo/errors-warnings-expected.echo, tests/regression/echo/errors-warnings-included-expected.echo
* Create new `core/ColorUtil.cc` functions `parse_color` and `getColor`. These both accept a string, check it against webcolors, and then attempt to parse it as hex.
* `parse_color` will return false if nothing is found, allowing for functions to handle the error.
* `getColor` will always return a color and will revert to the default while throwing a warning message
* All code has been updated to use these new functions, reducing duplicate logic and standardizing color processing.
* Export 3MF can now have colors specified by name via the command line.
* Pyfunction will now apply alpha channel to colors specified by name and hex.
This change will reduce the amount of duplicate code while implementing additional color support for PDF and SVG outputs: …
=> improve color utils

src/gui/MainWindow.cc
Like the title says.
```
No ASTto dump. Please try compiling first...
```
should be
```
No AST to dump. Please try compiling first...
```
=> Missing space in "No xxxto dump.  Please try compiling first..." message

CMakeLists.txt, locale/cs.po, src/RenderStatistic.cc, src/core/ImportNode.cc, src/geometry/Geometry.h, src/geometry/GeometryCache.cc, src/geometry/GeometryEvaluator.h, src/geometry/GeometryUtils.cc, src/geometry/PolySetBuilder.cc, src/geometry/PolySetUtils.cc, src/geometry/boolean_utils.cc, src/geometry/cgal/CGALCache.cc, src/geometry/cgal/CGALNefGeometry.cc, src/geometry/cgal/CGALNefGeometry.h, src/geometry/cgal/Polygon2d-CGAL.h, src/geometry/cgal/cgalutils-applyops.cc, src/geometry/cgal/cgalutils-project.cc, src/geometry/cgal/cgalutils.cc, src/geometry/cgal/cgalutils.h, src/geometry/manifold/ManifoldGeometry.cc, src/glview/PolySetRenderer.cc, src/glview/cgal/CGALRenderer.cc, src/glview/cgal/CGALRenderer.h, src/gui/MainWindow.cc, src/io/export_3mf_v1.cc, src/io/export_3mf_v2.cc, src/io/export_amf.cc, src/io/export_stl.cc, src/io/import.h, src/io/import_nef.cc
Our Geometry subtype CGAL_Nef_Polyhedron was too easy to mistake for the type alias CGAL_Nef_Polyhedron3. Renaming to make it more clear it's actually an OpenSCAD Geometry.
=> Renamed CGAL_Nef_Polyhedron to CGALNefGeometry

src/gui/TabManager.cc
I would expect the title to update, when the active Tab gets  Saved-As
=> Update Window Title

src/gui/TabManager.cc
Currently stays as Untitled.scad when you File/Open or File/Recent Files
Copied from #5887.
=> Update title bar when a file is opened

src/gui/Dock.cc, src/gui/MainWindow.cc
The QDockWidget::topLevelChanged() signal and its topLevel parameter are reporting changes of the floating property.
Fortunately QWidget::isTopLevel() is now deprecated.
=> Fix checking whether Dock widgets are floating

tests/export_import_pngtest.py, tests/export_pngtest.py, tests/mingw_convert_ctest.py, tests/shouldfail.py, tests/stlexportsanitytest.py, tests/test_cmdline_tool.py, tests/test_pretty_print.py
The shebangs in a few of the python scripts are wrong.
They should refer to `python3` and not `python`, as that's usually python2 which is end of life and probably not what's intended.
And two of the scripts even refer directly to `/usr/bin/python`. All scripts should use `/usr/bin/env python3` so that the correct python binary is selected.
This is causing almost all tests to fail when building for GNU guix, which doesn't follow the traditional FHS, so `/usr/bin/` doesn't even exist.
Should be an easy one to merge though.
=> Fix python shebangs

src/io/import_3mf_v2.cc
3MF import crashes in build-item 4 of the file MicroscopeMainBody.3mf from https://axotron.se/blog/microscope-adapter-for-mobile-phone-camera/
The crash happens in object->Verify() so for now we just disable that call and optimistically assume import will work.
Without the verify call, the import seems to run fine.
```
Parsing design (AST generation)...
Compiling design (CSG Tree generation)...
Compiling design (CSG Products generation)...
import_3mf_v2: METADATA[0]: http://schemas.slic3r.org/3mf/2017/06:Version3mf = '1'
import_3mf_v2: METADATA[1]: Title = 'MicroscopeMainBody'
import_3mf_v2: METADATA[2]: Designer = ''
import_3mf_v2: METADATA[3]: Description = 'MicroscopeMainBody'
import_3mf_v2: METADATA[4]: Copyright = ''
import_3mf_v2: METADATA[5]: LicenseTerms = ''
import_3mf_v2: …
```
=> Fix crash in lib3mf-v2 object verify by just disabling the call.

src/io/export_wrl.cc
Fixes #5998 according to my testing with an online viewer and KiCAD!
So I did some digging in the VRML97 spec and found that each face in the coordIndex list needs to be terminated with `-1` according to https://tecfa.unige.ch/guides/vrml/vrml97/spec/part1/nodesRef.html#IndexedFaceSet
`An index of "-1" indicates that the current face has ended and the next one begins. The last face may be (but does not have to be) followed by a "-1" index.`
I also checked the legal separators to make sure they are also correctly used in the list.
It looks like there is a lot of freedom defined for separator usage, so I changed the output per face in coordIndex to be in one line for improved visual grouping.
From https://tecfa.unige.ch/guides/vrml/vrml97/spec/part1/concepts.html#4.3.1
`Commas, spaces, …
=> Fix WRL export spec violation

tests/CMakeLists.txt
Fixes non-experimental build test failure.
=> Tag object tests as experimental

src/io/export_wrl.cc
Adds Color and ColorIndex fields to IndexedFaceSet.
RGB only, alpha is not supported in WRL file.
=> Add support for per-polygon colour in WRL exports.

src/gui/ScadLexer.cc, src/gui/ScadLexer.h
Closes #5991.
This performs batch highlighting by using the `SCI_SETSTYLINGEX` event. Previously, we were using one event per token for highlighting, which triggers rendering after every single token (apparently, from gdb stepping) and was very slow for large files. With the batch API, this is much faster and can open the 33MB file in less than 10s (most of the time is probably not in highlighting).
=> faster syntax highlighting

src/core/ContextMemoryManager.cc
The ContextMemoryManager had a visitor that returned *vector<Value>. However, not all types have a vector they can hand out a pointer for.  The new API is more generic, it allows to visit each value regardless how it is stored.
Also updated some missing consts.
=> Updated visitors for GC to allow non-vector values

src/core/Settings.cc, src/core/Settings.h, src/gui/MainWindow.cc, src/io/export.cc, src/io/export.h, src/openscad.cc
This runs beautify to clean up the existing code in preparation for: https://github.com/openscad/openscad/pull/6052
Only the code that will be changed has been updated. I've cut an issue to discuss options for cleaning up more: https://github.com/openscad/openscad/issues/6055
=> beautify files before svg export changes

.github/workflows/beautify.yml, doc/hacking.md, scripts/beautify.sh, scripts/hard_beautify.sh, scripts/nix/shell.nix
This change removes `uncrustify` from the codebase and documentation in favor of `clang-format`, and adds a workflow for enforcement.
* Switch to `clang-format` for code formatting
* Add a GitHub workflow to enforce formatting
* Workflow outputs a patch that can be used to resolve issues in the worst-case scenario
* Updated documentation
* Workflow can be run locally using `act`
* `beautify.sh` can be used as a git hook
* Added `hard_beautify.sh` that automatically beautifies code using the git workflow. This is the most accurate method of beautifying code, and can also be used as a git hook.
After this change, the code base will need to be reformatted to allow future pull requests.
https://github.com/openscad/openscad/issues/6055
=> Switch to clang-format and add formatting workflow

.gitignore
I am using CLion as development environment which creates .idea and .clangd files.
I would like to add them to the base setup so I do not have to be overly careful in making commits.
=> Ignore .idea (Intellij/CLion) setup files and .clangd/

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other-development-issue.md, .github/workflows/assign.yml, README.md
Openscad has 893 open issues. 886 of them are not assigned.
I started work on #4246 but I can't mark myself as assigned since I am not a collaborator, but I am marked as "Contributor" so maybe there's an existing permission that allows that, but I don't think that's possible i.e. https://github.com/orgs/community/discussions/13692
Maintainers list was taken from
https://api.github.com/orgs/openscad/members?role=admin and not intended to be authoritative (and also everyone in this list can just edit assignments directly, no?).
I just tested this for OrcaSlicer at
https://github.com/coryrc/OrcaSlicer/issues/4 if you want to see it working.
=> Allow the public to assign issues to themselves

.github/workflows/assign.yml
Once this is fixed, I will send out an announcement email.
The existing message is incorrect. I'm going to send PR to the action's repo to fix it also.
Original message: https://github.com/takanome-dev/assign-issue-action/blob/5cd840e7e688c10cdc933155c3289514d32879fa/action.yml#L64
On my example PR: https://github.com/openscad/openscad/issues/4246#issuecomment-3193001559
=> Correct the message upon getting assigned an issue

src/gui/MainWindow.cc
This commit fixes an issue where OpenSCAD would automatically preview a .scad file on startup, even if the 'Automatic Reload and Preview' setting was disabled.
The fix checks if auto-reload is enabled before triggering a preview when a new editor is opened.
Fixes #6107
=> Fix: Prevent auto-preview on startup when auto-reload is disabled

scripts/wasm-base-docker-run.sh
The `wasm-base-docker-run.sh` script currently mounts the source directory at `/src`
inside the Docker container but doesn't set the working directory. This causes commands
like `cmake` to run from `/home/ubuntu` (the default container working directory) instead
of `/src` where the source code is mounted.
This results in errors like:
CMake Error: The source directory "/home/ubuntu" does not appear to contain
CMakeLists.txt.
**Fix:** Add `-w /src` to the `docker run` command to set the working directory inside
the container to `/src` where the source code is mounted.
**Testing:** This fix allows `make wasm` to work properly when building OpenSCAD WASM
binaries from source.
=> Fix docker working directory in wasm build script

scripts/uni-get-dependencies.sh
I did experiments with building PythonSCAD using Docker.
My Dockerfile looks like this:
```Docker
FROM archlinux:latest
COPY . /opt/openscad
RUN rm -rf /opt/openscad/build
WORKDIR /opt/openscad
RUN scripts/uni-get-dependencies.sh
RUN cmake -B build
RUN cmake --build build -j$(nproc)
WORKDIR /opt/openscad/build
RUN ctest -j$(nproc) --output-on-failure
CMD ["build/openscad"]
```
You can build it with `docker build -f /path/to/dockerfile /path/to/openscad/repository`.
I did tests with a few Linux distributions by changing the `FROM` line accordingly:
```Docker
FROM archlinux:latest
FROM debian:12
FROM fedora:42
FROM linuxmintd/mint22.2-amd64
FROM ubuntu:22.04
FROM ubuntu:25.04
```
With this approach, it's extremely low effort to test whether OpenSCAD builds on a particular flavor of Linux …
=> Fix uni-get-dependencies.sh

src/python/pyopenscad.cc
The `get_fnas` function accidentally tries to load `fs` even if it is not defined, resulting in an exception when generating some objects like sphere() or text().
Fixes: c3d173854efafdc95aa9ff962e5a69b69e7f1590
=> python: Fix `fs` is required when generating some objects

tests/CMakeLists.txt
to support PROJECT_IS_TOP_LEVEL
=> Update CMake dependency for tests to 3.21

src/openscad.cc
This is arguably a PEBKAC problem, but I couldn't make the virtualenv created by OpenSCAD to work, until I realize that it only works when you call `bin/openscad-python`, and `bin/python` and `bin/python3` are broken.
Support calling the OpenSCAD binary as `python` or `python3` in addition to `openscad-python`.
=> python: Run python when called as `python` or `python3` in addition to `openscad-python`

CMakeLists.txt
Similar to the PR's I submitted already, CMake is also silently ignoring if `-DENABLE_GAMEPAD=ON` and Qt5Gamepad is not found.
This patch addresses this and make the build fail properly if the library is missing.
This should prevent users from head-scratching while despite enabling gamepad support during build time, their gamepad still doesn't work in the built application.
I expect the CI/CD pipeline to fail again here, similarly to as it did with #5933.
=> Fix search for Qt5Gamepad in CMake

src/core/parser.y
When parsing large generated scad files with a structure like:
module passages() {
color([0.5, 0.5, 0.5])
passage(9 * dx, -5 * dy, -8 * dz, r2, 3);
color([1, 0.5, 0.5])
passage(7 * dx, -7 * dy, -10 * dz, r, 1)
...
}
I experienced an error
ERROR: Parser error: memory exhausted in file design.scad, line 40108
Increasing the parser stack depth solves the issue.
The same issue has been encountered before, see commit cc1f9e13534a ("quickfix: Increase parser stack depth to allow for larger designs")
Bison uses malloc() by default. The program stack size does not need to be adjusted.
=> parser: increase parser stack depth
