src/Camera.cc, src/Camera.h, src/GLView.cc, src/QGLView.cc, src/mainwin.cc
=> Unify zoom handling for perspective and orthogonal mode.

examples/Advanced/offset.scad, examples/Basics/difference_cube.scad, examples/Basics/difference_sphere.scad, examples/Basics/intersection.scad, examples/Basics/logo_and_text.scad, examples/Basics/surface.scad, examples/Basics/text_on_cube.scad, examples/Basics/translate.scad, examples/Basics/union.scad, examples/COPYING-CC0.txt
- Change the examples written by me to CC0
- Include CC0 license text
=> Change license for example files.

src/MainWindow.h, src/MainWindow.ui, src/UIUtils.cc, src/UIUtils.h, src/mainwin.cc, src/openscad.cc, src/openscad.h
* Add link to open cheat sheet to help menu
* Add version number to documentation and cheat sheet urls (e.g. ```?version=2015.01.14```)
=> Add cheat-sheet link to help menu

locale/cs.po
It is 99 % finished. But I have a few concerns:
What is the meaning here and where is the text displayed? https://github.com/openscad/openscad/blob/master/src/ProgressWidget.ui#L14
https://github.com/openscad/openscad/blob/master/src/Preferences.ui#L1393
=> Updated the Czech translation

locale/cs.po, locale/de.po, locale/es.po, locale/fr.po, locale/openscad.pot, locale/ru.po, src/Preferences.cc, tests/CMakeLists.txt
* Update translation files against latest code changes
* Fix combobx issue (#1188)
* Update German translation (including menu mnemonics)
* Run translation-make.sh from test suite to validate *.po file syntax (#1180)
=> Translations update

locale/de.po, scripts/translation-update.sh
* Extract strings for translation from JSON file.
* Update German translation.
=> Translation updates

locale/cs.po
Please also cherry-pick this to 2015.03 branch. Thanks
=> Czech translation: Add missing space

src/MainWindow.h, src/MainWindow.ui, src/QGLView.cc, src/QGLView.h, src/mainwin.cc
Tested only on Linux so far (Copy to LibreOffice Writer works).
TODO:
=> Add "Export to Clipboard" to copy the current 3d view to the system clipboard.

openscad.pro, scripts/travis-ci.sh, src/import.cc, src/linearextrude.cc, src/openscad.cc, src/parsersettings.cc, src/rotateextrude.cc, src/surface.cc, src/value.cc, src/version_check.h, tests/CMakeLists.txt, tests/export_import_pngtest.py, tests/test_cmdline_tool.py
=> remove OPENSCAD_TESTING build flag

src/MainWindow.h, src/mainwin.cc
=> Use integers for underlying frame counter. Fixes rounding issue #1425

src/Preferences.cc, src/builtin.cc, src/cgaladv.cc, src/color.cc, src/control.cc, src/dxfdim.cc, src/expr.cc, src/func.cc, src/mainwin.cc, src/primitives.cc, src/settings.cc, src/settings.h, src/transform.cc, src/value.cc, src/value.h, testdata/scad/misc/recursion-test-vector.scad, tests/CMakeLists.txt, tests/regression/echotest/recursion-test-vector-expected.echo
All tests pass, but needs further testing.
One question: Are we _ever_ modifying a Value object? If so, this will break spectacularly at some point.
=> No, Values are truly immutable, so we should be safe.
=> Fix #1407 by storing vector values as heap objects (ValuePtr) rather than stack objects(Value)

scripts/uni-get-dependencies.sh
=> use qt5 on ubuntu >=14 mint >=17 (unless qt4 has already been chosen)

src/MainWindow.ui, src/mainwin.cc, src/scintillaeditor.cpp
=> Support Ctrl-Y Redo in addition to Ctrl-Shift-Z

src/scadlexer.cpp
=> Add multiline comment folding. Resolve #1408

src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/scintillaeditor.cpp, src/settings.cc, src/settings.h
Added Check Box for enabling/disabling line number in QScintilla Preference Options.
=> added line number option on editor preferences

locale/es.po
Some corrections to the spanish translation
=> Updated spanish translation

src/Preferences.cc
=> Disable spinbox when it has no effect. Fix issue #1187

src/MainWindow.ui
=> shortcut key for view all (ctrl +shift+ v)

src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/scintillaeditor.cpp, src/settings.cc, src/settings.h
Add backspace unindents option for QScintilla editor
=> Backspace unindents feature

src/scintillaeditor.cpp
This will shrink the margin when Line numbers get disabled.
=> shrink margin on demand

cgal/decompose.cpp, cgal/export_nef.cpp, src/FileModule.cc, src/FontCache.cc, src/ModuleCache.cc, src/ModuleInstantiation.cc, src/PlatformUtils-posix.cc, src/PlatformUtils.cc, src/PlatformUtils.h, src/boost-utils.cc, src/boosty.h, src/colormap.cc, src/context.cc, src/dxfdata.cc, src/fileutils.cc, src/handle_dep.cc, src/import.cc, src/lexer.l, src/mainwin.cc, src/openscad.cc, src/parser.y, src/parsersettings.cc, src/printutils.cc, src/scintillaeditor.cpp, src/value.cc, tests/cgalcachetest.cc, tests/csgtexttest.cc, tests/modulecachetest.cc, tests/tests-common.cc
=>  #1647 remove workarounds for older versions of boost

src/scadlexer.cpp
Fixed issue #1392 
How it looks now:
=> Fix issue #1392. Added folding else/if

src/MainWindow.h, src/MainWindow.ui, src/editor.h, src/legacyeditor.cc, src/legacyeditor.h, src/mainwin.cc, src/scintillaeditor.cpp, src/scintillaeditor.h
How it looks:
I took into account a comment from last pull request and fixed it.
=> Fix issue801. Made Undo button disabled when nothing to undo

scripts/uni-get-dependencies.sh
install dependencies on KDE Neon (current version).
=> dependency helper scripted adapted for KDE Neon distribution

locale/ru.po
File with a Russian translation has been corrected in accordance with the rules of the Russian language.
=> Fix Russian translation

locale/LINGUAS, locale/pl.po
There seem to be a lot of strings without l10n activated. Haven't fixed that, because I didn't want to mix it with Polish translation, but if you want to I can do it in separate PR.
Also I updated pot file, because there were some strings not included in it.
=> Polish translation

src/MainWindow.ui
This breaks compilation with Qt4 as the property was added in Qt5.2.
=> Remove clearButtonEnabled property introduced with #1767.

scripts/macosx-build-homebrew.sh
-- Work in progress for #1832 --
=> Travis-CI optimization tests

patches/QScintilla-2.9.3-xcode8.patch, scripts/macosx-build-dependencies.sh
See #1838 
Fix from: Homebrew/homebrew-core#5877
upstream discussion: https://www.riverbankcomputing.com/pipermail/qscintilla/2016-October/thread.html#1168
=> Patch to allow building QScintilla with Xcode 8

src/lexer.l, src/parser.y
=> Fix parser issue with assert and echo by adding them as separate tokens

src/parameter/groupwidget.cpp
=> Qt theme apply correctly to customizer

src/mainwin.cc, src/parameter/ParameterWidget.cc
Solves Issues #1836. i.e. It doesn't compile two time on Save As.
=> solves #1836 Save As does not do a double compile (preview) after saving

src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/groupwidget.h, src/parameter/parameterextractor.cpp, src/parameter/parameterextractor.h
In reference to issue #1844.  This PR make orders parameter according to there position.
TODO:
=> Orders Parameters as in source code

src/AboutDialog.html, src/mainwin.cc
Just noticed the year was still 2015 in openscad.
=> Updating the years on the copyright notice and might as well get ahead of us

src/scadlexer.cpp
=> Added keyword children

src/parameter/ParameterWidget.cc, src/parameter/parameterset.cpp, testdata/scad/customizer/setofparameter.json, tests/CMakeLists.txt, tests/regression/customizertest-setNameWithDot/setofparameter-expected.ast
Writes and reads set Name with `.` correctly in JSON file. 
TODO:
=> Solves issue #1931

src/lexer.l, testdata/scad/issues/issue1890-comment.scad, testdata/scad/issues/issue1890-include.scad, testdata/scad/issues/issue1890-string.scad, testdata/scad/issues/issue1890-use.scad, tests/CMakeLists.txt
=> Handle unclosed start conditions. Fixes #1890

tests/CMakeLists.txt
Fix for #2007 as per suggestion from Marius.
=> Fix for cgalstlsanitytest_normal-nan test on Windows.

src/MainWindow.ui
- Set max height of status bar.
- Issue #1209
=> Issue 1209 - Fix status bar growing when showing progress bar.

CMakeLists.txt
This is the last change I needed for the cmake build process to complete successfully on my Linux machine.
=> Added QSettingsCached.cc to GUI_SOURCES

src/GeometryEvaluator.cc
Update progress bar as we process 2D items. 
To test open openscad and run the following:
for(o = [0:10:10000]){
translate([o,0])
circle(r=10, center=true);
}
=> Update progress as we process 2D items

src/parameter/ParameterWidget.cc, src/parameter/parameterset.cpp, src/parameter/parameterset.h
=> Removes error related to delete in customizer

locale/es.po
Just for the sake of order. By the way, minor fixes
=> Fixes on shortcuts (et alia), minor fixes in gener

.gitignore, src/OGL_helper.h
Reverts openscad/openscad#2096 due to Qt dependency issues.
=> Revert "DPI Normalized Wireframe Rendering"

src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/input/DBusInputDriver.cc, src/input/InputDriver.h, src/input/InputEventMapper.cc, src/input/InputEventMapper.h, src/input/JoystickInputDriver.h, src/mainwin.cc, src/settings.cc, src/settings.h
Adding UI and backend code for Viewport relative translation
=> UI and backend code for Viewport relative translation

src/GLView.cc
This pull request addresses issue #2020.
It can sometimes be difficult to tell what units the tick marks represent depending on how zoomed in you are relative to the current axes scale. The axes change "units" every time the viewport changes in size by a factor of 10. When you scroll out just past the point where the units change again, you usually can't see any tick labels at all. I added additional labels every 2 minor tick marks that are visible when very few (sometimes 0) major tick marks are visible. I think this makes it a bit easier to tell what the denominations are in those situations.
See the code comment for how to determine whether to show these additional labels given the current zoom level. The threshold is adjustable, but I think it's at a reasonable value now.
Here are …
=> Show minor tick labels when major tick labels are invisible. #2020

src/settings.cc
=> c++11 style for-loop

README.md
Makes the compilation section nicer to read
=> Use backticks on commands in README

src/Preferences.cc, src/Preferences.h, src/input/InputEventMapper.cc, src/input/InputEventMapper.h, src/settings.cc, src/settings.h
trim and deadzone for inputdriver 5.
The UI is allready prepared, but I would like to get feedback on how I store the values for the trim and deadzone.
It is kind of tricky, that the ValueType NUMBER is actually a double, but beeing used as an int.
=> trim and deadzone for inputdriver 5

locale/cs.po, locale/de.po, locale/es.po, locale/fr.po, locale/openscad.pot, locale/pl.po, locale/ru.po
updated the translation files in general,
updated parts of the german translations in particular
=> translation

src/parameter/ParameterEntryWidget.ui, src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/ParameterWidget.ui, src/parameter/groupwidget.cpp, src/parameter/groupwidget.h, src/parameter/parametercheckbox.cpp, src/parameter/parametercombobox.cpp, src/parameter/parameterslider.cpp, src/parameter/parameterspinbox.cpp, src/parameter/parametertext.cpp, src/parameter/parametervector.cpp
=> customizer: try to minimize spacing

src/cgalutils-project.cc, src/cgalutils.cc, src/highlighter.cc
I noticed the auto-formatting tools were having a tough time deciding what to do with these.
=> remove duplicate semicolons

tests/CMakeLists.txt
Also whitespace changes: removed some mixed tabs, made indentation more consistent.
=> Test build should find same packages as main build

src/input/HidApiInputDriver.cc
buttons now working with SpaceExplorer under Linux
=> HIDAPI: fixed buttons with SpaceExplorer under Linux

src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/input/InputDriverManager.cc, src/input/InputDriverManager.h, src/input/InputEventMapper.cc, src/input/InputEventMapper.h, src/mainwin.cc, src/settings.cc, src/settings.h
add option to set the gain for each type of input
=> Inputdriver gain

src/MainWindow.h, src/parameter/ParameterWidget.ui, src/parameter/parameterextractor.cpp
* add tooltips to the customizer buttons
* bugfix: allways rebuild the UI, when a new entry is added
=> Customizer: Tooltips for buttons, rebuild UI when new entry is found

src/export_stl.cc
=> Calculate STL normals from string formatted vertex data for consistency

src/export_stl.cc
Related to #2140 
@thehans Since you touched this code last, would you mind giving it a lookover?
=> Minor refactoring and removal of unused code

CMakeLists.txt
Partially addresses Issue #2227
=> Set cmake path for lexer/parser generated files.

src/input/QGamepadInputDriver.cc
https://doc.qt.io/qt-5.10/qgamepad.html
tested with an XBox360 controller under ubuntu
=> inputdriver5: all buttons mapped

org.openscad.OpenSCAD.xml, src/input/DBusInputDriver.cc
This rework is based on the car example from QT.
I have a simple implementation of the other side of the interface.
I will clean it up and then upload to github as a reference implementation.
=> DBus interface debugged

src/input/JoystickInputDriver.cc, src/input/JoystickInputDriver.h, src/input/SpaceNavInputDriver.cc, src/input/SpaceNavInputDriver.h, src/openscad.cc, src/settings.cc, src/settings.h
* back-end code for setting the joystick number
* spaceNavDominantAxisOnly option
=> Inputdriver5: backend code for inputdriver configuration

src/openscad.cc
"Enable setting for the individual inputdrivers" fixed.
The indentation change is intentional.
Most of the file is using tab indentation.
=> enable setting for the individual inputdrivers fixed

src/MainWindow.h, src/input/AxisConfigWidget.cc, src/input/AxisConfigWidget.h, src/input/AxisConfigWidget.ui, src/input/InputDriver.h, src/input/InputEventMapper.cc, src/input/InputEventMapper.h, src/mainwin.cc, src/settings.cc, src/settings.h
see mailing list
you mainly feel the difference, when you turn the model upside down and try to spin it to the right.
=> inputdriver 5:  view port relativ rotation using qglview->rotate2

src/AboutDialog.html, src/mainwin.cc
just for the record: I have submitted patches for the customizer.
I also submitted patches to inputdriver5, but this is just indirectly relevant.
=> Updating the years on the copyright notices, adding myself to Patches

src/scadlexer.cpp, src/scintillaeditor.cpp, src/scintillaeditor.h
=> Syntax highlighting: adding intersection_for, do not highlight SingleQuotedStrings

src/comment.cpp
see this pull request as a formal question whether iterating over characters or regex is preferred to handle strings in a situation like this.
I would like to add a feature to the customizer and would like to get the coding style down, before writing new code.
=>  rewrite of createGroup using regex 

src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/groupwidget.h, src/parameter/parametervirtualwidget.cpp
My aim is to improve the readability of the code, before changing datastructers and adding features.
=> costumizer: Parameter widget refraction

src/parameter/ParameterWidget.cc, src/parameter/parametervirtualwidget.cpp, src/parameter/parametervirtualwidget.h
* making strings translateable
* turning the private member LabelWidth into the static variable prevLabelWidth
* comment typo fixed
=> Costumizer cleanup

src/func.cc, src/value.cc, src/value.h
=> Cache g_utf8_strlen

testdata/scad/customizer/group.scad, tests/regression/customizertest/group-expected.ast
=> add test case for multiple group names and empty vector

src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/ParameterWidget.ui, src/parameter/parametercombobox.cpp, src/parameter/parameterslider.cpp, src/parameter/parameterspinbox.cpp, src/parameter/parametertext.cpp, src/parameter/parametervector.cpp, src/parameter/parametervirtualwidget.cpp
* only enable the customizer UI when ready 
* descriptionLoD "Description Only" (hiding the variable name when a description is set) 
* set a flag when we have an unreadable json file 
* ask before overwriting unreadable JSON-Files
see also #2316
=> Customizer UI Improvment

src/GroupModule.cc, testdata/scad/misc/scope-assignment-tests.scad, tests/regression/echotest/scope-assignment-tests-expected.echo
I basically copied how ColorModule::instantiate works, minus the code for color-related parameters.
=> Fix issue #1576, local scope assigments in groups.

src/FileModule.cc, src/GroupModule.cc, src/comment.cpp, src/parameter/parametervirtualwidget.cpp, testdata/scad/misc/scope-assignment-tests.scad, tests/export_import_pngtest.py, tests/regression/echotest/scope-assignment-tests-expected.echo, tests/test_cmdline_tool.py, tests/test_pretty_print.py, tests/validatestl.py
optimizing getting the lower case file extension during use registration  -> we should not need to create a copy
optimizing: we only need one EmptyStringLiteral as we can share the pointer to it.
I use a static variable in the method as I do not want to elevate the deceleration to the class level.
initializing static variable  in parametervirtualwidget.cpp
=> Cleanup and optimatzion

README.md
Link to image via coverity needs an update (https://scan.coverity.com/projects/2510). Plus minor fixes (proposals)
=> Update link downloads & documentation (proposal)

src/mainwin.cc
removing the actionRenderPreview(); from MainWindow::changeParameterWidget(), see #2337
=> changes on features should not cause preview

locale/de.po
=> Updated German translation

src/AST.h, src/FileModule.cc, src/exceptions.h, src/expr.cc, tests/regression/echotest/assert-expression-fail1-test-expected.echo, tests/regression/echotest/assert-expression-fail2-test-expected.echo, tests/regression/echotest/assert-expression-fail3-test-expected.echo, tests/regression/echotest/assert-fail1-test-expected.echo, tests/regression/echotest/assert-fail2-test-expected.echo, tests/regression/echotest/assert-fail3-test-expected.echo
based on #2322 closing #1910
testing is an issue
=> writing the filename where the assertion failed

src/mainwin.cc, src/parameter/ParameterWidget.cc, src/parameter/ParameterWidget.h, src/parameter/groupwidget.cpp, src/parameter/groupwidget.h, src/parameter/parametercheckbox.cpp, src/parameter/parametercombobox.cpp, src/parameter/parameterextractor.cpp, src/parameter/parameterextractor.h, src/parameter/parameterobject.cpp, src/parameter/parameterobject.h, src/parameter/parameterset.h, src/parameter/parameterslider.cpp, src/parameter/parameterspinbox.cpp, src/parameter/parametertext.cpp, src/parameter/parametervector.cpp, src/parameter/parametervirtualwidget.cpp
- resolving the multi inheritance in openscad, making the data structure/sharing more explicit.
- this-> to access members
-...
=> Customizer inheritence

src/parameter/ParameterWidget.cc
=> Customizer: Bugfix: Do not save hidden variables

README.md
=> update links: http to https

openscad.appdata.xml.in
Add OARS content rating and basic release information.
See also https://github.com/flathub/flathub/pull/510
=> Improvements for the Appdata file

src/parameter/parametertext.cpp, src/parameter/parametertext.h
=> parametertext.cpp: emit changed() when editingFinished(), not onChanged(QString)

src/parameter/parameterslider.cpp, src/parameter/parameterslider.h, src/parameter/parameterspinbox.cpp, src/parameter/parameterspinbox.h
=> spinbox: emit changed() when editingFinished(), not onChanged(QString)

src/mainwin.cc
=> compile the for TopLevelDocument when a file is opened for customizer

contrib/OpenSCAD.plist
As requested by @MichaelPFrey.
=> Added $preview to OpenSCAD.plist

src/import_amf.cc
No longer uses filsystem::path for XML element path.
=> AMF bug fix for Windows

src/AboutDialog.html
closing tags.
I do not find reference for `lu` tag, so I assume it means `ul`.
`&amp;c` should be more robust then a simple` &c`
=> clean up the html tags in AboutDialog.html

src/editor.h, src/legacyeditor.cc, src/legacyeditor.h, src/mainwin.cc, src/scintillaeditor.cpp, src/scintillaeditor.h
This is an attempt of making updateFindIndicators (currently resetFindIndicator) side effect free.
This should fix #2440
=> making updateFindIndicators side effect free

src/Dock.cc, src/Dock.h, src/QSettingsCached.h, src/mainwin.cc, src/openscad.cc
Looks like this only happens with Qt5.11 on Windows after the gcc7 upgrade. At least it's not reproducable on Linux with Qt5.11.
=> Qsettings fix (fixes #2501)

src/scintillaeditor.cpp, src/scintillaeditor.h
=> Minor cleanup (C++11) of scintillaeditor

locale/es.po
Added missed translated strings
=> Mistake on string #670

src/libsvg/path.cc
Fixes the parsing issue, but also indicates we want to move to a real parser handling all the edge cases.
=> Add workaround for number parsing (fixes #2528).

openscad.pro, src/CSGTreeEvaluator.cc, src/FileModule.h, src/FontCache.h, src/ModuleCache.cc, src/ModuleCache.h, src/StatCache.cc, src/parameter/ParameterWidget.cc
=> FreeBSD and Boost build fixes

src/StatCache.cc
Fixed a regression that made the auto reload and compile take minutes to notice file changes.
=> Fixed the chrono incantataion to get milliseconds.

locale/ru.po
Not much to say here, plumbing work :)
=> Update Russian translation

scripts/generate-potfiles.sh, src/input/AxisConfigWidget.ui
this goes back to #2325. As we currently have other pull requests regarding translation open, I would wait to run the script until those are merged.
=> preperation for inputdrivers translation

src/import_3mf.cc
Oops, forgot to remove the `delete p`.
=> Coverity: CID 192890: (USE_AFTER_FREE).

CMakeLists.txt
Needed these changes for cmake build to complete on Linux Mint 19.
Partially addresses #2518
=> Add Qt5Multimedia and 3mf sources to cmake build.

src/mainwin.cc, testdata/scad/misc/errors-warnings.scad
=> warn, when $vpr $vpt and/or $vpd assignment was not succesful

src/primitives.cc, src/transform.cc, testdata/scad/misc/builtins-calling-vec3vec2.scad, tests/CMakeLists.txt, tests/regression/echotest/allmodules-expected.echo, tests/regression/echotest/builtins-calling-vec3vec2-expected.echo
this partially addresses #2575
=> warning when the parameter could not be converted

CMakeLists.txt, src/modcontext.cc
I can now again compile with CMake and run OpenSCAD on my debian stable 64bit system.
=> some fixes & minor improvements (mostly CMake related)

src/QGLView.cc, src/QGLView.h
=> Implemented cursor-centered mouse wheel zoom.  

features/qscintilla2-priv.prf, scripts/macosx-build-dependencies.sh
* Updated a bunch of library versions for macOS
* Synced qscintilla2-priv.prf from upstream
=> Updated macOS library dependencies

src/OpenSCADApp.cc, src/OpenSCADApp.h
See https://bugreports.qt.io/browse/QTBUG-65592 for details.
=> Add workaround for jumping dock widgets.

src/MainWindow.h, src/MainWindow.ui, src/mainwin.cc
Added copy viewport distance. Copy viewport now copy viewport image and grouped with the others.
=> Viewport paste operations now copy to clipboard.

src/FontCache.cc
=> Fix crash when font wasn't found

src/Preferences.ui
=> split up the advanced preferences into groups

src/CSGTreeEvaluator.cc, src/GeometryEvaluator.cc, src/cgalworker.cc, src/mainwin.cc
by handling HardWarningException in the CGALWorker
http://forum.openscad.org/Prefixed-warnings-and-errors-td25205.html
=> removing the CSG-WARNING prefix

Info.plist, Info.plist.in, appcast-snapshots.xml.in, appcast.xml.in, src/AboutDialog.html, src/SparkleAutoUpdater.mm, src/UIUtils.cc, src/color.cc, src/input/JoystickInputDriver.cc, src/mainwin.cc, tests/regression/echotest/errors-warnings-expected.echo, tests/regression/echotest/errors-warnings-included-expected.echo
This should take care of #2685 and also changes a number of other links that verified ok via https.
=> Update to https links

src/parameter/ParameterWidget.cc, src/parameter/groupwidget.cpp, src/parameter/parametercombobox.cpp, src/parameter/parameterextractor.cpp, src/parameter/parameterspinbox.cpp, src/parameter/parametertext.cpp, src/parameter/parametervector.cpp
- member acces via this-> 
- cleaning up comments
=> Customizer cleanup

src/MainWindow.h, src/mainwin.cc
=> Throttle progress bar updates to 5 per second

src/evalcontext.cc, testdata/scad/misc/errors-warnings.scad, tests/regression/echotest/errors-warnings-expected.echo, tests/regression/echotest/errors-warnings-included-expected.echo
=> warning when an argument is supplied more then once

src/func.cc, tests/regression/echotest/allfunctions-expected.echo, tests/regression/echotest/isundef-test-expected.echo, tests/regression/echotest/len-tests-expected.echo
as discussed on the mailing list.
=> correct the warnings from "length" to "len"

src/CSGTermEvaluator.cc
Cherry-picked from 8fb64db99ce05da1c72efb8b2f572995fef2ea86
=> 2015.03: Build fix for boost 1.69

scripts/macosx-build-dependencies.sh
=> Added double-conversion to macosx-build-dependencies.sh

locale/cs.po, locale/de.po, locale/es.po, locale/fr.po, locale/openscad.pot, locale/pl.po, locale/ru.po, locale/uk.po, src/CGALCache.cc, src/CGALCache.h, src/GeometryCache.cc, src/GeometryCache.h, src/Preferences.cc, src/Preferences.h, src/Preferences.ui, src/cache.h, src/mainwin.cc, tests/cgalcachetest.cc
=> Set cache size in MB, allow >2GB for 64bit

locale/cs.po, locale/de.po, locale/es.po, locale/fr.po, locale/openscad.pot, locale/pl.po, locale/ru.po, locale/uk.po, src/Preferences.ui, src/input/AxisConfigWidget.ui
=> Axis -> Axes (grammer, translation)

src/parameter/ParameterWidget.cc, src/parameter/parameterextractor.cpp
- move the "initialize if empty" code to updateParameterSet to avoid duplication 
- only write the backup, when the set is not empty
- typo in a comment (doen't -> doesn't)
=> Customizer code clean up

src/feature.cc, src/feature.h, src/import.cc, src/import.h, src/import_svg.cc, src/importnode.h, src/libsvg/svgpage.cc, src/libsvg/svgpage.h, src/libsvg/util.cc, src/libsvg/util.h, src/mainwin.cc, tests/CMakeLists.txt
=> Accept SVG import as a stable feature

src/ext/hidapi/hid.c, src/input/HidApiInputDriver.cc, src/input/HidApiInputDriver.h
I left the framework for having different functions in, it's not really a big thing and might come in useful later.
=> HIDAPI: Unify decoder

src/PlatformUtils.h
=> Increase STACK_BUFFER_SIZE from 64 to 128K.

src/MainWindow.h, src/mainwin.cc
If the root module is compiled and hasn't changed F4 would do nothing, even if an included file had been fixed.
=> Fixes F4 and auto preview not working on file load

src/input/AxisConfigWidget.cc, src/input/AxisConfigWidget.h, src/input/AxisConfigWidget.ui, src/input/ButtonConfigWidget.cc, src/input/DBusInputDriver.cc, src/input/DBusInputDriver.h, src/input/HidApiInputDriver.cc, src/input/HidApiInputDriver.h, src/input/InputDriver.h, src/input/InputDriverManager.cc, src/input/InputDriverManager.h, src/input/JoystickInputDriver.cc, src/input/JoystickInputDriver.h, src/input/QGamepadInputDriver.cc, src/input/QGamepadInputDriver.h, src/input/SpaceNavInputDriver.cc, src/input/SpaceNavInputDriver.h
- bar changes color when above deadzone value
- output status information in the axis config dialog
- implementation details improved
- making better use of the status information provided by qgamepad
=> Inputdriver ui improvement

cgal/decompose.cpp, cgal/export_nef.cpp, src/CGAL_OGL_Polyhedron.h, src/GeometryEvaluator.cc, src/Polygon2d-CGAL.cc, src/cgal.h, src/cgalutils-applyops.cc, src/cgalutils-polyhedron.cc, src/cgalutils-project.cc, src/cgalutils-tess-old.cc, src/cgalutils-tess.cc, src/cgalutils.cc, src/cgalutils.h, src/export_nef.cc, src/ext/CGAL/CGAL_Nef3_workaround.h, src/ext/CGAL/CGAL_workaround_Mark_bounded_volumes.h, src/ext/CGAL/OGL_helper.h, src/ext/CGAL/convex_hull_3_bugfix.h, src/import_nef.cc, src/polyset-utils-old.cc, src/version_check.h, test-code/nef_polyhedron_2-bug.cc
Added NDEBUG protection around **ALL** CGAL includes. #2180
=> Fix for issue #2180

releases/2019.02.md
=> Cleaned up/slimmed down release notes a bit

locale/fr.po
I started to change a misleading term in French translation and it led to translating and correcting a bunch of other entries in the fr.po file.
While not complete, this series of patches provide a lot of new translations and several corrections of existing entries (some wrong terms fixed and some improvements).
=> Update in French translation

src/GeometryUtils.cc, src/GeometryUtils.h, src/Reindexer.h, src/cgalutils.cc, src/export_off.cc, src/polyset-utils.cc
=> Have Reindexer return a const ref instead of a pointer into value array.

README.md, scripts/check-dependencies.sh, src/tabmanager.cc
Best effort for supporting 5.3 (default on Debian8) for now as that
should not impact features too much.
=> Update minimum Qt version to 5.4; Fix compilation on Debian8.

.travis.yml, scripts/macosx-build-homebrew.sh, scripts/travis-ci-before-install-linux.sh
...also trying if travis picks up draft pull requests now.
=> Travis updates

src/mainwin.cc
The filename is of previously exported file in export dialog box. This pr corrects that.
=> Corrected file name shown in export dialog box

.circleci/config.yml, src/OffscreenContextGLX.cc, src/linearextrude.cc, src/openscad.cc, src/parameter/parametervector.cpp, src/parameter/parametervector.h, tests/CMakeLists.txt, tests/virtualfb.sh
Batch 2 of cherry picked bugfix commits from https://github.com/openscad/openscad/projects/6.
Up to master: Aug 11, 2019 / fc91c81ffafe07691cec7466399b18f267964328
=> Patch 1 Updates

src/openscad.cc
Follow-up of PR #3033. Reword help and logs for --export-format a bit.
=> Export format logs

src/dxf.cc, src/dxf.h, src/import_dxf.cc
Adding error passing structure to the parser.
=> Dxf import

src/MainWindow.ui, src/mainwin.cc, src/tabmanager.cc, src/tabmanager.h
=> GUI: make CTRL-W close current tab

src/MainWindow.ui, src/editor.h, src/legacyeditor.cc, src/legacyeditor.h, src/scintillaeditor.cpp, src/scintillaeditor.h, src/tabmanager.cc, src/tabmanager.h
Fix merge conflict on #3060 and ensure we end up on correct line even if the source column is larger than the target line length.
=> Jump to error

src/tabmanager.cc, src/tabmanager.h, src/tabwidget.cc, src/tabwidget.h
- Middle mouse click on tab closes
- Middle mouse click in empty area create new empty tab
- Enable close button for active tab only
=> Editor Tab updates

src/FileModule.cc, src/FileModule.h, src/editor.h, src/indicatordata.h, src/legacyeditor.cc, src/legacyeditor.h, src/lexer.l, src/mainwin.cc, src/parser.y, src/printutils.cc, src/printutils.h, src/scintillaeditor.cpp, src/scintillaeditor.h, src/tabmanager.cc, src/tabmanager.h
Based on #3045, implementing location tracking for both `use<>` and `include<>`.
=> Hyperlinks for use/include

locale/fr.po
Completed and corrected french translation.
One important point is the translation of 'saved preset', which enlarge a lot the customizer panel, this tag also using a font much larger than other tags.
=> update french locale fr.po

src/csgnode.cc, src/csgnode.h, src/mainwin.cc
=> Use iteration for CSGOperation::dump and custom CSGOperation deleter

src/mainwin.cc
=> Console messages now only use HTML to highlight errors/warnings.

locale/LINGUAS, locale/zh_CN.po
Add Chinese (china) translation file
=> Add Chinese (china) translation file

locale/pl.po
I've updated the Polish translation (fixed few typos and added new strings)
=> Updated Polish translation

src/value.cc
=> Extra matrix row size check and warnings.

doc/openscad.1, src/AboutDialog.html, src/Preferences.cc, src/mainwin.cc
=> Release updates

src/MainWindow.ui
=> Fix unnamed tab toolbar title bug

src/MainWindow.h, src/MainWindow.ui, src/mainwin.cc
Separate toolbar hide and show is created for editor toolbar and 3D view toolbar has requested in issue #3257 .
=> Separate toolbar hide and show 

src/localscope.cc, testdata/scad/redefinition/redefinition.scad, tests/CMakeLists.txt, tests/regression/echotest/redefinition-expected.echo
=> fix redefinition regression

openscad.pro, src/Preferences.cc, src/Preferences.h, src/initConfig.cc, src/initConfig.h, src/input/AxisConfigWidget.cc, src/input/AxisConfigWidget.h
In reference to  #3014 .
Add InitConfigurator Class
=> Unify setup code in Preferences and AxisConfigWidget [PR]

src/MainWindow.ui, src/mainwin.cc
=> Add Export STL option to Viewer-Toolbar when Editor Pane is hidden 

locale/hy.po
This is a full Armenian translation for OpenSCAD.
=> Create hy.po file

CMakeLists.txt, openscad.pro, src/CGAL_Nef_polyhedron.h, src/GLView.h, src/Geometry.cc, src/Geometry.h, src/OffscreenContext.h, src/OffscreenContextAll.hpp, src/OffscreenContextCGL.mm, src/OffscreenContextGLX.cc, src/OffscreenContextNULL.cc, src/OffscreenContextWGL.cc, src/OffscreenView.cc, src/OffscreenView.h, src/Polygon2d.h, src/QGLView.cc, src/QGLView.h, src/RenderStatistic.cc, src/RenderStatistic.h, src/export.h, src/export_png.cc, src/mainwin.cc, src/openscad.cc, src/openscad.h, src/polyset.h
#3241 with conflict resolved and a few minor cleanups added
=> Print statistics in cmdline mode as in GUI (update)

CMakeLists.txt, openscad.pro, src/CGAL_Nef_polyhedron.h, src/GLView.h, src/Geometry.cc, src/Geometry.h, src/Polygon2d.h, src/RenderStatistic.cc, src/RenderStatistic.h, src/export.h, src/export_png.cc, src/mainwin.cc, src/openscad.cc, src/polyset.h
- Added a helper visitor class to uniformly process Geometry
- Move statistic printing to a dedicated class
- Resolves #2639
=> Print statistics in cmdline mode as in GUI

src/export.cc, src/export.h, src/openscad.cc, tests/regression/echotest/preview_variable-expected.echo
=> Allow export to .ast, .csg, .echo and .term in preview mode

locale/LINGUAS, locale/openscad.pot, locale/zh_TW.po, src/AboutDialog.html
=> Add translation

contrib/scad-mode.el
Added missing 2019.05 keywords to scad-mode.el
=> Added missing 2019.05 keywords.

src/expr.cc
This change removes some warnings when building with clang, and slightly simplifies the inner loop of evaluate_function.
Example warnings:
```
src/expr.cc:966:20: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]                                            
else if (typeid(*subExpr) == typeid(TernaryOp)) {                                              
^                                                                              
src/expr.cc:970:20: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]                                            
else if (typeid(*subExpr) == typeid(Assert)) { …
```
=> Workaround compiler warnings about side-effects in typeid usages

src/parameter/parametertext.cpp
=> Fix crash if non-integer in [max] customizer cmnt

src/func.cc
=> Fix tooltip of tan() and atan2()

src/tabmanager.cc
=> Show Editor(if hidden), on opening new file

src/mainwin.cc
to simplify https://github.com/openscad/openscad/issues/3230 a bit
=> specify the auto-reload timeout in one place

src/UserModule.cc, src/mainwin.cc, src/node.cc, src/node.h, src/renderer.cc, src/transform.cc, src/transformnode.h
Fixed a bug intruduced with #3332, and took the opportunity to display more verbose names in the selection trace.
=> Fix mouseselection, Add Names

src/openscad.cc
Fixes #1632.
Notes:
- I split up the huge `cmdline` function because for animation the second half of this function (which does the actual exporting) needs to be run once for each frame.
- If you don't specify an output filename and only use `--animate N`, the frame filenames will be `frame00000.png`, `frame00001.png`, etc, same as the filenames picked by the GUI's "Dump pictures" feature.
- If you _do_ specify an output filename, e.g. `-o bla.png --animate 20`, the frames are output as `bla00000.png`, `bla00001.png`, etc.
=> Add --animate command line option.

src/feature.cc
=> Have Feature::is_enabled return false when built without ENABLE_EXPERIMENTAL

src/mainwin.cc
=> disable context menu editor switch if editor hidden

src/clipper-utils.cc, testdata/scad/2D/features/minkowski2-tests.scad, tests/regression/dumptest/minkowski2-tests-expected.csg
=> Handle empty first geometry in 2D Minkowski.

src/ErrorLog.cc, src/ErrorLog.h, src/ErrorLog.ui, src/MainWindow.h, src/MainWindow.ui, src/mainwin.cc, src/parameter/ParameterWidget.ui, src/scintillaeditor.cpp, src/tabmanager.cc, src/tabmanager.h
Small step to allow access to all parts of the UI via Keyboard.
=> Add window menu to allow keyboard access to all docked windows (fixes #3509).

src/value.cc, src/value.h, testdata/scad/issues/issue3541.scad, tests/CMakeLists.txt, tests/regression/echotest/issue3541-expected.echo
=> Handle case of flattening during iteration over VectorType.

locale/zh_TW.po
fix a typo and add more translation.
=> Update zh_TW translation

locale/zh_TW.po
polish and add more translation based on the updated template.
=> Update zh_TW translation based on the updated template

src/scintillaeditor.cpp
This follows a recommendation from another project having the same issue as #3614.  It passes a smoke test, but I'm unable to reproduce issue #3614 so I can't promise it actually resolves the issue.  Someone who can reproduce the issue should test this PR to determine if it is a proper resolution.
=> Fix HiDPI non-integer scaling issue #3614

.gitignore
Makefile.{Debug,Release}
object_script.openscad.{Debug,Release}
release
=> Add some build artifacts to .gitignore.

src/scintillaeditor.cpp
see #3664 for motivation.
closes #3664
=> Make jumped-to lines more visible by sliding +-3 lines into view

src/Camera.cc
=> Downgrade the $vp  warning to UI_Warning, allowing --hardwarnings

tests/test_pretty_print.py, tests/validatestl.py
This is not something useful but merely an attempt to convey readiness to work for GSoC project.
=> Test pull request to prove readiness to work for GSoC

src/feature.cc
=> Comments describing how features are set/ordered

src/import_stl.cc
The recent cve entry motivated me to examine import_stl and try to boost up the quality of the rest of it.  I tightened up the checks and error handling, and cleaned up some strict aliasing violations.
=> Robustness improvements to import_stl

src/arguments.cc, src/arguments.h, src/linearextrude.cc, src/parameters.cc, src/parameters.h
=> Repair linear_extrude argument parser broken earlier during some overzealous simplification.

scripts/msys2-install-dependencies.sh
=> MSYS2 dependency script cleanup:  add ImageMagick, drop pkg-config

src/openscad.cc
CSG and AST get extra treatment due to #128, trying to make sure relative path work inside the files.
=> Restore CWD after module instantiation (fixes #3879).

src/ScintillaEditor.cc, src/ScintillaEditor.h
This fixes #3899.  (Also some tab/space issues were fixed in the area of work.)
=> Fix alt-uparrow tab crash

src/AboutDialog.html
My attempt to make About dialog more appealing.
I used donation button from https://opencollective.com/openscad/donate/button.png?color=blue with slight modifications to reduce file size, so you might want to check thier clause 13 at https://opencollective.com/tos regarding copyright and licensing, if you decide to merge this.
Other changes include simplifying html structure, removing dependency on particular fonts, removing duplicate contributor's name entry, updating website URLs if redirects or switched to HTTPS, proper GitHub name spelling, etc.
If you have any questions, I'll gladly explain every change made.
=> Eye candy for About dialog.

src/FontListTableView.cc, src/MainWindow.cc, src/ProgressWidget.h, src/QGLView.cc, src/ScintillaEditor.cc, src/qt-obsolete.h
Rebased against fresh origin/master.
=> Qt5 deprecations

scripts/macosx-build-dependencies.sh
=> Add more macOS versions.

scripts/macosx-build-dependencies.sh
=> Bump hidapi to version 0.11.0.

.circleci/config.yml, scripts/macosx-build-dependencies.sh
=> macOS package upgrade: 

.github/workflows/macos-snapshot.yml
This is currently mostly for completeness of build configs and to test that CircleCI and Github build are equivalent.
=> Build macOS snapshot on GitHub Actions

templates/CC0.json, templates/cc0.json
option for text:
»
// This work is released with CC0 into the public domain.
// https://creativecommons.org/publicdomain/zero/1.0/
«
=> Add CC0 txt in templates

src/ScadLexer.cc
It's a good day when you can fix UI bugs by removing code.
=> fix #4047, change from glyph count to byte count in setting styling

scripts/installer.nsi
* use secure https instead of http
* default openscad homepage moved to non www.
=> Update windows installer links

src/PlatformUtils-win.cc
Merging this change independently of #4067.  
We need output working on Windows to verify if mimalloc is functioning at all, using the current static override method.
=> Register mimalloc output handler for Windows.

src/export.cc
Follow up to https://github.com/openscad/openscad/pull/4146 (for https://github.com/openscad/openscad/issues/420), I'm getting some -0 vs. +0 / Debug vs. Release diffs in remeshing outputs from https://github.com/openscad/openscad/pull/4117
=> [sort-stl] Canonicalize -0 to +0

src/gui/MainWindow.cc, src/gui/QGLView.cc, src/gui/QGLView.h, src/openscad.cc
Only QOpenGLWidget should be used now.
=> Remove obsolete QGLWidget preprocessor checks etc.

src/io/export_3mf.cc
src/io/export_3mf.cc: Missing wrapper parameter in new append_polyset
call.
=> Fix lib3MF version 2.0 build

src/core/IndicatorData.h, src/core/SourceFile.cc, src/core/lexer.l, src/gui/ScintillaEditor.cc, tests/CMakeLists.txt, tests/data/scad/misc/linenumber.scad, tests/regression/echotest/linenumber-expected.echo
fixes #4210, adds regression test for #4210
note: this could interact with #4209, so after merging either, the other merge requests tests should be rerun.
=> debug GUI indicator, lexter line numbers, lexter column numbers

tests/regression/echotest/include-recursive-test-expected.echo, tests/regression/echotest/include-tests-expected.echo, tests/regression/echotest/linenumber-expected.echo
#4211 added a test case
#4209 added details to an error message
#4211 triggers the changed message in #4209
=> regenerate expected echo to fix interaction of two pull requests

src/gui/MainWindow.cc, src/gui/Preferences.cc, src/gui/Preferences.h, src/gui/Preferences.ui
=> add auto clear console option to preferences

src/gui/MainWindow.cc, src/io/export.cc, src/io/export.h
Let me know if you are happy with the proposed change. Fixes #3963.
=> issue 3963

src/gui/TabManager.cc
=> Show manual overwrite confirmation only in the correct context

src/glview/GLView.cc
the gradient back only worked properly with show axis enabled.
=> gradient background needs GL_MODELVIEW

src/gui/MainWindow.cc, src/gui/Preferences.cc, src/gui/Preferences.h, src/gui/Preferences.ui, src/gui/QGLView.cc, src/gui/QGLView.h, src/gui/Settings.cc, src/gui/Settings.h
Please, let me know if you are not happy with the change.
Fixes  #3981.
=> Add Option to Invert Mouse Buttons on 3DView

examples/Basics/hull.scad, examples/examples.json, tests/regression/dumptest-examples/hull-expected.csg
I created a hull example of a toy sailboat, added it to the examples/basic folder and updated the examples.json.
=> Resolves Issue #355 - added a hull example to basic examples

src/geometry/GeometryEvaluator.cc
using max slices of twist and non uniform scale to prevent reduction of slices due to twist component in non uniform extrusion
=> linear_extrude slices calculation

src/gui/MainWindow.cc, src/gui/MainWindow.h, src/gui/MainWindow.ui, src/gui/TabManager.cc, src/gui/TabManager.h
=> Add "Save a Copy" menu option

.github/workflows/macos-tests.yml
Applying this fix separately from PR #4384
=> Fix mac test report uploads.

src/Feature.cc, src/core/CSGTreeEvaluator.cc, src/core/ColorNode.cc, src/core/Expression.cc, src/core/Parameters.cc, src/core/ProjectionNode.cc, src/core/RenderNode.cc, src/core/SourceFileCache.cc, src/core/TextNode.cc, src/core/Value.cc, src/glview/OffscreenContextEGL.cc, src/glview/OffscreenContextGLX.cc, src/glview/OffscreenContextNULL.cc, src/glview/OffscreenContextWGL.cc, src/glview/OffscreenView.cc, src/glview/system-gl.cc, src/gui/input/DBusInputDriver.cc, src/gui/input/HidApiInputDriver.cc, src/gui/input/JoystickInputDriver.cc, src/gui/input/SpaceNavInputDriver.cc, src/gui/parameter/ParameterSlider.cc, src/gui/parameter/ParameterSpinBox.cc, src/handle_dep.cc, src/io/dxfdim.cc, src/io/export_amf.cc, src/io/export_stl.cc, src/openscad.cc, src/utils/exceptions.h, src/utils/printutils.h
Splitting out this change from #4384
=> Replace STR macro with recursive template function.

scripts/release-common.sh
This shouldn't have any noticeable effects; just cleanup.
=> release-common.sh: Added some docs, removed obsolete -c and tests args

scripts/macosx-build-dependencies.sh
=> Bump mpfr to 4.2.0

CMakeLists.txt
Output Eigen version when found.
Output bugfix release for CGAL when found.
=> Improve package version output for Eigen and CGAL

tests/CMakeLists.txt
Temporary workaround for #4470
=> Disable flaky test

CMakeLists.txt, tests/CMakeLists.txt
* Don't install Manifold dependencies (did install clipper2)
* Don't install venv from tests folder
=> Update make install

src/glview/GLView.cc, src/glview/OffscreenContextCGL.mm, src/glview/VBORenderer.cc, src/glview/VertexArray.cc, src/glview/VertexArray.h, src/glview/cgal/CGALRenderer.cc, src/glview/cgal/CGAL_OGL_VBOPolyhedron.h, src/glview/cgal/CGAL_OGL_VBO_helper.h, src/glview/fbo.cc, src/glview/preview/OpenCSGRenderer.cc, src/glview/preview/ThrownTogetherRenderer.cc, src/glview/system-gl.cc, src/glview/system-gl.h, src/gui/MouseSelector.cc, src/gui/QGLView.cc
Moved into common macros in system-gl.h
TODO:
=> Refactored all the various GL error checking macros

snap/snapcraft.yaml
* Update cmake using Snap package
* Bump OpenCSG to version 1.5.1
* Bump CGAL to version 5.5.2
* Clone git submodules for builds with Manifold
* Switch to Clang and update libraries
=> Fix Snap package build

src/glview/OffscreenContextCGL.mm, src/glview/OffscreenContextEGL.cc, src/glview/OffscreenContextGLX.cc, src/glview/OffscreenContextNULL.cc, src/glview/OffscreenContextWGL.cc, src/platform/PlatformUtils-mac.mm, src/platform/PlatformUtils-win.cc
Green refactoring to make future PRs less messy
=> Removed duplicate machine info which is already provided by PlatformUtils

.circleci/config.yml, .github/workflows/codeql-analysis.yml, .github/workflows/linux.yml, README.md, scripts/docker-build.sh, scripts/release-common.sh
This brings mainly:
- #elalish/manifold/issues/389 -> may fix some of the random test case crashes
- #elalish/manifold/issues/408 -> fixes disapearing geometry in higher resolutions
- #elalish/manifold/issues/404 -> may fix the mirror winding order issue?
=> Bump manifold version to latest master.

src/geometry/cgal/cgalutils-applyops.cc
Makes the following model 10% faster to render
```js
$fn=1000;
hull() {
sphere();
translate([0.5, 0, 0])
sphere();
}
```
Also, the code is now simpler (reindexer was already building a vector of points for us)
=> Speed up hull() w/ better reserve & less alloc

src/core/FreetypeRenderer.cc, src/core/Value.cc, src/core/builtin_functions.cc, src/core/lexer.l, src/core/str_utf8_wrapper.h
Green refactoring.
Stepping stone towards easily experimenting with glib alternatives.
=> Isolate glib usage to str_utf8_wrapper

patches/gmp-macos-x18.patch, scripts/macosx-build-dependencies.sh
=> Apply gmp patch to avoid using register x18

src/gui/QGLView.cc, src/gui/QGLView.h
=> Make FOV changeable via GUI

src/glview/OffscreenView.cc
=> Fall back to GLX if we're using GLEW

doc/openscad.1
Text copied from `openscad --help` which already documents them.
=> Document asciistl and binstl in the man page.

src/glview/VertexStateManager.cc
=> Enable tracing of remaining glBindBuffer/glBufferData calls

tests/CMakeLists.txt
Disable failing tests related to #3567
=> Disable known failing non-manifold tests

src/geometry/GeometryEvaluator.h, src/gui/MainWindow.cc, src/io/export.cc, src/io/export.h, src/openscad.cc
Just minor stuff, PRing as a separate PR to make subsequent PRs simpler
=> Minor green refactoring

tests/CMakeLists.txt, tests/cgalstlsanitytest.py
Also updates a test script to handle --enable arguments
=> Enable VBO for all tests in experimental mode

src/glview/VertexArray.cc
=> Bugfix: Forgot to wrap some VBO GL calls in a VBO feature check

src/core/SurfaceNode.cc, src/core/primitives.cc, src/geometry/PolySetBuilder.cc, src/geometry/PolySetBuilder.h, src/geometry/cgal/Polygon2d-CGAL.cc, src/geometry/cgal/cgalutils-mesh.cc, src/geometry/cgal/cgalutils-polyhedron.cc, src/geometry/cgal/cgalutils.cc, src/geometry/roof_vd.cc, src/io/import_3mf.cc, src/io/import_amf.cc, src/io/import_stl.cc
=> Add convenience methods addVertex/prependVertex taking Vertex3d

src/core/FreetypeRenderer.cc, src/geometry/GeometryUtils.cc, src/geometry/PolySet.cc, src/geometry/PolySetUtils.cc, src/geometry/boolean_utils.cc, src/geometry/cgal/cgalutils-mesh.cc, src/geometry/manifold/ManifoldGeometry.cc, src/geometry/manifold/manifold-applyops-minkowski.cc, src/geometry/manifold/manifoldutils.cc, src/gui/MainWindow.cc, src/gui/QGLView.cc, src/io/export_obj.cc, src/io/export_stl.cc, src/io/export_wrl.cc, src/io/import_stl.cc
Fixed some compiler warnings and removed unused stuff.
=> fixed some compiler warnings

src/gui/Preferences.ui
This is an indentation fixup only.  The net result here is an empty `git diff -b`.
=> Fix indentation in Preferences.ui

src/io/export.cc, src/io/export.h, src/io/export_3mf.cc, src/io/export_stl.cc
=> Rewrote ExportMesh into a function createSortedPolySet()

src/io/export_stl.cc
Closes #4981.
This is a simple infinite recursion.
=> fix append_stl infinite recursion

src/geometry/GeometryEvaluator.cc, src/geometry/cgal/CGALCache.cc, src/geometry/cgal/CGALCache.h, src/gui/MainWindow.cc, src/gui/Preferences.cc
Use CGALCache to store any engine-specific geometry.
Fixes #4753
=> Minor caching cleanup

src/geometry/cgal/cgalutils.cc, src/glview/VBORenderer.cc, src/glview/VBORenderer.h, src/glview/VertexArray.cc, src/glview/VertexArray.h, src/glview/cgal/CGAL_OGL_VBO_helper.h, src/glview/preview/OpenCSGRenderer.cc, src/glview/preview/OpenCSGRenderer.h
Also adds back indexing support for CGALRenderer (#4968)
=> Another batch of green VBO cleanup

src/io/import_obj.cc
using information provided by builder.vertexIndex
=> Fix for kintel's obj file cube corner testcase .

src/RenderStatistic.cc, src/core/ImportNode.cc, src/core/primitives.cc, src/geometry/GeometryEvaluator.cc, src/geometry/PolySet.cc, src/geometry/PolySet.h, src/geometry/PolySetUtils.cc, src/geometry/boolean_utils.cc, src/geometry/cgal/cgalutils-applyops-hybrid-minkowski.cc, src/geometry/cgal/cgalutils-hybrid.cc, src/geometry/cgal/cgalutils.cc, src/geometry/manifold/ManifoldGeometry.cc, src/geometry/manifold/ManifoldGeometry.h, src/geometry/manifold/manifold-applyops-minkowski.cc, src/geometry/manifold/manifoldutils.cc, src/io/export.cc, src/io/import_3mf.cc, src/io/import_amf.cc, src/io/import_obj.cc, src/io/import_off.cc, src/io/import_stl.cc, src/openscad.cc, tests/data/scad/3D/misc/polyhedron-self-touch-face-nonmanifold.scad, tests/data/scad/3D/misc/polyhedron-self-touch-vertex-nonmanifold.scad, tests/data/scad/3D/misc/polyhedron-self-touch-vertex.scad, tests/data/scad/3D/misc/polyhedrons-touch-edge.scad, tests/data/scad/3D/misc/polyhedrons-touch-face-nonmanifold.scad
Green refactoring, in preparation of fixing #5022
=> More PolySet Refactoring

scripts/git-archive-all.py, tests/test_pretty_print.py
=> chore(python): use py3 class declaration

scripts/git-archive-all.py
=> chore(python): simplify to `yield from`

scripts/circleci-download-artifacts.py
Replace format with specifier with f-string
=> chore(python): migrate string format

scripts/macosx-build-homebrew.sh
Temporary workaround for #5058 until something more permanent is in place.
=> Add workaround for broken QScintilla2 for Qt5

src/core/primitives.cc
This fixes a problem discussed in the [I'm still confused about Manifold](https://lists.openscad.org/empathy/thread/O6OZBFORSBNYT3HKQHW4VDSWTOEU2TOP) mailing list thread:
Cones were generated with identical connectivity as cylinders; but with degenerate triangles near the peak of the cone. This PR generates only the necessary vertices and triangles.
=> Create better geometry for cones

src/platform/PlatformUtils-mac.mm
=> Bugfix: Color schemes no loading due to uninitialized pointer

.github/workflows/codeql-analysis.yml, .github/workflows/non-experimental.yml, scripts/github-ci.sh, src/geometry/Geometry.h, src/geometry/GeometryEvaluator.cc, src/geometry/GeometryUtils.cc, src/geometry/cgal/CGALCache.cc, tests/CMakeLists.txt
Also adds a workflow to execute on each push to master, which fixes #4875
=> Build fix: Make non-experimental build work again

.github/workflows/linux-build-matrix.yml, .github/workflows/linux-tests.yml, scripts/uni-get-dependencies.sh, tests/CMakeLists.txt
Depends on https://github.com/openscad/openscad/pull/5095.
=> Add minimum Linux build without tests using the support scripts.

.circleci/config.yml, .github/workflows/codeql-analysis.yml, .github/workflows/linux-build-matrix.yml, .github/workflows/linux-tests.yml, .github/workflows/macos-release.yml, .github/workflows/macos-tests.yml, .github/workflows/manual.yml, .github/workflows/non-experimental.yml, .github/workflows/windows.yml
Make action names more human readable
=> Better action naming

src/gui/MainWindow.cc
=> Use saveGeometry() instead of trying to restore size/position separately.

src/core/OffsetNode.cc
=> Fix tooltip for offset().

src/gui/ViewportControl.cc, src/gui/ViewportControl.h, src/gui/ViewportControl.ui
See https://github.com/openscad/openscad/issues/4706#issuecomment-2078433263
=> Support horizontal and vertical layouts (fixes #4706).

src/gui/Animate.cc, src/gui/Animate.h, src/gui/Animate.ui
[Screencast from 2024-04-26 21-53-27.webm](https://github.com/openscad/openscad/assets/1330241/22fe51b7-2650-4375-8aa6-c6a4b5dc3ce8)
Fixes  #4899.
=> Update animation window layout; Simplify horizontal/vertical switch.

src/geometry/GeometryEvaluator.cc
=> Remove duplicate rotatePolygon()

.github/workflows/codeql-analysis.yml, .github/workflows/linux-tests.yml, .github/workflows/manual.yml, .github/workflows/non-experimental.yml, scripts/github-ci-linux-get-dependencies.sh
msgfmt is required to build:
```
msgfmt -c -v -o ./locale/cs/LC_MESSAGES/openscad.mo ./locale/cs.po
./scripts/translation-update.sh: 86: msgfmt: not found
error running msgfmt
```
=> Always install gettext for Linux testing

.github/workflows/windows.yml, scripts/msys2-install-dependencies.sh
Windows test. We do want Qt 5 and Qt 6?
=> Test building with Qt 6 on Windows

src/io/export_amf.cc, src/io/import_amf.cc
=> Add deprecation warning for AMF import+export

src/gui/ViewportControl.cc
=> Fix dark theme color

src/io/import_off.cc
=> Fix OFF import of clors in float format

src/core/SurfaceNode.cc, src/geometry/linear_extrude.cc, src/glview/cgal/CGAL_OGL_VBO_helper.h
Running this causes a bunch of tests to trigger asan errors. This CL fixes the errors surfacing on macOS:
```
cmake -DEXPERIMENTAL=1 -DCMAKE_BUILD_TYPE=Debug -DSANITIZE_ADDRESS=1 ..   
make -j20
ctest -j20
```
=> Fix errors found by running all tests with ASAN enabled

README.md
Don't propose any parallel builds in the default commands, leaving that to the user in case they know their system can handle that.
=> Remove -j suggestions

.github/workflows/macos-tests.yml, src/gui/Settings.cc
=> Bugfix: Default render backend was wrong, confusing the settings writer

.github/workflows/macos-tests.yml, src/gui/MainWindow.cc
=> Check validity of manifold before exporting

src/gui/MainWindow.cc
=> Make Design->Check validity support Manifold

src/gui/QGLView.h
Context:
https://github.com/openscad/openscad/pull/5371#issuecomment-2409121011
=> Work around bad interaction of including glew and QOpenGLContext

src/geometry/GeometryEvaluator.cc
=> fix rotate extrude

src/openscad.cc, src/platform/PlatformUtils.cc
=> Fix resource folder lookup (fixes #5394).

.circleci/config.yml, scripts/release-common.sh
=> Automatically sign and notarize development snapshots.

.circleci/config.yml, scripts/macosx-build-dependencies.sh
=> macOS deps update: Added pcre2, bumped gettext and glib2, removed static libs + some cleanup

src/openscad.cc
Introduce new `--animate_sharding=<shard>/<num_shards>` flag that
allows to output a subset of animation frames.
e.g. `--animate_sharding=2/5` only outputs the second 1/5 of all shards.
This allows an easy parallelization on a machine with multiple cores,
or even distribute the work to multiple machines.
A typical use could be like this: run two instances and divide
the work into two shards that output the first and second half
of the frames.
```bash
openscad -q --animate=42 --animate_sharding=1/2 foo.scad &
openscad -q --animate=42 --animate_sharding=2/2 foo.scad &
wait
```
(of course, one would use probably more shards closer to the
number of cores on the machine).
Issues: #5467
=> Allow to do --animate work in shards.

src/core/DrawingCallback.cc, src/core/DrawingCallback.h, src/core/FreetypeRenderer.cc, src/core/FreetypeRenderer.h, src/core/TextNode.cc, src/core/TextNode.h, src/core/primitives.cc, src/geometry/ClipperUtils.cc, src/geometry/ClipperUtils.h, src/geometry/GeometryEvaluator.cc
..plus some other minor cleanup preparing for Clipper2.
=> Move projection implementation into ClipperUtils

src/gui/MainWindow.cc
=> Don't use the mappedInt signal before Qt-5.15

.gitignore
(this is the directory name mentioned in the readme for wasm builds)
=> Add build-web to .gitignore

src/glview/GLView.cc, src/glview/Renderer.h, src/glview/VBORenderer.cc, src/glview/cgal/CGALRenderer.cc, src/glview/cgal/CGALRenderer.h, src/glview/preview/OpenCSGRenderer.cc, src/glview/preview/OpenCSGRenderer.h, src/glview/preview/ThrownTogetherRenderer.cc, src/glview/preview/ThrownTogetherRenderer.h, src/gui/MainWindow.cc
* We always need to prepare for viewing edges; always enable barycentric coordinates, clean up interfaces
* Fix broken picking
=> VBO refactoring: We're getting close

src/LibraryInfo.cc, src/python/pyfunctions.cc, src/python/pyopenscad.cc, src/python/pyopenscad.h
and object oriented calls
this will enable to even do some useful things
=> union, difference, intersection and translate added

CMakeLists.txt, src/LibraryInfo.cc, src/core/node.h, src/core/node_clone.cc, src/gui/CGALWorker.cc, src/gui/MainWindow.cc, src/gui/TabManager.cc, src/python/pyfunctions.cc, src/python/pyopenscad.cc, src/python/pyopenscad.h, src/python/python_public.h
now have minimal set to do useful design.
node cloning and python gil locks
enhanced python acceptance
=> Python pr5

resources/icons/macos-icon-sources/icon.sh, scripts/check-dependencies.sh, scripts/common-build-dependencies.sh, scripts/setenv-macos.sh, scripts/setenv-unibuild.sh, scripts/uni-get-dependencies.sh, scripts/wasm-base-docker-run.sh, tests/wasm-check.sh
Add missing shebang to fix #5698.
Add missing shebangs to other scripts as well, while we're already at it.
=> Fix check dependencies.sh

src/python/pyfunctions.cc, src/python/pyopenscad.cc
added all openscad legacy functions, which are available with my fork
added code to help python forget at reinit
=> completing all legacy functions which are available with my fork

src/openscad.cc
=> Add missing "param" and "pov" in help.  Copy edit. Fixes #5707.

releases/next.md
=> Populated release notes for next release

CMakeLists.txt, src/geometry/GeometryEvaluator.cc, src/geometry/linear_extrude.h, src/geometry/rotate_extrude.cc, src/geometry/rotate_extrude.h
Green refactoring prior to addressing #5555
=> Refactoring: Extract implementation details of rotate_extrude into separate file

tests/regression/dumptest-examples/example007-expected.csg, tests/regression/dumptest-examples/example008-expected.csg, tests/regression/dumptest-examples/example009-expected.csg, tests/regression/dumptest-examples/example010-expected.csg, tests/regression/dumptest-examples/example012-expected.csg, tests/regression/dumptest-examples/example013-expected.csg, tests/regression/dumptest-examples/example015-expected.csg, tests/regression/dumptest-examples/example016-expected.csg, tests/regression/dumptest-examples/projection-expected.csg, tests/regression/dumptest-examples/surface_image-expected.csg
The PR (#5671) to support import(center=) forgot to update examples tests.
=> Updated examples tests after implementing import(center=)

src/gui/MouseSelector.cc, src/gui/QGLView.cc
=> MouseSelection fix: Make context current, manage state

locale/es.po
I am not fluent in Spanish, but was able to improve it a little. Removed automatic translations that were obviously wrong. Added a few easy translations. It is nor usable yet, but closer to.
=> Improve the spanish translation

locale/LINGUAS, locale/pt_BR.po
Add the pt-BR translation.  Still needs improvement, but I believe it is already usable.
=> Add the pt-BR translation

src/io/export_pdf.cc
Moved grid code inside of ShowScale code to align behavior with Export PDF Dialog options.
=> Update export_pdf.cc for Issue #5868

src/gui/MainWindow.cc
=> Update copyright to 2025.

src/glview/GLView.cc
Another attempt to suport OpenSCAD
=> prevenrt segfault

src/python/pyfunctions.cc
'r' was a required argument when it should not be
=> Python: Fix argument processing in offset

scripts/nix/shell.nix
Add a few fixes for developing on Nix.
=> include gsettings and utilities in nix shell

src/core/control.cc
Dont need it often, but Help was not helping intially
=> In-App Help is misleading

scripts/macosx-build-dependencies.sh
=> Bumped harfbuzz to 11.4.1, added libgraphite2

.github/workflows/macos-tests.yml
=> Workaround for pinned CMake

scripts/beautify.sh
=> Add beautify.sh --staged

src/core/NodeCache.h, src/python/pyfunctions.cc
Reverts openscad/openscad#6209
sorry, not my intent!
I was about to merge a branch in pythonscad, but this happened instead. 
github bug ?
=> Revert "Allow list of vectors"

src/gui/LaunchingScreen.ui
=> Use nightly icon for nightly build
